### ISSUE TITLE
Live boot screen lock cannot be unlocked

### ISSUE THREAD

**Issue by karatedog** [archcraft-os/archcraft#103]
After booting with the liveuser user/pass when the  screen lock is activated it cannot be unlocked with the 'liveuser' password (which is the password for the 'liveuser' user)

**Comment by SimonLegros** [comment]
I had the same issue, rebooted and it worked fine

**Comment by SimonLegros** [comment]
Yeah sorry for the missing context. The OS and the lock-screen worked fine for me after reboot. I have to say though that I didn't test locking the screen after logging in, I launched the installation immediately and created a new user.

**Comment by adi1090x** [comment]
I'm not sure why some users face this issue, for me and for majority of the users, this was never an issue.

**Comment by karatedog** [comment]
I've installed Archcraft in Virtualbox, that might causing issuest.
One thing to note, I use different Arch and Debian setups and when I shut down or reboot any of the VMs, all of them except the Archcraft crashes Virtualbox.

**Comment by adi1090x** [comment]
So it's a good thing, Right?
your VM doesn't crash, Yeee!!!
