### ISSUE TITLE
LVM cannot be selected/installed with GUI installer and it crashes the installer with the Expert installer

### ISSUE THREAD

**Issue by karatedog** [archcraft-os/archcraft#104]
Installing under Virtualbox with a single HDD device.
Even physical disks are listed in the Partitions, new volume group cannot be created as no physical device is listed under New Volume Group.
Switching to Expert mode allows the selection of the physical devices into the Volume Group but pressing OK on the selections crashes the installer.

**Comment by adi1090x** [comment]
LVM is not fully supported in Calamares, It's there but it's all buggy.

**Comment by adi1090x** [comment]
were you trying to install Archcraft on a physical disk via Virtualbox?

**Comment by karatedog** [comment]
Sorry, I meant virtual HDD. I had to manually create the disks, the LVM stuff. Then the installer could skip this step and continue.

**Comment by KiranWells** [comment]
I also attempted to use LVM, I think manual would have worked if I set it up correctly, but none of the automatic ways would function.

**Comment by adi1090x** [comment]
#190 

It works just fine.
