### ISSUE TITLE
Display issues after wake-up

### ISSUE THREAD

**Issue by CodingArctic** [archcraft-os/archcraft#105]
Hi!

I'm having weird display issues whenever my 2 displays wake up from the system turning them off, or coming out of a suspend. the displays go "on top of each other" (according to display settings, screenshot attatched). This essentially makes them just duplicated instead of an extension like i want it. this is really annoying cause i have to fix all the settings back each time, so if there's a fix i'd appreciate it.

![image](https://user-images.githubusercontent.com/82346273/119943190-b1760700-bf60-11eb-8e1f-9c507ef41387.png)

**Comment by CodingArctic** [comment]
still looking for a solution, only other article i've found is [this one](https://forum.xfce.org/viewtopic.php?id=10951), which has solutions but the most recent one didn't work for me.

**Comment by adi1090x** [comment]
I can't do testing for this issue as i don't have external monitor. 
Keeping it open, someone else might be able to solve the issue.
