### ISSUE TITLE
Support for 30 series cards

### ISSUE THREAD

**Issue by 1fate4all** [archcraft-os/archcraft#106]
Hello! just wanted to ask if 30 series cards are supported with new iso or not? when I try to boot into live environment from a USB it just leads to a black screen and hangs without progressing. If its not the video card then I am not sure as to why I would be getting a black screen when booting into live environment, it doesn't happen to other distros I have used.

my video card is a rtx 3080 with a r9 3950x cpu

**Comment by humaintenance** [comment]
Currently writing this comment from inside the latest Archcraft live ISO (archcraft-2021.05.26-x86_64.iso) using RTX 3090 and R9 5950x. Not having any issues personally.

**Comment by 1fate4all** [comment]
Huh, I guess I can check out ventoy soon then. I made my boot usb with belena

**Comment by CodingArctic** [comment]
i'm running archcraft with an i7 9700k and a 3060ti. no issues besides the one i posted about (#105) but i'm able to boot with no issues.

**Comment by 1fate4all** [comment]
Okay! thanks for verifying that for me guys, I'll check out a few other programs to make a boot media and see if that turns out better. I appreciate the help!
