### ISSUE TITLE
Would it be possible to publish gpg keys on main web site or even other medium (twitter).

### ISSUE THREAD

**Issue by fama** [archcraft-os/archcraft#107]
Would it be possible to publish also GPG signatures for authenticity?  There is no way to verify the signature.  What if sourceforge gets hacked?  It would also allow for distribution via tor and other channels.
Similar to https://manjaro.org/downloads/official/xfce/

_Originally posted by @fama in https://github.com/archcraft-os/archcraft/issues/99#issuecomment-850651165_

**Comment by adi1090x** [comment]
I'll do it.

**Comment by adi1090x** [comment]
And it's been done, long ago.
