### ISSUE TITLE
Can't increase brightness with media key ( F3 )

### ISSUE THREAD

**Issue by AsathalMannan** [archcraft-os/archcraft#108]
In all the distro easily detect media keys and working properly without any manual setup, only archcraft not seems to working automatically.

**BrightnessDown** - _WORKING_ - Key F2
**BrightnessUp** - _NOT WORKING_ - Key F3

Now I can't increase the brightness,
please help me to solve this issue.

**Comment by adi1090x** [comment]
You sure the key is fine?
if F2 works, F3 should work too, because these keys execute same scripts.

**Comment by AsathalMannan** [comment]
Keys fine, both keys working in endeavour os gnome edition.

These issues only on BSPWM based distros.
- Both keys not working on Endeavour os BSPWM but working on Gnome edition of the same distro
- Both keys not working on GarudaLinux too on the BSPWM edition.

Now increasing brightness using `brightnessctl` via terminal

**Comment by izedamo** [comment]
I raised a [PR](https://github.com/archcraft-os/archcraft-scripts/pull/1/files) for this as this is happening on my MacBook Pro mid 2012 as well.

**Comment by KungPaoChick** [comment]
This issue is now fixed on my end... Didn't do anything, it's probably some new updates. Thanks!

**Comment by AsathalMannan** [comment]
Yes new update, fix this issue,.. thanks team..!
