### ISSUE TITLE
Polybar tray shows over fullscreen applications

### ISSUE THREAD

**Issue by steamsyyy** [archcraft-os/archcraft#109]
On the Nordic theme:
![Screenshot_2021-05-29-11_227x82](https://user-images.githubusercontent.com/54457902/120090419-084a2080-c0c8-11eb-8946-eed9d11583b2.png)

This happens when YouTube, mpv or CS:GO (borderless windowed) are in fullscreen

This error is also thrown after running the `launch.sh` script:
```
error: tray: Failed to put tray above 0x1c00001 in the stack (XCB_MATCH (8))
```

**Comment by adi1090x** [comment]
It's an issue with openbox, can't fix.
see here : https://github.com/polybar/polybar/issues/425
