### ISSUE TITLE
Theme and pipemenu download.

### ISSUE THREAD

**Issue by apoorv569** [archcraft-os/archcraft#11]
Hey can you provide the included themes and pipemenu scripts as well as other config files in the ISO for download.

**Comment by adi1090x** [comment]
just, clone this repo and look inside **iso/airootfs/etc/skel/.config** for configs & **iso/airootfs/usr/local/bin** for pipemenus & **iso/airootfs/usr/share** for themes, iconpacks and wallpapers.

**Comment by apoorv569** [comment]
> just, clone this repo and look inside **iso/airootfs/etc/skel/.config** for configs & **iso/airootfs/usr/local/bin** for pipemenus & **iso/airootfs/usr/share** for themes, iconpacks and wallpapers.

Thanks!
