### ISSUE TITLE
Possible issue with Calamare installer not installing all packages

### ISSUE THREAD

**Issue by aplawson7707** [archcraft-os/archcraft#110]
Windows 10 host machine
Virtualbox VM installation
Calamare installer
Install date and ISO download date 5/30/2021

ISO download, VM build, and live environment (liveuser session) initial run all working as expected, at least at first glance.

Calamare installer used 4 times from fresh ISO download.

After installer is run and restart prompt is followed, the only user presented is the liveuser. I have tried to login with the information I provided to the installer at least 4 times now and it is not logging in with that information - just looping me back to the login screen with only liveuser displayed.

If I log into the liveuser session there is no terminal emulator installed - Super + T  does nothing, Super + Return does nothing. Attempting to launch Allarcritty from OpenBox menu gives an error "Failed to execute child process "Alacritty" (No such file or directory)" but this might be due to the liveuser session.

I am going to try the other installer and see if that works - will follow up here.

**Comment by athamour1** [comment]
i have a similar setup and also in my installation there is a problem.

I tried to resolve the problem via tty2, remove and reinstall the alacritty package, but it refuses to start with any way i tried.

**Comment by aplawson7707** [comment]
Ok, I've got to admit the problem was partially me - I didn't remove the iso from the virtual hard disk in Virtualbox after installation, so I now have a new user profile. Consider that part user error.

However, now that I've gotten through the install process I have no terminal emulator. I'm getting "input/output error" when I try to launch Alarcritty and I don't really know what to do.

**Comment by athamour1** [comment]
Try to press ctrl+alt+f2 (via the virtual keyboard, you could find it under input in machine settings), then you will be in TTY2 there you could install an other terminal emulator and change it in the default apps.

**Comment by adi1090x** [comment]
Your system's gpu might be the reason alacritty not working for you.
Upstream issue : https://github.com/alacritty/alacritty/issues/128
