### ISSUE TITLE
Terminal Not Opening  

### ISSUE THREAD

**Issue by Reptop** [archcraft-os/archcraft#111]
I've tried opening the terminal through every method available, and it does not open; is there a fix for this?

**Comment by s4msy** [comment]
same here. you can try Ctrl+Alt+F1 to get into another tty and try to fix it from commandline.

**Comment by berbellon** [comment]
The default terminal is Alacritty,
My PC,
```
$alacritty
Created log file at "/tmp/Alacritty-3957.log"
[2021-05-29 19:29:46.774931063] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
There was an error initializing the shaders: Failed compiling shader: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
```

You can install the Tilix terminal and use the Material theme.

**Comment by adi1090x** [comment]
Upstream ISSUE : https://github.com/alacritty/alacritty/issues/128
