### ISSUE TITLE
Suggestion: Wallpapers cannot be applied from Thunar, betterlockscreen must be manually updated.

### ISSUE THREAD

**Issue by ljfoster97** [archcraft-os/archcraft#114]
Currently when browsing images, right clicking and choosing to set as wallpaper does nothing. Instead you have to open nitrogen and also move the desired image to the background folder. Furthermore, betterlockscreen must be manually updated from terminal to change the wallpaper. It would be more user friendly to be able to change both simultaneously from file manager.

**Comment by adi1090x** [comment]
Hmmm... let's see what can be done about that.
