### ISSUE TITLE
Cannot install snap packages

### ISSUE THREAD

**Issue by d3fkon** [archcraft-os/archcraft#115]
```sudo snap install {ANYTHING}```

gives
```
error: system does not fully support snapd: cannot mount squashfs image using "squashfs": mount:
 /tmp/sanity-mountpoint-768112598: mount failed: Operation not permitted.
```

Looks like squashfs is disabled in the distro by default. Is there a way to enable it without having to reinstall the system?

**Comment by adi1090x** [comment]
Make sure the snapd service is enabled and running.

**Comment by Carlosprint** [comment]
Enable snapd 

`sudo systemctl enable --now snapd.socket`

Add classic support if necesary

`sudo ln -s /var/lib/snapd/snap /snap`

restart
