### ISSUE TITLE
Yay breaks after update to pacman 6.0

### ISSUE THREAD

**Issue by vicentius** [archcraft-os/archcraft#116]
After updating Pacman to 6.0, yay no longer works:

```
~ pacman --version

 .--.                  Pacman v6.0.0 - libalpm v13.0.0
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2021 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'
                       This program may be freely redistributed under
                       the terms of the GNU General Public License.

~ yay --version
yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory
```
Suggested fix is to rebuild yay: https://github.com/Jguer/yay/issues/1519

Any additional recommendations?

**Comment by AvinashReddy3108** [comment]
How about, switching to `paru`?

**Comment by vicentius** [comment]
@AvinashReddy3108 , I have evaluated paru recently and I am happy to switch. Still, I tend to favour the tools recommended/included by the distro maintainer. Which is why I opened this issue.

**Comment by pankace** [comment]
you need to re-install yay 
well actually you should remove yay first then update then reinstall but non the less 
the code you would prob need id you wanted to re install and recompile yay 

```
#remove yay 
sudo pacman -R yay
# Install yay from git
pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git
#cd into the yay directory 
cd yay
#compile yay 
makepkg -si

```

**Comment by pankace** [comment]
> you need to re-install yay
> well actually you should remove yay first then update then reinstall but non the less
> the code you would prob need id you wanted to re install and recompile yay
> 
> ```
> #remove yay 
> sudo pacman -R yay
> # Install yay from git
> pacman -S --needed git base-devel
> git clone https://aur.archlinux.org/yay.git
> #cd into the yay directory 
> cd yay
> #compile yay 
> makepkg -si
> ```

at lest this has worked for me i would like to know your solutions

**Comment by adi1090x** [comment]
fixed.
