### ISSUE TITLE
Distro not custom layout friendly

### ISSUE THREAD

**Issue by Zahrun** [archcraft-os/archcraft#118]
Hi,

Thank you for your work.
When I launch the iso, the first issue I have is that I need to enter the password and the system is just assuming that I use a qwerty keyboard (and that I know the password is the same as the username). It is painful with a bépo or dvorak type of keyboard.

Can't the live user be without password ? Or login automatically ? Or set the layout before we actually have to type ?

**Comment by adi1090x** [comment]
I'll have a look at the layout setup on startup. I may enable the auto-login in next release.
