### ISSUE TITLE
Separate repo for future package updates

### ISSUE THREAD

**Issue by Dark-Matter7232** [archcraft-os/archcraft#12]
Can you implement a separate repo in GitHub for future package updates so we don't have to install the system Everytime a new archcraft package update is released, for reference you can go through salient os repo.

**Comment by adi1090x** [comment]
That's the plan actually & hopefully will do it till next release.
I mean, c'mon... nobody gonna install the OS every-time i update the ISO, that's stupid.

**Comment by adi1090x** [comment]
Done.
