### ISSUE TITLE
No internet connection inside docker container

### ISSUE THREAD

**Issue by evseevnn** [archcraft-os/archcraft#120]

**Comment by dadez** [comment]
I have the same problem, can't nslookup www.google.com or even the docker0 network interface inside a container.

**Comment by adi1090x** [comment]
Hmm... I've never tested any docker containers on Archcraft. Well, let's see what can i do about that.

**Comment by Djamy** [comment]
Hi! Thanks for your work on this distro, good job!

I also have this kind of problem with docker so I cannot work on it at the moment and I am not really good with Arch to figure it out alone.
Hope you could help us with this!

**Comment by izedamo** [comment]
Docker containers are working for me with internet and LAN access!

**Comment by Djamy** [comment]
Thanks for your feedback!
Can you do something like this : `docker run ubuntu apt update` with a positive result?

Because I can't

**Comment by izedamo** [comment]
I can `curl google.com` successfully. `ping` command isn't available inside my image otherwise I could try that. Also, my container pulls data from various online sources and they work fine as well.

**Comment by Djamy** [comment]
Are you on a fresh install?
I tried it on 2 different PC and on 2 different networks so I still don't understand.

Have you done any modification to the network configuration?

**Comment by evseevnn** [comment]
You can use flag --network=host for building and run container, in this case internet connection will available.

**Comment by Djamy** [comment]
Thanks but I don't think this is an acceptable solution as we usually don't need to do that on other distro.
In fact, this issue might brings other side-effects and particular settings not need otherwise.

I tried with setting DNS directly in the `/etc/docker/daemon.js` but no effect.

**Comment by evseevnn** [comment]
@Djamy Yes, sure, this is just temporary solution, and this is not good solution for many ppl.

Actually me too trying change dns and many other things, but I got no working result.

Also I see dead valley of custom arch distros... I think if in near future this distro will not get support he can also die.

I hope that will never happen. I like this distro and I think this is good for developers who lazy for configure arch.

I will trace on this distro, but I should move to more stable distro.

**Comment by Djamy** [comment]
I do like this distro too but it is unusable atm for me so I switched back to PopOs.
Like you, I will keep an eye on this one.

**Comment by ab2pentest** [comment]
Well have you tried WARP of CloudFlare ? it may fixes the issue for you !

**Comment by adi1090x** [comment]
So, Fixed!
