### ISSUE TITLE
Suggestion: Documentation repo/webste 

### ISSUE THREAD

**Issue by pankace** [archcraft-os/archcraft#121]
I think that we would all really appreciate it if there was a documentation repo we could contribute solved issues to

**Comment by adi1090x** [comment]
what you suggest?

**Comment by adi1090x** [comment]
what you suggest?

**Comment by pankace** [comment]
like the arch wiki but in os ? idk this is probs something for wayyy later in the dev-cycle

**Comment by adi1090x** [comment]
wiki.archcraft.io
