### ISSUE TITLE
Suggestion: more agressive opinionated version, faster "time to market"

### ISSUE THREAD

**Issue by karatedog** [archcraft-os/archcraft#122]
I'd suggest being more opinionated on the set up of Archcraft so new users can almost press click-click-finish and they'd have a working OS (or create VM appliance from the setups).
Examples:
- file system selection (most newbies don't care about this, doesn't matter if it is Ext4 or BtrFS), let it be Ext4
- partitioning (everything can go to a single disk. Experienced users can spend their 10 minutes to add/repartition their disks or just add and mount new disks)
- LVM (install it, anyone who don't want this and has minimal experience can move the root filesystem out of LVM in minutes)
- etc.
I think it is better to have a working version than a fully customized one.
Archcraft desktop experience is about only opinions as configuring Openbox for the average people looks like a punishment.
Experienced users usually have their system configuration in code, like Ansible, so they will install everything in 2 minutes.

**Comment by adi1090x** [comment]
Yes, And I have considered that.

- Switched back to ext4 as default.
- LVM is already installed.
