### ISSUE TITLE
Increase Monitor Brightness keybind not working.

### ISSUE THREAD

**Issue by KungPaoChick** [archcraft-os/archcraft#123]
I use  Acer Nitro 5 AN515-42 with AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx 2.00 GHz and Radeon RX 560X Series.

I installed Archcraft because I love the minimalist look, and how easy it is to set its look and feel for the user. But there was a few problems that I have encountered. When I do `fn + leftArrowKey` it decreases my brightness as usual. But `fn + rightArrowKey` doesn't work for some reason. I checked the .yml file to try and fix it, but no luck. There was no problem adjusting the brightness in other distributions. Just this one. Please help fix this problem, because this is the best distribution I have used out of all so far. Thank you :)

**Comment by adi1090x** [comment]
#108

**Comment by KungPaoChick** [comment]
This issue is now fixed on my end. Thank you so much.

**Comment by hackingguy** [comment]
hey @KungPaoChick, what is the solution, I have similar issue on same hardware
