### ISSUE TITLE
Linux-zen kernel not working

### ISSUE THREAD

**Issue by ZeusThundr** [archcraft-os/archcraft#124]
when I select Linux-zen from the boot menu it keeps showing error message

> Kernel Panic - Not Syncing: VFS: Unable to Mount Root FS on unknown-block (8,19)

I ran `sudo mkinitcpio -p linux-zen` even thought I had seen that mkinitcpio already ran while it was installing the package and checked my /boot directory to see if the files were actually generated and they were.
any advice on how to fix this thank you in advance

**Comment by adi1090x** [comment]
Works just fine for me, make sure the initrd line exist in grub config, it not, add manually like shown in screenshot (line 126)

![Screenshot_2021-06-09-03-18-35_1919x524](https://user-images.githubusercontent.com/26059688/121332970-fa04cb80-c935-11eb-84ea-e0e7909c00fc.png)

**Comment by ZeusThundr** [comment]
Don't know how you figured that out but yeah it works fine now thanks a lot really appreciate the awesome work you doing.
