### ISSUE TITLE
timeshift is stuck in live mode after installation

### ISSUE THREAD

**Issue by verajosemanuel** [archcraft-os/archcraft#129]
Hi

after installing some apps I wanted to do a snapshot but timeshift seems to be stuck in live mode. Assistant allows to choose between rsync and btrfs but then closes.

![times](https://user-images.githubusercontent.com/15836677/120900044-1998ad00-c633-11eb-9b52-b5e19ec97bd7.png)

**Comment by adi1090x** [comment]
I don't think timeshift works in Live Environment.

**Comment by adi1090x** [comment]
Update the system, fixed it.

**Comment by verajosemanuel** [comment]
No. Not in live mode. I have installed it and then , after using it and install some apps, time shift is stuck LIKE if it was in live mode.
