### ISSUE TITLE
Help changing path of a file.

### ISSUE THREAD

**Issue by apoorv569** [archcraft-os/archcraft#13]
Hey, you have this file `/usr/lib/archlabs/common/al-include.cfg`, Is there a way to move this file to my `~/.local/lib/common/al-include.cfg`. I was trying your `picom` pipemenu, but it needs this file, I tried modifying the file `ob-compositor` and changed this line
```
if ! . "/usr/lib/archlabs/common/al-include.cfg" 2>/dev/null; then
     echo $"Error: Failed to source /usr/lib/archlabs/common/al-include.cfg" >&2 ; exit 1
```
to
```
if ! . "~/.local/lib/common/al-include.cfg" 2>/dev/null; then
     echo $"Error: Failed to source ~/.local/lib/common/al-include.cfg" >&2 ; exit 1
```
but running the script gives error
```
Error: Failed to source ~/.local/lib/common/al-include.cfg
```
What else do I need to change?

**Comment by adi1090x** [comment]
just don't change the path al all, it is exactly where it should be, you change it's location you break a lot of openbox stuff.
