### ISSUE TITLE
unable to change keyboard layout using gui

### ISSUE THREAD

**Issue by verajosemanuel** [archcraft-os/archcraft#130]
I use an english layout keyboard. Tried to set using "keyboard" application in settings, but this does not change the keyboard as you see in the output from 'localectl status'

![locale](https://user-images.githubusercontent.com/15836677/120916156-302d1b80-c6a8-11eb-9fb0-a6a8e2d63d6c.png)

**Comment by berbellon** [comment]
Puede crear o modificar /etc/X11/xorg.conf.d/00-keyboard.conf ...
You can create or modify /etc/X11/xorg.conf.d/00-keyboard.conf ...
https://wiki.archlinux.org/title/X_keyboard_layout#Using_X_configuration_files

**Comment by adi1090x** [comment]
It's working just fine, make sure you assign a key to switch b/w layouts.

![Screenshot_2021-06-08-04-56-52_1131x828](https://user-images.githubusercontent.com/26059688/121177065-95d10180-c87a-11eb-83a0-e60388e14ddc.png)

**Comment by verajosemanuel** [comment]
can't assign a key to switch either. The assigned keys are not responding.

**Comment by adi1090x** [comment]
That's because `xfsettingsd` doesn't run in bspwm session, it's only for openbox session. if you run that daemon in bspwm session, it'll mess up the theming in bspwm. You have to manually edit the files as @berbellon mentioned.

**Comment by adi1090x** [comment]
Please close the issue when resolved.

**Comment by verajosemanuel** [comment]
modifying the files as @berbellon mentioned worked but the issue is how to change it in the middle of a working session . My laptop has ES (spanish) layout but my external keyboard is US layout, so I need to change layout in bspwm not editing files and restarting if possible.

**Comment by verajosemanuel** [comment]
After latest upgrade I noticed the keyboard is detected automatically. Thanks a lot!!!!
