### ISSUE TITLE
bsplock has many typos

### ISSUE THREAD

**Issue by SeanKim** [archcraft-os/archcraft#131]
some options missing `-` character between words.
I don't know where to fix this problem in this repository(or another AUR?).

However, it can be fixed by executing below script.
```bash
sed -i 's/--\(.*\)color/--\1-color/g' ~/.config/bspwm/bin/bsplock
sed -i 's/--\(.*\)text/--\1-text/g' ~/.config/bspwm/bin/bsplock
sed -i 's/--\(.*\)size/--\1-size/g' ~/.config/bspwm/bin/bsplock
```

**Comment by adi1090x** [comment]
Not typo, just updated with new option format.
Anyway, fixed.
