### ISSUE TITLE
System tray is displayed above fullscreen apps, this happens for video's, games, etc.  It is only the system tray, polybar is fine.

### ISSUE THREAD

**Issue by Laar3** [archcraft-os/archcraft#133]
![Screenshot_2021-06-09-58_1366x768](https://user-images.githubusercontent.com/77225642/121291437-cb580800-c8d7-11eb-8506-960e9635a92a.png)

**Comment by adi1090x** [comment]
Polybar issue with openbox, can't be fixed.
