### ISSUE TITLE
bspwm: terminal always opens in first workspace

### ISSUE THREAD

**Issue by NyxCode** [archcraft-os/archcraft#136]
When opening a terminal using SUPER+ENTER, it always opens in the first workspace, even if a different workspace is currently opened.

**Comment by thelazt16** [comment]
there is a line on bspwmrc which explicitly make the alacritty always open on desktop 1, just remove the `desktop='^1'`

**Comment by adi1090x** [comment]
Edit `~/.config/bspwm/bspwmrc` and comment the following line: 
![Screenshot_2021-06-10-06-44-18_639x70](https://user-images.githubusercontent.com/26059688/121531361-f51a4780-ca1b-11eb-9d84-d0992244709e.png)
