### ISSUE TITLE
Add 'option' to preserve user modified config or back it up (rename) before replacing it when updating

### ISSUE THREAD

**Issue by thelazt16** [archcraft-os/archcraft#137]
So I tried the OS for almost 2 week with the bspwm, and I love it. So as always, I modified it to my liking, but after todays update it completely replace all of my modified config, like everything inside `bspwm` and `sxhkd` (i just noticed that for now), it even remove my own made files which is weird like the update remove the entire folder and make new one.
I would love if you guys could add option to preserved user modified config or just make a backup of it (like renaming the old one to `*.backup`) before replacing it, since I need to start all over again from scrath configuring everything.

**Comment by adi1090x** [comment]
Everything is backed up before updating new configs, check your home directory, There should be a `.ac-backup-time` directory containing all of your configs. To restore them, just copy everything form backup directory and paste them inside your home dir.

Also, This won't happen again, update your system. Now it's totally up to user whether they want to update configs or not.

**Comment by thelazt16** [comment]
> Everything is backed up before updating new configs, check your home directory, There should be a `.ac-backup-time` directory containing all of your configs. To restore them, just copy everything form backup directory and paste them inside your home dir.
Owh thanks god, yeah I check and yes indeed there's `.ac-backup-time` folder on `home` directory. I just assumed it didn't make backup cause it doesn't mention anything when updating or it's just me who failed to read it

> Also, This won't happen again, update your system. Now it's totally up to user whether they want to update configs or not.
Great. And thank you.
