### ISSUE TITLE
issue on adding more font into polybar config?

### ISSUE THREAD

**Issue by thyeun** [archcraft-os/archcraft#139]
Two things need to know

1. Where is the correct polybar `config` file?
2. Try adding the extra font into config file
Before
`
font-0 = "Iosevka Nerd Font:size=10;3"
font-1 = "Iosevka Nerd Font:size=12;3" 
`
After
`
font-0 = "Iosevka Nerd Font:size=10;3"
font-1 = "Iosevka Nerd Font:size=12;3"
font-2 = "FontAwesome:size=10;3" 
`
Not working by add it into the `~/.config/bspwm/polybar/config`

And is the polybar theme are using style `default` inside `~/.config/polybar`

**Comment by adi1090x** [comment]
The polybar used in openbox session are located in `~/.config/polybar/<STYLE>` where STYLE is whatever style you're using.
Bpswm's polybar are inside `~/.config/bspwm/polybar`
