### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by gpk2000** [archcraft-os/archcraft#14]
Hi i want to boot up this ISO but i find that you need to wipe your entire hard-disk to install it? Is there any workaround where i can install it in selected partition? Thanks.

**Comment by Heliferepo** [comment]
For `installing the iso in boot live` you need to format a disk of course (generally a usb stick)

If you are talking about `actually installing the OS`, you don't have to wipe the entire disk

You can  easily manually make partitions with `gparted`

> The `Linux Swap` if you don't already have a partition should be : `512M`
> The `/ (root)` should be `at least` : 10G

I think you can even do that in `abif` the program used to install the distro easily

If you have other OS 's and installing grub you might want to check out this to see [Grub alongside OS's ](https://wiki.archlinux.org/index.php/GRUB)

If you don't care about for example ricing your bootloader you can go with systemd which offers a great supports detecting other OS's

> Also there `abif` can let you chose beetween systemd and grub

**Comment by gpk2000** [comment]
Thanks I figured out i really asked a dumb question.
