### ISSUE TITLE
[Query] Upgrade old version to new one

### ISSUE THREAD

**Issue by RafayGhafoor** [archcraft-os/archcraft#143]
I have a freeze issue and had been using old iso. What's the remedy for upgrading to the latest one without losing data.

**Comment by adi1090x** [comment]
The freeze issue mainly caused by the bootable USB not being created correctly.
Wipe the USB and recreate it with etcher.

Or 

Try booting in `copytoram` mode.

For more info, join the [telegram group](https://t.me/joinchat/0hltmC_JuMUzMzBl), a detailed discussion about that already there.

**Comment by RafayGhafoor** [comment]
Is it possible to not lose the installed configurations and softwares when reflashing it?

**Comment by adi1090x** [comment]
You should install the Latest version of the ISO. There are major base updates. Any ISO before `26May, 2021` are not compatible with new base.
