### ISSUE TITLE
Shadow on Plank

### ISSUE THREAD

**Issue by izedamo** [archcraft-os/archcraft#144]
Compton seems to ignore `shadow-exclude` argument for Plank in `compton.conf` file.

Issue Screenshot:
![image](https://user-images.githubusercontent.com/2781046/121872291-ba1d5a00-cd22-11eb-8a2f-62d7afb6e16b.png)

Current shadow-exclude in `~/.config/compton.conf` file:
![image](https://user-images.githubusercontent.com/2781046/121872426-de793680-cd22-11eb-945b-c52903c3cb1b.png)

### Temporary Workaround
Add `no-dock-shadow=true` to the` ~/.config/compton.conf` file. However, this disables shadow for polybar as well.

**Comment by adi1090x** [comment]
Please use an UTF8 system language. For example : `en_US.UTF-8`

**Comment by izedamo** [comment]
This fixed it. Thanks!

**Comment by thejzain** [comment]
> Please use an UTF8 system language. For example : `en_US.UTF-8`

Bro I don't know how to do that can you explaing or direct me how to get that set

**Comment by izedamo** [comment]
@thejzain please check this 
https://wiki.archlinux.org/title/Locale#Setting_the_locale

**Comment by thejzain** [comment]
> @thejzain please check this
> https://wiki.archlinux.org/title/Locale#Setting_the_locale

Thanks for the help it worked
