### ISSUE TITLE
Loading screen freezes booting from usb

### ISSUE THREAD

**Issue by Rundik** [archcraft-os/archcraft#145]
Loading screen freezes booting from usb. I see the logo and a progressbar.

My hardware: ryzen 9 3900X, nvidia 550ti

**Comment by adi1090x** [comment]
This issue mainly caused by the bootable USB not being created correctly.
Wipe the USB and recreate it with etcher.

Or 

Try booting in `copytoram` mode.

For more info, join the telegram group, a detailed discussion about that already there.
