### ISSUE TITLE
[Failed to start Refresh Pacman mirrorlist with Reflector] on fresh install

### ISSUE THREAD

**Issue by Flapperoo** [archcraft-os/archcraft#146]
CPU: Intel i5-4460
Ram: 8gb Dual

**Comment by adi1090x** [comment]
It'll work after you connect to internet.

**Comment by Flapperoo** [comment]
> It'll work after you connect to internet.

PC was connected via LAN, This shows up on boot and never proceeds if it helps any.

**Comment by adi1090x** [comment]
Try booting with `copytoram` mode.

**Comment by PraveenRaoVP** [comment]
Reinstalling picom through tty fixed this issue for me

**Comment by OctoRocket** [comment]
Failed to start Refresh Pacman mirrorlist with Reflector when trying to sign in to liveboot on all modes

**Comment by BTWarchBTW** [comment]
Same problem with me any help??

**Comment by Reyuki-san** [comment]
i also get this problem, how to solve? in my case i use vbox and archcraft as a distro
and when the os is iddle in a few hours, this error appears 😢 

![image](https://user-images.githubusercontent.com/126035476/224613294-80415652-dc68-460a-998b-7137e8f6ed56.png)

**Comment by LouayHanouche** [comment]
@RealYukiSan any luck?

**Comment by RealYukiSan** [comment]
No, I don't remember. it was a long time ago and now I just use default arch linux installation medium and after the installation, I configure the rest of the environment manually.
