### ISSUE TITLE
Cannot receive key to verify signature

### ISSUE THREAD

**Issue by spamegg1** [archcraft-os/archcraft#147]
After clicking "Download" on https://archcraft.io/install.html I follow the instructions:
![inst](https://user-images.githubusercontent.com/4255997/122284661-7b3ffd80-cef6-11eb-8439-6a53c1596279.png)

```bash
gpg --recv-keys 7DC81F73
```
returns `gpg: keyserver receive failed: No data`

**Comment by adi1090x** [comment]
Works here!

![Screenshot_2021-06-19-10-05-45_598x424](https://user-images.githubusercontent.com/26059688/122649224-81c6b300-d14a-11eb-80fe-c3aa0c4c5e5c.png)

**Comment by spamegg1** [comment]
`gpg --keyserver hkp://keys.gnupg.net --recv-keys 7DC81F73` works.
