### ISSUE TITLE
Many issues with dwm

### ISSUE THREAD

**Issue by paarthjuneja** [archcraft-os/archcraft#148]
FIrst of all, thanks for making a `dwm` edition!
However, I'm facing many issues. I've been able to solve a couple of them. However, I'll need help for the others.

1. The title name in `slstatus` shows the word "broken"  for every window.
2. dmenu doesn't work, only rofi does.
3. There's nothing to see the sound/brightness and the shortcut  keys to change them don't work either, so one has to use the command line.
4. `super + return` doesn't open `st`, only `super + shift + return` works which opens `alacritty`
5. (Fixed myself) Battery doesn't show up in the statusbar.
6. Also, how can I change/add more keybindings?

**Comment by berbellon** [comment]
1. Here it works ...
2. #pacman -S archcraf-dmenu
3. Simple, 
Add, /usr/bin/start_dwm
```
...
## Add your autostart programs here --------------
numlockx on &
unclutter &
sxhkd &
...
```

And, edit ~/.config/sxhkd/sxhkdrc (Do not overwrite sxhkdrc_bspwm)

```
# Volume control
XF86Audio{RaiseVolume,LowerVolume}
    volume{-up,-down}

XF86AudioMute
    amixer set Master toggle

# Music control
XF86Audio{Next,Prev,Play,Stop}
    mpc {next,prev,toggle,stop}

# Brighness control
XF86MonBrightness{Up,Down}
        backlight{-up,-down}

```
Or wait for a new archcraft-dwm update, ( https://gist.github.com/palopezv/efd34059af6126ad970940bcc6a90f2e )
4. #pacman -S archcraft-st
5. **I want to remove it, how did you do it?**
6. No idea, :-)

**Comment by berbellon** [comment]
@adi1090x, Is there any way to remove the battery status?

**Comment by adi1090x** [comment]
Everything is [here](https://github.com/archcraft-os/archcraft-dwm)
Modify -> Re-Compile -> Re-Install
