### ISSUE TITLE
Installing 'all-the-icons' messes up preinstalled icon glyphs

### ISSUE THREAD

**Issue by paarthjuneja** [archcraft-os/archcraft#152]
installed DOOM Emacs which includes 'all-the-icons' fonts. After installing it, the icon glyphs provided by default got messed up. Now, some other meaningless glyphs show up. How do I revert them without removing DOOM Emacs? Screenshots:
![Screenshot_2021-06-20-01_450x125](https://user-images.githubusercontent.com/77548507/122670615-93f33080-d1e0-11eb-9970-d43d365bc051.png)

![Screenshot_2021-06-20-01_589x446](https://user-images.githubusercontent.com/77548507/122670580-71611780-d1e0-11eb-962e-73b5356905d7.png)

**Comment by adi1090x** [comment]
Archcraft already use nerd fonts to provide various kind of glyphs. Instaling another nerd font probably mess up current fonts, remove whatever font you installed and rebuild font cache.
If you want to use another font, use the default version of it instead of nerd version.
