### ISSUE TITLE
Need a better way to deliver updated/new styles

### ISSUE THREAD

**Issue by izedamo** [archcraft-os/archcraft#153]
Currently whenever there is an update to archcraft built in styles the end user needs to choose whether to keep their own styles and create a backup of the new styles or install the new styles and keep a backup of their own styles. This process is less than ideal since in both the cases one has to do a manual merge (copy/paste/replace) of the backup with the actual config directory which is at odds with a rolling-release update process.

We should look at a better way of delivering new/updated styles without manual intervention.

**Comment by coral-hungus** [comment]
Agree with this. A good first step may be to list the changes in the new configs so the user can decide whether or not to upgrade.

**Comment by izedamo** [comment]
That's a good suggestion. I'm not sure how much flexible pacman is to allow such a visual comparison/diff. I wonder how how other software updates work when a user has changed some settings. Just a thought that may be the styles shouldn't be installed in a user's config directory since they're not user specific. And existing hotkey bindings and Compton configs can be left untouched. Newer ones can be delivered as an example config in some location shared among all users.

**Comment by adi1090x** [comment]
There's no other better way, Either i can overwrite you configs, or i can give you the choice to keep yours.
I don't think any other distribution deals with user configs.

**Comment by izedamo** [comment]
Disagree, but okay 🙆‍♂️
