### ISSUE TITLE
GPG can't be verified

### ISSUE THREAD

**Issue by cycomanic** [archcraft-os/archcraft#154]
This was reported in #147 but I'm encountering the same issue.  
keys.gnupg.net is down so I'm trying to verify with ubuntu's keyserver (which typically gets recommended) and cannot find the key:

```
$gpg --keyserver hkps://keyserver.ubuntu.com --search-keys 7DC81F73
gpg: data source: https://162.213.33.9:443
gpg: key "7DC81F73" not found on keyserver
gpg: keyserver search failed: Not found
```

**Comment by adi1090x** [comment]
Try Again : `gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 7DC81F73`
