### ISSUE TITLE
Question: Is there any way to remove the space between the top bar and the maximized windows?

### ISSUE THREAD

**Issue by FernandoNos** [archcraft-os/archcraft#156]
I've been trying to remove the space between maximized windows and the top bar, but with no success. 

Link to image: https://drive.google.com/file/d/1SeHPXA7yHunQ41_NBN93KSeCi_Ndb9z5/view?usp=sharing

The openbox configuration states that the top margin of the windows is 0, so I can only assume it's configured in the top bar configuration.

**Comment by arnolddinkla** [comment]
polybar config.ini margin-top

**Comment by Sudheeshspai** [comment]
my taskbar missing
