### ISSUE TITLE
How can we help in the translation of the OS?

### ISSUE THREAD

**Issue by Carlosprint** [archcraft-os/archcraft#157]
I want to help translate the menus and other stuff to es-ES, how can i help?

**Comment by raitonoberu** [comment]
+1. I love Archcraft so much and could translate it to ru-RU.

**Comment by adi1090x** [comment]
I'll think about it, and let you guys know.

**Comment by Seidenreiher** [comment]
I could translate stuff to de-DE (also the website or the wiki).

**Comment by adi1090x** [comment]
@Carlosprint @raitonoberu @LeaFy-ui @Seidenreiher 

You're welcome to translate the wiki, Follow the instructions [here](https://wiki.archcraft.io/docs/contrib/contrib-translate)
