### ISSUE TITLE
Question: how do I disable the tiling mode (openbox)?

### ISSUE THREAD

**Issue by raitonoberu** [archcraft-os/archcraft#158]
Sorry for the stupid question. I pressed Ctrl+Shift+T, and my windows started to break into tiles, as in the screenshot:
<details>

![image](https://user-images.githubusercontent.com/64320078/123399685-1c9e1200-d5cf-11eb-9d9b-1f013d94d924.png)
</details>
And it's a great mode, but how do I get back? I searched in `rc.xml` and on the "Features" page of the site, but I didn't find anything about this keybind.

Thanks in advance.

**Comment by arnolddinkla** [comment]
This is zentile. To untile press Control-Shift-u

**Comment by raitonoberu** [comment]
Thank you. It would be great to add this somewhere in the docs.

**Comment by arnolddinkla** [comment]
True. 
/zentile/config.toml for other kbs
