### ISSUE TITLE
Not an issue, just want to know the list of core system changes made in archcraft as compared to the vanilla arch?

### ISSUE THREAD

**Issue by khang33k** [archcraft-os/archcraft#162]
So apart from theming and customization of window managers, what are the list of changes made to the core vanilla arch in archcraft?
So that we can know how much close we are to vanilla arch, haha. 
Anyway, good job on the distro!!

**Comment by izedamo** [comment]
Archcraft custom packages mentioned [here](https://archcraft.io/features.html) however, I am not sure if the list is up-to-date. You can also do `pacman -Q | grep archcraft` to list packages that have archcraft in their name. The source for these pkgs is available on github.

**Comment by adi1090x** [comment]
Archcraft is just Arch with GUI, so you get the idea now.
