### ISSUE TITLE
Remove about developer

### ISSUE THREAD

**Issue by md-hr** [archcraft-os/archcraft#164]
Dont like the fact that after i removed the about developer script and folders it gets re added after an update.

If i dont want to have something on my sytstem then i should be able to remove it without you adding it back, the whole purpose of linux and not microsoft.
So please remove this.

**Comment by md-hr** [comment]
Are you gonna remove this or your going to allow malware?

**Comment by Kjvthomas** [comment]
> Are you gonna remove this or your going to allow malware?

It isn't malware, do you even know the definition? It is simply an about the developer page. Have some respect for the awesome work he has done!
