### ISSUE TITLE
Display won't blank

### ISSUE THREAD

**Issue by izedamo** [archcraft-os/archcraft#166]
If the system sleep is disabled for AC power in xfce4-power-manager, then it seems even the display power management is turned off even though it is turned on and has valid configuration values.

In effect, we can't have display turned off unless the system is put to sleep. This results in unnecessary power consumption.

System sleep disabled:
![image](https://user-images.githubusercontent.com/2781046/123761055-14034f80-d8df-11eb-833d-e4cab196476b.png)

Display power management enabled:
![image](https://user-images.githubusercontent.com/2781046/123761245-3eeda380-d8df-11eb-94a8-3d7a30216539.png)

**Comment by haffywaffy** [comment]
Are you using OpenBox/XFCE or another DE/Window Manager?

**Comment by izedamo** [comment]
It's happening with both - bspwm and openbox

**Comment by izedamo** [comment]
This happens only when a vncserver (x11vnc, x0vncserver, etc.) is running. Somehow the DPMS doesn't work if a vncserver is running.
