### ISSUE TITLE
Inconsistent user experience with Installation options in LiveCD

### ISSUE THREAD

**Issue by darth-veitcher** [archcraft-os/archcraft#167]
When loading the LiveCD for the first time and right-clicking to pull up the OpenBox menu you receive the following:

| Menu Path | Available Options|
| -----------|------------------|
|Applications >> Settings | <ul><li>Install Archcraft (Expert)</ul> |
|Applications >> System | <ul><li>Install Archcraft (Expert)<li>Install Archcraft</ul> |

This feels a bit inconsistent and confusing. Especially as the the first place I looked was `Applications >> Settings`.

It might be easier if you direct people to the Calamari installer with a button directly in the `Getting Started` screen that gets displayed?

## Applications >> Settings
![image-0](https://i.imgur.com/TqOWHvT.png)

## Applications >> System
![image-1](https://i.imgur.com/GPIgOLL.png)

**Comment by adi1090x** [comment]
Fixed!
