### ISSUE TITLE
Autologin does not get enabled when selecting it in the Calamares installer

### ISSUE THREAD

**Issue by TheCrether** [archcraft-os/archcraft#169]
Hi, another issue :)

After installing archcraft through the calamares installer today and selecting autologin to be enabled, I found that it was not enabled in `/etc/lxdm/lxdm.conf`.
Sadly, I don't know where the necessary change would need to be made because I would otherwise create a pull request.

**Comment by TheCrether** [comment]
I found this package: https://github.com/archcraft-os/archcraft-pkgs/blob/master/x86_64/calamares-config-1.0-1-any.pkg.tar.zst

Apparently the autologin group does not seem to work because my user has it:
![image](https://user-images.githubusercontent.com/18720938/124400322-d6108c00-dd21-11eb-9a93-0e58bfb8ca93.png)

**Comment by Nerkyator** [comment]
I have same problem. It seems Calamares doesn't update autologin row in `/etc/lxdm/lxdm.conf`
It can be solved manually changing from this
`# autologin=username`
to this
`autologin=YOUR_USERNAME`
in `/etc/lxdm/lxdm.conf`
