### ISSUE TITLE
Unable to update. "failed retrieving file 'archcraft.db' from archcraft.io"

### ISSUE THREAD

**Issue by tjrissi** [archcraft-os/archcraft#173]
When trying to update the system with -Syu i get
"error: failed retrieving file 'archcraft.db' from archcraft.io : Resolving timed out after 10000 milliseconds"
"error: failed to synchronize all databases (download library error)"

**Comment by middieNomad** [comment]
@tjrissi , you maybe on a slow internet connection. Unfortunately, all you can do is retry.

**Comment by adi1090x** [comment]
Slow internet connection.
