### ISSUE TITLE
grub vs archcraft-grub. What is the difference?

### ISSUE THREAD

**Issue by izedamo** [archcraft-os/archcraft#174]
While installing grub-customizer pacman throws a conflict error -- grub and archcraft-grub are in conflict and asks if I want to remove archcraft-grub.
I don't know what archcraft-grub does which is different from grub and so i cannot remove it for fear of making boot process broken.

Is there any documentation surrounding what archcraft-grub does different from normal grub? And how, if required, can we switch from archcraft-grub to grub to avoid conflicts in future?

**Comment by rlad78** [comment]
In experimentation (_cough_ being lazy _cough_), I did what you feared and replaced archcraft-grub with grub. `update-grub` and `os-prober` could not be found afterwards (I have no idea why), so my initial response was to restart the system.

I can confirm this bricks your bootloader. I was only left with the basic grub command line.

**Comment by izedamo** [comment]
oh hey @rlad78 thx for checking it out. i found the source for the `archcraft-grub` package [here](https://github.com/archcraft-os/archcraft-core-pkgs). looks like it applies some patches to the grub source code but i don't the reason for applying them when normal grub should work just fine

**Comment by adi1090x** [comment]
Latest release of Archcraft uses grub. So no such errors anymore.
