### ISSUE TITLE
Something is deeply wrong about the network configuration of Archcraft

### ISSUE THREAD

**Issue by Yugeniki** [archcraft-os/archcraft#177]
I have narrowed down the list of possible causes to this OS, where protonvpn for some reason doesn't work at certain popular websites (youtube, pixiv, etc). 

After investigating the vpn itself, flushing DNS cache, and engaging in other malarkey I had someone test the vpn in another device and it was ok. Working as expected. Before switching to this OS, in the very same day it was working alright. 

So something is wrong here clearly. What non orthodox steps were taken when configuring the DNS/network/whatever that is causing this mess?

**Comment by izedamo** [comment]
Archcraft has iwd and wpa_supplicant both enabled at the same time... Maybe try disabling one of them?

**Comment by Yugeniki** [comment]
> Archcraft has iwd and wpa_supplicant both enabled at the same time... Maybe try disabling one of them?

How do I do this?

**Comment by izedamo** [comment]
Go through arch wiki .. It should have some info regarding this. I simply uninstalled _iwd_ and wifi was fixed for me ... otherwise it used to just disconnect randomly.

**Comment by middieNomad** [comment]
@Yugeniki you can disable iwd. I had the same issue with protonvpn and disabling iwd solved the issue. 
`systemctl stop iwd`
`systemctl disable iwd`
Restart once disabled and you are good to go!

**Comment by adi1090x** [comment]
That should be fixed in the latest release as systemd-network is completely disabled.
