### ISSUE TITLE
If i change the cursor the os will not apply it untill after i logout and back in again.

### ISSUE THREAD

**Issue by Laar3** [archcraft-os/archcraft#178]
This happens when i choose any cursor other than the default. i will need to logout and back in every time that i want it to work for openbox (apps like firefox detect it just fine)

**Comment by middieNomad** [comment]
@Laar3 ,  Have you tried running `openbox --reconfigure`?

**Comment by adi1090x** [comment]
It's fixed in latest release, You still need to re-login  as openbox can't reload the cursor theme instantly without restarting it.
