### ISSUE TITLE
Doing a full system update breaks my installation

### ISSUE THREAD

**Issue by theosenoussaoui** [archcraft-os/archcraft#18]
Hello, this is my first time trying out this ISO and sadly I've ran into a problem (on the 2607 version ISO) :

- if I try to do `pacman -Syu` or a `yay -Syu` command, I got a bunch of errors (screenshot attached).

I've tried to accept everything but then my Arch can't boot properly (black screen). Do you have any idea where it could come from ?

![Screenshot_2020-08-02-08-21-10_1920x1080](https://user-images.githubusercontent.com/14891070/89131641-deeb5300-d4fd-11ea-8c68-28bee1f82d12.png)

**Comment by adi1090x** [comment]
did you modify the pacman mirror list?

**Comment by theosenoussaoui** [comment]
Nope, completely stock. :)

**Comment by theosenoussaoui** [comment]
I tried it on a competely new installation, and it does have a problem when I'm updating with` yay -Syyu` (but `yay -Syu` is fine).

**Comment by meta-boy** [comment]
I am facing the same issue, unable to open tty even so can't check for logs.

**Comment by adi1090x** [comment]
Before upgrading, first - 
- update keyring : `sudo pacman -S archlinux-keyring`
- if you're getting this or similar error -
```
nss: /usr/lib/p11-kit-trust.so exists in filesystem
lib32-nss: /usr/lib32/p11-kit-trust.so exists in filesystem
```
then run the upgrade command like this : `sudo pacman -Syu --overwrite /usr/lib\*/p11-kit-trust.so`
- Finally, run `sudo pacman -Syu` to upgrade your system.

There's a lot going on with archlinux & it's repository. hope they'll fix it ASAP so my distro won't get slammed.

**Comment by fdanangp** [comment]
After full upgrade completed i got blank screen with only mouse pointer

**Comment by adi1090x** [comment]
Please try the latest ISO, reopen the issue if problem still exist.
