### ISSUE TITLE
Powermenu

### ISSUE THREAD

**Issue by Ilyas729** [archcraft-os/archcraft#180]
Can you help me with changing the style of powermenu to default , i casually changed the style of powermenu and i want to roll back the stayl to default?

**Comment by middieNomad** [comment]
Hi @Ilyas729, 
Edit `~/.config/rofi/bin/powermenu`.
Change the following lines to these : 
 {code}
 14 DIR=default
 15 STYLE=powermenu
{code}

**Comment by adi1090x** [comment]
Just apply the default theme.
