### ISSUE TITLE
Feature Request: Matrix Theme / Color Scheme

### ISSUE THREAD

**Issue by uspman** [archcraft-os/archcraft#181]
I love this distro! Super happy with it, and I want to thank the Dev for making such a great looking version of arch!

I was hoping to get a Matrix Styled Theme, and or a terminal style with a Matrix Style, Green on Black.\

Thanks for all you do! I bought you 3 coffees!

**Comment by adi1090x** [comment]
I've added this hackish theme in latest release, You can change the cyan color to green.

![11](https://user-images.githubusercontent.com/26059688/134722826-c7c26da0-0816-40f0-be14-1bb43e00b6ad.png)
n.
