### ISSUE TITLE
Nvidia drivers not working, at all. 

### ISSUE THREAD

**Issue by ThatOneCalculator** [archcraft-os/archcraft#184]
I have an RTX 2070 Super. The Nvidia drivers are extremely buggy, all games run at like 10 fps. I've tried uninstalling and reinstalling the drivers, using the DKMS drivers, reinstalling Archcraft, but nothing works.  I have NOT had this issue on any other distro.

**Comment by adi1090x** [comment]
That should be fixed in Latest release.
