### ISSUE TITLE
Java windows hang and only present grey empty box

### ISSUE THREAD

**Issue by pwhite1989** [archcraft-os/archcraft#187]
This is due to bspwm not playing nice with java applications, such as IntelliJ.

One solution that works for me is to add 
```
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
```
 into ~/.config/bspwm/bspwmrc:
https://wiki.archlinux.org/index.php/Bspwm#Problems_with_Java_applications

**Comment by adi1090x** [comment]
User Specific Config, Can be done later.
Thank you btw.
