### ISSUE TITLE
FIX: Zsh theming and polybar after full update 

### ISSUE THREAD

**Issue by Odyssey2247** [archcraft-os/archcraft#19]
for fix Polybar
reinstall polybar check this [issue](https://github.com/polybar/polybar/issues/885)

for fix Zsh theming (terminal prompt)
un-install the grml-zsh-config package (this [issue](https://stackoverflow.com/questions/43402753/oh-my-zsh-not-applying-themes))

    yay -Rncs grml-zsh-config

**Comment by adi1090x** [comment]
yeah, you need to re-compile polybar everytime `jsoncpp` gets update.
Hope the issue is resolved as you clearly mentioned **fix**, reopen if not.
