### ISSUE TITLE
Can't setup LVM on LUKS

### ISSUE THREAD

**Issue by CrynTox** [archcraft-os/archcraft#190]
When trying to setup LUKS everything is fine, but after that when you try to add lvm ABIF crashes.

**Comment by adi1090x** [comment]
1.
![Screenshot_2021-09-24-09-44-27_1920x1080](https://user-images.githubusercontent.com/26059688/134721321-468b9511-95ee-44fa-bc5f-a1786732b380.png)

2.
![Screenshot_2021-09-24-09-51-25_1920x1080](https://user-images.githubusercontent.com/26059688/134721344-9007e80a-27c2-4138-9c0e-967a60bf8626.png)

3.
![Screenshot_2021-09-24-09-57-07_1920x1080](https://user-images.githubusercontent.com/26059688/134721380-fc9622f3-4edb-43cb-bb6e-08c37d8847d0.png)

4. Installed
![Screenshot_2021-09-24-09-59-29_1920x1080](https://user-images.githubusercontent.com/26059688/134721425-9f58b85e-3b14-42b0-a4b3-2001a7ea5cd1.png)

As you can see, It's working just fine, Try Again (correctly)
