### ISSUE TITLE
Rofi update broke rofi menus in bspwm

### ISSUE THREAD

**Issue by izedamo** [archcraft-os/archcraft#192]
The latest rofi update was released today/yesterday and has broken the UI of all rofi menus in bspwm. Screenshot attached.

![2021-08-31-002307_1280x800_scrot](https://user-images.githubusercontent.com/2781046/131390274-e68132ee-4a7c-422a-9731-7e140db87d84.png)

**Comment by Pyther99** [comment]
The same problem exists in i3

**Comment by theevil** [comment]
same error in bspwm today i update and the icons off all menus have a white background

**Comment by g14wx** [comment]
same here!

**Comment by jedi2610** [comment]
same here with dwm. i don't think the wm matters here.

**Comment by jedi2610** [comment]
https://github.com/davatorium/rofi/issues/1397

**Comment by izedamo** [comment]
> [davatorium/rofi#1397](https://github.com/davatorium/rofi/issues/1397)

This indeed is the issue. The author was good enough to provide the fix as well [here](https://github.com/davatorium/rofi/issues/1397#issuecomment-908683906) and I can confirm it works :D

**Comment by izedamo** [comment]
@adi1090x  pls, when you release an update do consider adding the above fix to the rofi themes :)

**Comment by anilbeesetti** [comment]
use this script to fix all themes in archcraft
script_link:  https://github.com/anilbeesetti/archcraft_rofi_fix

**Comment by anilbeesetti** [comment]
I've Updated the script,  Now it will fix all rofi menus in openbox and bspwm.
checkout the script:  https://github.com/anilbeesetti/archcraft_rofi_fix

**Comment by frostycoding** [comment]
@anilbeesetti thank you for the script, it worked very well :+1:

**Comment by joaosds** [comment]
thanks a lot @anilbeesetti worked like a charm.

**Comment by Seidenreiher** [comment]
Also worked on Openbox. Thank you @anilbeesetti!

**Comment by adi1090x** [comment]
Fixed everything in the new release. Use that.
