### ISSUE TITLE
Keyboard layout not saved on reboot

### ISSUE THREAD

**Issue by Nerkyator** [archcraft-os/archcraft#193]
I have an ArchCraft fresh install. 
On login screen I set my keyboard to `it` without problems. If I logout I can see that it is still selected as default choice in lxdm screen, but on every reboot default selection is always `us`

**Comment by adi1090x** [comment]
Check [this](https://wiki.archlinux.org/title/Linux_console/Keyboard_configuration#Persistent_configuration)

**Comment by Nerkyator** [comment]
It works, thanks!
(closing)
