### ISSUE TITLE
Won't boot after install

### ISSUE THREAD

**Issue by arthurhawron** [archcraft-os/archcraft#194]
I just installed archcraft, and it gets stuck when booting up. It takes about 20 minutes for the bar to reach the end, but nothing happens afterwards. I have tried reinstalling it multiple times and the same thing happens every time.

**Comment by izedamo** [comment]
you could press Escape when the bar is loading and get a look at the boot msgs ... maybe there is a kernel panic happening in which case there would most likely be some sort of indication on the console

**Comment by gelovic** [comment]
Same problem here, need help.

**Comment by adi1090x** [comment]
Use the latest ISO, If your system has NVIDIA... try booting with nvidia menu entry.

**Comment by arthurhawron** [comment]
I figured it out. It wasn't the new iso, I had raid enabled in my bios settings. The same issue also happened with other arch based distros
