### ISSUE TITLE
System tray over fullscreen applications.

### ISSUE THREAD

**Issue by jonkke8** [archcraft-os/archcraft#196]
I'm testing out the new Openbox enviroment. Everything is pretty much perfect, except when I try playing fullscreen games or play YouTube videos, the system tray is still visible over them.

Edit: As a temporary fix, I just disabled the tray for the time being while waiting for a fix.

**Comment by adi1090x** [comment]
It's a polybar issue with openbox in general, not an issue with Archcraft.
