### ISSUE TITLE
Moving to new ISO host / Multiple hosts.

### ISSUE THREAD

**Issue by UpperCenter** [archcraft-os/archcraft#2]
Title is fairly self explanatory.

I live in the UK and have a 350mbps download speed, yet downloads from SourceForge are always incredibly slow. (Not limited to just this ISO) Not sure if I'm doing something wrong somehow.

For a file this size, I would suggest moving to a different download host, or having multiple server locations / regions and or torrent option.

![image](https://user-images.githubusercontent.com/46819924/88112135-23dec380-cba7-11ea-8f1b-381e6a760c4a.png)

**Comment by adi1090x** [comment]
I'll create a mirror for that, dropbox or something.
