### ISSUE TITLE
Can you use bigger bitmap fonts for polybar or include a ttf icon font to better support HiDPI?

### ISSUE THREAD

**Issue by Eoin-McMahon** [archcraft-os/archcraft#20]
4k screens are becoming more and more popular and the polybar config shipped with archcraft are catered more for lower dpi screens. The waffle icon pack in the forest style polybar config for example is only around 10pt which makes it basically unreadable on a 4k display. I've tried to change it myself but keep getting errors with unmatched characters. Can you include bigger bitmap fonts or rather truetype fonts where the size of the icons and text can be scaled?

**Comment by adi1090x** [comment]
the forest style is basically designed for laptop screens with low resolution (I mean i still use a 7 year laptop with 1366x768 screen resolution).
for other screen resolution there are other styles like wave, spark, etc which have better fonts. if you specifically wanna use the forest style, I've also took care of that. you can change the fonts of any application or for everything. all you need to do is, Right click on the desktop to launch openbox menu, go to **Preferences > Change Font > Everywhere** and select the font you like, it'll change fonts everywhere.
In the next release, i'll take care of that, Maybe i'll remove forest style as default.

**Comment by Eoin-McMahon** [comment]
Yes you can change the font size this way, but for bitmaps it wont change anything, And the only icon pack you seem to be using is waffle which is a bitmap.

In the next release could you create a polybar style that uses font awesome instead? that would solve the problem.
