### ISSUE TITLE
Notifications don't support japanese characters even if proper fonts are installed

### ISSUE THREAD

**Issue by demondave** [archcraft-os/archcraft#203]
![image](https://user-images.githubusercontent.com/35665396/136025233-b45835aa-0b67-4de3-8269-8da70d0c3b07.png)

**Comment by samwhelp** [comment]
My implementation, please read [#213](https://github.com/archcraft-os/archcraft/issues/213)

you can set font-match-order like [this](https://github.com/samwhelp/archcraft-adjustment-package/blob/main/core/font/archcraft-modeling-font-match-order/asset/etc/skel/.config/fontconfig/conf.d/50-font-match-order.conf)

fonts.conf can be put some place

| Path | Note | Load From |
| --- | --- | --- |
| /etc/fonts/conf.d/ | system wide |  |
| [/etc/fonts/local.conf](https://github.com/samwhelp/archcraft-adjustment-package/blob/main/core/font/archcraft-modeling-font-match-order/asset/etc/fonts/conf.d/51-font-match-order.conf) | system wide | /etc/fonts/conf.d/51-local.conf |
| ~/.config/fontconfig/conf.d/ | per user | /etc/fonts/conf.d/50-user.conf  |
| [~/.config/fontconfig/fonts.conf](https://github.com/samwhelp/archcraft-adjustment-package/blob/main/core/font/archcraft-modeling-font-match-order/asset/etc/skel/.config/fontconfig/conf.d/50-font-match-order.conf) | per user | /etc/fonts/conf.d/50-user.conf |


## Example Command

to view font match order

``` sh
fc-match monospace -a | less
```

``` sh
fc-match serif -a | less
```

``` sh
fc-match sans -a | less
```
