### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by Firemixtap3** [archcraft-os/archcraft#21]
I followed the guide that is on the site for installing to my machine. Upon booting into the drive I was greeted with the login screen and my username. However, I typed in my password and many differing versions and possible mistypes but every time I attempt to login it goes through as if it is going to login and then kicks me back to the login screen with no meaningful errors or output. I have also attempted to logging into root and receive the same issue. Please advise.

Thank you,

**Comment by fdanangp** [comment]
Yes. Mee too. I still can login with openbox option but there is nothing in desktop. I can run openbox menu by right click but that's only unconfigured openbox menu.

**Comment by adi1090x** [comment]
I'll look into that ASAP.

**Comment by adi1090x** [comment]
If you have created separate home partition, make sure you mount that correctly while installing archcraft.
Try the latest release and reopen issue if you still face this issue.

**Comment by piersolenski** [comment]
I'm having the same issue using VirtualBox with the latest release - should this still be happening?

**Comment by piersolenski** [comment]
Also when using Etcher with a MacBook.

**Comment by LoveSponge** [comment]
Still an issue.

Fresh install of the latest version.

Choosing 'default' at login for window manager just kicks you back to login screen.
Choosing 'openbox' at login for window manager just shows blue background, right clicking shows the openbox menu (unstyled) - attempting to click any application fails 'application-name be found'.
Bspwm just shows background and mouse with absolutely nothing else.

Please help
