### ISSUE TITLE
Moving windows in Openbox produces severe lag.

### ISSUE THREAD

**Issue by ghost** [archcraft-os/archcraft#212]
# Prerequisites
- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Detailed Description
Moving windows with the mouse produces severe lag on Openbox. Windows are 'stuttering' around the screen when you drag them. It is noticeable when nothing but a browser is running, but far worse the more load you put on. 

## Context
- Moving floating windows in bspwm does not produce the same lag. 
- I've tried messing with nvidia-drm.modeset=1
- I've tried enabling glx backend in picom.conf

* ISO Version:  archcraft-2021.10.05-x86_64.iso
* System Specs: Ryzen 5 5600X; Nvidia 1080 with 470.74 driver, 16gb of ram.

**Comment by linuxno0b** [comment]
Same problem here, have you found a solution ?

**Comment by DeinMathelehrer** [comment]
I also got that problem
I asked on the discord already but I didn't got an answer 
So yeah imma post my neofetch output maybe that info helps a bit at solving the problem
![Screenshot_2021-11-26-03-54-40_3000x1920](https://user-images.githubusercontent.com/58335765/143598966-eb544cdc-9854-4884-9e1c-3d0679a373e1.png)

**Comment by adi1090x** [comment]
That's probably because of incompatible GPU drivers.
