### ISSUE TITLE
Does this distro support input methods framework  such as fcitx/ibus?

### ISSUE THREAD

**Issue by hxse** [archcraft-os/archcraft#213]
This is useful for non-English speaking users.

**Comment by samwhelp** [comment]
I use [fcitx-chewing](https://archlinux.org/packages/community/x86_64/fcitx-chewing/) for my input method,

and use [noto-fonts-cjk](https://archlinux.org/packages/extra/any/noto-fonts-cjk/) for view cjk characters.


## Arch Package

| Package | Note | 
| --- | --- |
| [fcitx](https://archlinux.org/packages/community/x86_64/fcitx/) | for fcitx |
| [fcitx-chewing](https://archlinux.org/packages/community/x86_64/fcitx-chewing/) | for my input method |
| [fcitx-configtool](https://archlinux.org/packages/community/x86_64/fcitx-configtool/) | for fcitx |
| [fcitx-qt5](https://archlinux.org/packages/community/x86_64/fcitx-qt5/) | for fcitx |

| Package | Note | 
| --- | --- |
| [noto-fonts-cjk](https://archlinux.org/packages/extra/any/noto-fonts-cjk/) | for view cjk characters |


## Adjustment Package

My Settings

| Package(PKGBUILD) | Note |
| --- | --- |
| [archcraft-modeling-fcitx-chewing](https://github.com/samwhelp/archcraft-adjustment-package/tree/main/core/im/archcraft-modeling-fcitx-chewing) | settings for fcitx and fcitx-chewing |
| [archcraft-modeling-font-match-order](https://github.com/samwhelp/archcraft-adjustment-package/tree/main/core/font/archcraft-modeling-font-match-order) | settings for font-match-order |


## Example iso-profile

My adjustment iso-profile

It could viewing cjk characters and using fcitx-chewing for im.

| iso-profile | packages.x86_64 |
| --- | --- |
| [adjustment-start-from-21.10](https://github.com/samwhelp/archcraft-iso-profile-openbox/tree/main/iso-profile/adjustment-start-from-21.10) | [packages.x86_64](https://github.com/samwhelp/archcraft-iso-profile-openbox/blob/main/iso-profile/adjustment-start-from-21.10/profile/packages.x86_64#L403) |
| [adjustment-start-from-21.09](https://github.com/samwhelp/archcraft-iso-profile-openbox/tree/main/iso-profile/adjustment-start-from-21.09) | [packages.x86_64](https://github.com/samwhelp/archcraft-iso-profile-openbox/blob/main/iso-profile/adjustment-start-from-21.09/profile/packages.x86_64#L407) |
| [adjustment-openbox-with-tint](https://github.com/samwhelp/archcraft-adjustment-iso-profile/tree/main/iso-profile/openbox/adjustment-openbox-with-tint) | [packages.x86_64](https://github.com/samwhelp/archcraft-adjustment-iso-profile/blob/main/iso-profile/openbox/adjustment-openbox-with-tint/profile/packages.x86_64#L412) |


## Link

Just for reference implementation.

* [archcraft-adjustment-documentation](https://github.com/samwhelp/archcraft-adjustment-documentation)

**Comment by hxse** [comment]
@samwhelp 
I try is . 'chewing' can be installed normally but 'rime' can't be used. I don't know why

**Comment by samwhelp** [comment]
In my environment, chewing and rime is working. [See Also](https://www.ubuntu-tw.org/modules/newbb/viewtopic.php?post_id=363314#forumpost363314)
