### ISSUE TITLE
Unable to login after changing shell

### ISSUE THREAD

**Issue by OckhamOdyssey** [archcraft-os/archcraft#214]
# Detailed Description

After a fresh install and update the system I installed fish. The ```/etc/shells``` file have ```/usr/bin/fish```and ```/bin/fish```. Then I changed my default shell using ```chsh -x /usr/bin/fish``` and when I logout I'm unable to login again, I always return to SDDM.

Doesn't matter with "fish" I use, I always have the same result. If I start another TTY and change the shell again to zsh I can login again.

# Expected Behavior

Login as usual

# Current Behavior

Black screen and return to SDDM

# Failure Information (for bugs)

Doesn't find anything relevant in the journal.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install fish with ```sudo pacman -S fish```
2. Change your shell with ```chsh -s /usr/bin/fish``` or ```chsh -s /bin/fish```
3. Reboot and try to login again

## Context

* ISO Version: archcraft-2021.10.05-x86_64
* Graphics Card: Intel HD Graphics 620
* fish version 3.3.1

## Failure Logs

Don't find anything relevant on the logs

**Comment by DisheartenedEthereal** [comment]
You should never change your login shell to fish!

According to gentoowiki, it's best to design an shell init file in bash that changes the shell to fish after logging in.

Read : https://wiki.gentoo.org/wiki/Shell#Changing_a_user.27s_shell

**Comment by frostycoding** [comment]
try using zsh or bash

if fish does not work
