### ISSUE TITLE
HDMI monitor fail => I have a second monitor (SONY)

### ISSUE THREAD

**Issue by irrefl** [archcraft-os/archcraft#215]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
>**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [ ] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository

# Detailed Description

When you connect a second monitor it does not work. Image is blurry and stay frizzed till you disconnect it. 

# Feature request

Need to work perfect as manjaro or another arch distro with a second monitor

# Expected Behavior
Work with extended mode

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version:
* System Specs:
* Graphics Card:
* Etc

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by adi1090x** [comment]
Window managers don't usually deal with multi-monitor automatically. You need to manually configure that using tools like `xrandr` or `arandr`
