### ISSUE TITLE
Archcraft wont boot at all

### ISSUE THREAD

**Issue by babis74** [archcraft-os/archcraft#216]
hello

archcraft wont boot at all progress bar stuck in the beggining, system is intel based and in Bios mode
escape button does not work as well
Machine is perfect for distro hoping,never have issues with other distros

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
>**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository

# Detailed Description

Please describe the issue in detail

# Feature request

If this is just a feature request, please remove the rest of this template.

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version:
* System Specs:
* Graphics Card:
* Etc

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by skjo0c** [comment]
same issue with intel i7 nvidia

**Comment by NewbieLady** [comment]
same issue with i31115g4 laptop(asus vivobook x515ea-bq1005t)

**Comment by adi1090x** [comment]
Have a look at that : https://wiki.archcraft.io/docs/install-archcraft/post-install#black-screen-after-install--liveboot
