### ISSUE TITLE
[Request] Secure Boot option

### ISSUE THREAD

**Issue by FROST8ytes** [archcraft-os/archcraft#217]
# Feature request

An option to setup shim etc. during installation for secure boot would be a great feature to add. Users won't have to sign their bootloader, kernel etc. if everything is already setup during installation. Thank you, keep up the great work!

**Comment by adi1090x** [comment]
Can't.

**Comment by FROST8ytes** [comment]
Yeah, forgot to close this. It's almost impossible to setup secure boot on Arch. Even then, the maintenance would be horrible. Thanks for your great work  @adi1090x !
