### ISSUE TITLE
Live iso doesn't boot up

### ISSUE THREAD

**Issue by pgvalle** [archcraft-os/archcraft#220]
# Detailed Description

I only know the following message appears on screen when booting up the live iso:
[FAILED] Failed to start **Refresh Pa■an mirrorlist with Reflector...**
And i get stuck there with that.

## Context

I don't have wired internet connection. Only wifi.

* ISO Version: archcraft-2021.10.05-x86_64

**Comment by realkinja** [comment]
Having the same issue here. Everything goes how it's supposed to go then it gets stuck at that.

**Comment by realkinja** [comment]
Been 3 months, any fix found yet?

**Comment by adi1090x** [comment]
Have a look at this : https://wiki.archcraft.io/docs/install-archcraft/post-install#black-screen-after-install--liveboot

**Comment by realkinja** [comment]
> Have a look at this : https://wiki.archcraft.io/docs/install-archcraft/post-install#black-screen-after-install--liveboot

Tried this, didn't work, can't even get to the login screen, it just gets stuck at "Failed to start Refresh Pacman mirrorlist with Reflector.." while booting and nothing else happens.

**Comment by Minfred** [comment]
Same here.
Also the same failure happens when booting the liveiso from June and April.
Why is this issue closed? There is no solution.
Is the problem hardware-related?
Or can nobody test or install Archcraft?

Regards
