### ISSUE TITLE
Live USB doesn`t boot

### ISSUE THREAD

**Issue by Kvrdja** [archcraft-os/archcraft#221]
I made the bootable usb like its said on the wiki with Etcher. When i try to boot the live usb, it gets trough the countdown screen and loading splashscreen and then its just black screen with blinking "-". I have wired connection, Nvidia GPU, AMD processor, fairly new cpu and motherboard. Didn`t have this problem with other distros.

**Comment by alkenes** [comment]
Does your system use BIOS or UEFI? Are you using a USB 3 or later for your live disk? I sometimes have problems with those as some of the low level code that starts OSes can get pretty confused by newer standards, but it will depend largely on your combination of hardware and BIOS/UEFI. My suggested troubleshooting steps to narrow it down would be:

1. Reflash the usb with Etcher, sometimes this just goes wrong in ways that aren't obvious
2. Try a different usb, even if you're already on a 2.0 device just try something else if you have anything available
3. Try plain arch on the same USB, if this works then we at least know that something that archcraft modified is the problem

**Comment by Kvrdja** [comment]
I've tried both BIOS and UEFI, few different USB-s both 3.0 and 2.0, I've had plain arch it works no problem and I also tried booting USB to other computer, same problem

**Comment by alkenes** [comment]
Hmm ok sounds like a hardware incompatibility or a bad ISO.

What version of the iso are you running? 2021.09 had an issue with drivers that's fixed in .10
Did you verify the checksum?
Have you tried redownloading the file?

If none of that is able to resolve the issue next step would be disabling the splash screens and hoping for helpful output.

**Comment by Kvrdja** [comment]
I downloaded archcraft-2021.10.05 multiple times from all sources, I didn`t verify checksum tho. I`ll try disabling the splash screen and let you know if it helped.

**Comment by nishinsagume** [comment]
If that didn't help you can try using rufus with dd mode.

**Comment by Kvrdja** [comment]
> If that didn't help you can try using rufus with dd mode.

Tried it, didn`t work
