### ISSUE TITLE
Run On Termux

### ISSUE THREAD

**Issue by 2096779623** [archcraft-os/archcraft#223]
Can I run it in termux?
github.com/termux/termux-app

**Comment by alkenes** [comment]
I would expect this to be difficult. Archcraft and most other linux distros are meant to run on the type of CPU that laptops and desktops have (Intel and AMD style called x86_64 usually although there are a few names that mean the same thing) and android phones have a different style processor (ARM style). This means you would need to setup the build system to build the entire thing from scratch targeting ARM style processors which is possible, but it's probably more work than most people are willing to do.

Your best approach would probably be to start with something like Manjaro ARM which uses arch as a base, like Archcraft, and then building up the packages, themes, and customizations that Archcraft has added. Still not a small task but more achievable.

**Comment by 2096779623** [comment]
> I would expect this to be difficult. Archcraft and most other linux distros are meant to run on the type of CPU that laptops and desktops have (Intel and AMD style called x86_64 usually although there are a few names that mean the same thing) and android phones have a different style processor (ARM style). This means you would need to setup the build system to build the entire thing from scratch targeting ARM style processors which is possible, but it's probably more work than most people are willing to do.
> 
> Your best approach would probably be to start with something like Manjaro ARM which uses arch as a base, like Archcraft, and then building up the packages, themes, and customizations that Archcraft has added. Still not a small task but more achievable.

https://github.com/2moe/tmoe-linux/issues/77
