### ISSUE TITLE
Error on opening the terminal due to Oh My Zsh

### ISSUE THREAD

**Issue by paarthjuneja** [archcraft-os/archcraft#224]
# Detailed Description
Whenever the terminal is opened, an error is shown, and I'm pretty sure it's because of Oh My Zsh.

# Expected Behavior
The terminal window should normally open without any error messages shown.

# Current Behavior
An error mentioned above below.

# Failure Information (for bugs)
`error: object directory /home/adi1090x/Archcraft/packages/archcraft-skeleton/archcraft-omz/oh-my-zsh/objects does not exist; check .git/objects/info/alternates
`
`fatal: reference is not a tree: master
`

## Steps to Reproduce
Simply open the terminal with Zsh as the default shell.

## Context
I'm using the simple theme, and this issue randomly appeared one day when I opened Archcraft. I suspect its probably because of an update, because the error message points to a file which is in @adi1090x's system.

**Comment by nishinsagume** [comment]
I second this, i couldn't update oh-my-zsh because the .git config on .oh-my-zsh folder

**Comment by frostycoding** [comment]
try using other shells instead of zsh, such as fish, bash, etc.

**Comment by Notarin** [comment]
> try using other shells instead of zsh, such as fish, bash, etc.

Is this your proposed solution? Because if so, it is not really a solution. Telling someone to not use a tool because it has a problem rather than telling them how to fix the problem is not the solution they're looking for.
On the other hand, presenting the idea that there are other options is acceptable.

**Comment by aksalsf** [comment]
Reinstalling your zsh can fix that. But, you have to backup the plugins (if you need it) or try to installing it from scratch.

**Comment by adi1090x** [comment]
Current fix : Either you disable the auto-update or you reinstall it from it's github page.
