### ISSUE TITLE
Resting to default settings after rebooting.

### ISSUE THREAD

**Issue by esvuv** [archcraft-os/archcraft#225]
# Bspwm

- [ Y] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [ Y] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [ Y] I checked to make sure that this issue has not already been filed
- [ Y] I'm reporting the issue to the correct repository

# Detailed Description

My monitor settings (Hz on monitor) resets to default settings after rebooting.(xrandr)
Mouse cursor theme resets after reboot to default.
I could say that something is bringing back default settings i guess.

# Current Behavior

After rebooting, xrandr settings and Mouse cursor resets.

![Screenshot_2021-11-08-03-41-28_1920x1080](https://user-images.githubusercontent.com/90131796/140762118-6c46083f-d842-4f96-ae94-bdaf928edbf7.png)

**Comment by adi1090x** [comment]
You need to edit `~/.config/bspwm/bspwmrc` file and put `xrandr` commands there, so they can execute on startup.
To change the cursor theme persistently, edit `~/.config/bspwm/xsettingsd` file.
