### ISSUE TITLE
Windows lagging/tearing while moved

### ISSUE THREAD

**Issue by linuxno0b** [archcraft-os/archcraft#226]
- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

I'm an absolute beginner using linux, so feel free to ask if I forgot something.

# Detailed Description

I installed Arch recently using Calamares, and noticed it was a bit laggy while dragging windows or scrolling (especially in Firefox), but nothing severe. (note : i don't think it's the hardware, Windows was really fluid)
But if i open 3+ windows, or start playing a video, the image is literally stuttering if I move or resize a window.

## Context

* ISO Version: 21.10
* Graphics Card: NVIDIA GeForce RTX 2060
* 2 monitors

 I'm using the default ArchCraft, openbox + Nvidia proprietary driver (v495.44).
 I enabled GLX, and set ForceFullCompositionPipeline=On (found this solution on the arch forum)

## Files

Here's my 20-nvidia.conf file (I added the TearFree =  true):
>Section "Device"
> Identifier     "Device0"
> Driver         "nvidia"
> VendorName     "NVIDIA Corporation"
> Option "TearFree" "true"
>EndSection

Thanks in advance for the help.

**Comment by fuckcuff** [comment]
i had this issue at first when i installed archcraft but it got fixed itself with time, and got even less laggier after rebooting after updating the system

**Comment by adi1090x** [comment]
Could be an upstream issue (with `mesa` or something), Anyway closing it.
