### ISSUE TITLE
stuck at loading screen after installing successfully

### ISSUE THREAD

**Issue by NewbieLady** [archcraft-os/archcraft#227]
My laptop is asus vivobook x515ea-BQ1005T

**Comment by NewbieLady** [comment]
![Uploading 6D262C3A-C92B-43DD-AF53-FA6572B24E15.jpeg…]()

**Comment by NewbieLady** [comment]
![Uploading 04D92DA0-C786-4834-A44B-315145605A64.jpeg…]()

**Comment by shaibaz711** [comment]
Same issue for me on HP laptop x360 - i7 processor.
I can go into the tty shell screen but not sure what else to do there.
![Uploading 20211208_015241.jpg…]()

**Comment by Javets70** [comment]
I cant see the images but as per your description of the issue , it seems very similar to mine

Make sure that
1. The drive you're installing the os from is in FAT32A format
2. Use etcher for writing the iso the flash drive , I used unetbootin and had a pretty similar issue.

The loading bar always got stuck at 100% and nothing happened .

After some googling i found out that it was trying to find a file in `/dev/disk/by-label/arch-craft`.

If etcher doesn't fix the problem then , heres your last hope

https://arcolinuxforum.com/viewtopic.php?t=840
