### ISSUE TITLE
Wi-Fi is connected, but the internet doesn't work at all

### ISSUE THREAD

**Issue by Comet-Z** [archcraft-os/archcraft#229]
# Detailed Description
I can't really say what caused such behavior, I didn't download any network-related software. The only thing I can recall doing before getting this problem, is using `pacman -Syu`. I'm also no power-user at all when it comes to "in-depth Linux stuff" (If that even matters).

# Current Behavior
I connect to Wi-Fi networks, but when I open, let's say, Firefox, the Internet is not being used at all. Same goes for any internet-required stuff. The Internet is gone. Writing this Issue from Windows (dual-boot)

# My Specs
![Screenshot_2021-11-28-11-12-11_1366x768](https://user-images.githubusercontent.com/66474636/143784506-72c80805-8cc6-4032-b0f0-19fdb6ad2d76.png)

**Comment by javierellou** [comment]
How did you solved it?. I have the same error.

**Comment by Elyas2024** [comment]
bro left us in the dark with no answer
