### ISSUE TITLE
ISO Installer Freezes on load

### ISSUE THREAD

**Issue by TylerAldrich814** [archcraft-os/archcraft#23]
The Login screen works just fine. But once i sign in with liveuser as the password. For a few seconds, I can use my mouse. But As soon as the background loads up. The whole system freezes.. I've tried waiting 10 or so minutes(just in case if the files were loading in the background) I even tried installing with the awesome and openbox versions, hoping it was just the original installer that had this bug. But unfortunately they to froze up my system before the background even loaded.
Laptop in use: Lenovo L340 Gaming

Maybe I'll try again in a month or so..

**Comment by adi1090x** [comment]
it's because of Nvidia, maybe...

**Comment by Jacob-Ortiz** [comment]
Yep, same problem the custom iso had before archcraft. Only rebuilding the custom iso with nvidia instead of intel solved this problem. Maybe integrate that as a feature into archcraft?

**Comment by atidyshirt** [comment]
> Yep, same problem the custom iso had before archcraft. Only rebuilding the custom iso with nvidia instead of intel solved this problem. Maybe integrate that as a feature into archcraft?

Can you detail how you achieved this (I havent built a custom ISO before)

**Comment by Heliferepo** [comment]
The steps should be :

1. sudo pacman -Sy bison archiso mikinitcpio mkinitcpio-archiso edk2-shell
2. Clone the repo
(ONLY IF YOU USE NVIDIA ) 3. Go in iso/packages.x86_64 and add your drivers packages as you would download them with arch
4. launch setup.sh
5. sudo su
6. Launch build.sh with verbose (located in the iso folder)
-> ./build.sh -v
You should be done the iso would be builted in the out folder

**Comment by atidyshirt** [comment]
> The steps should be :
> 
> 1. sudo pacman -Sy bison archiso mikinitcpio mkinitcpio-archiso edk2-shell
> 2. Clone the repo
> (ONLY IF YOU USE NVIDIA ) 3. Go in iso/packages.x86_64 and add your drivers packages as you would download them with arch
> 4. launch setup.sh
> 5. sudo su
> 6. Launch build.sh with verbose (located in the iso folder)
> -> ./build.sh -v
> You should be done the iso would be builted in the out folder

So I do need a previous arch install to do this, right I see, thanks a heap, I'll get onto it :).

**Comment by adi1090x** [comment]
Follow the guide on the website and rebuild the iso with nvidia gpu instead of intel.
