### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by bharathyes** [archcraft-os/archcraft#230]
Using the openbox/bspwm iso.

On entering the credentials the screen flickers and comes back to the login page without any errors being displayed.

Was able to login into tty2 using the same user password though.

First occured but was resolved on system reboot but happened again when installed a different WM(DTOS's xmonad). 
Now with a fresh reinstall of Archcraft happened again without much changes to the system.

Unable to determine the cause of this issue so far.

**Comment by tanzious01** [comment]
I have the same issue after doing a syu. I tried disabling the log in manager but that wasnt the issue either. Still dont know the cause.

**Comment by LuisCruzRamon** [comment]
Same issue after a Syu too. 
I just can't resolve that.

**Comment by LuisCruzRamon** [comment]
Please check #237

**Comment by adi1090x** [comment]
probably the compositor, comment it out in startup files.
