### ISSUE TITLE
Error while -Syu command.

### ISSUE THREAD

**Issue by Abhiwa6** [archcraft-os/archcraft#231]
error: exfatprogs: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
:: File /var/cache/pacman/pkg/exfatprogs-1.1.3-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).

**Comment by ralversity** [comment]
Try doing "sudo pacman -S archlinux-keyring" first and then running -Syu

**Comment by Abhiwa6** [comment]
> Try doing "sudo pacman -S archlinux-keyring" first and then running -Syu

It worked for me
