### ISSUE TITLE
OpenBox: No polybar in multi display setup, wallpapers gone

### ISSUE THREAD

**Issue by ymau** [archcraft-os/archcraft#232]
# Prerequisites

- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Detailed Description
Using OpenBox I switched from laptop display only to a multi-display setup (laptop and a monitor). The following problems occurred:
* polybar is gone in the multi-display setup, no matter which display is the main display
* despite setting wallpapers for both displays correctly using `nitrogen`, both wallpapers are gone or not displayed correctly after reboot 

# Expected Behavior
* Polybar is visible at least on the main display
* wallpapers are displayed correctly after a reboot and/or switch from/to single display setup

# Current Behavior
see Detailed Description

# Failure Information (for bugs)
 
## Steps to Reproduce
1. attach another display to the laptop
2. configure display using the display settings from Application -> Settings -> Display
3. make second display the primary one
-> polybar is gone
4. set wallpapers for each display using nitrogen
5. reboot
-> polybar and wallpapers are gone or displayed incorrectly (not filling the display)

**Comment by adi1090x** [comment]
That's how WM works. One need to configure it according to their setup.

For your case :
- Edit the openbox autostart file and use `xrandr` to setup multiple displays.
- Edit the openbox autostart file and use `nitrogen` with `--head` argument to set the wallpaper on both display
- edit polybar config file and add another bar for secondary display and launch both bars.

Basically, Create a script that do all that work and run it after connection to the monitor.
