### ISSUE TITLE
how i can open a terminal command in the default rofi on bspwm

### ISSUE THREAD

**Issue by alavaelian** [archcraft-os/archcraft#236]
when i press the win key there is tree options but when i wan to use a command the terminal doesnt show up

**Comment by frostycoding** [comment]
what do you mean dude?

**Comment by frostycoding** [comment]
i cant understand you

**Comment by Nuralii1i** [comment]
Mod+Enter

**Comment by GuiltyKing27** [comment]
I use windows(Super Key) + Enter(Return). The default shortcut. I'm a Linux noob so I don't know much, but the help application had everything to get me started. :)

**Comment by Nuralii1i** [comment]
You can see details in ~/.config/sxhkd/sxhkdrc,look at it and it will be helpful to you to know what keys are for what function

**Comment by Nuralii1i** [comment]
You can see details in ~/.config/sxhkd/sxhkdrc,look at it and it will be helpful to you to know what keys are for what function

**Comment by AbhayF8** [comment]
@alavaelian If issue is resolved, u may close the issue.
