### ISSUE TITLE
Newest arch update issues

### ISSUE THREAD

**Issue by tanzious01** [archcraft-os/archcraft#237]
The newest arch update wont allow me to log into archcraft. I am not sure if it is due to nvidia drivers or python being updated to 3.10.1. I tried a fresh install then updating via sudo pacman -Syu and the issue still persists. Basically when I log in, I see the desktop environment for a second, then it flashes back to the login screen asking me to log in. 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version: Latest
* System Specs:i7 6700k, gtx 1070 16 gb ram
* Graphics Card: Nvidia Gtx 1070

**Comment by LuisCruzRamon** [comment]
Same problem here, exactly as described by tanzius.

**Comment by LuisCruzRamon** [comment]
I found the solution in reddit.
When on login screen go to tty (ALT + F2 in my case), log in and edit the _bspwmrc_ file (.config/bspwm/bspwmrc).
Comment the bspcomp line and save. 
Return to the login screen (ALT + F1 ) and log in as normally.

**Comment by cloudlmao** [comment]
How do you fix Openbox? I've fixed bspwm

**Comment by LuisCruzRamon** [comment]
@cloudlmao I just solved it commenting the "Start Compositing Manager" line (exec picom &)  in .config/openbox/autostart

Hope this helps you.

**Comment by mbolanoss** [comment]
> I found the solution in reddit. I use bspwm btw. When on login screen go to tty (ALT + F2 in my case), log in and edit the _bspwmrc_ file (.config/bspwm/bspwmrc). Comment the bspcomp line and save. Return to the login screen (ALT + F1 ) and log in as normally.

Hi, how do you go to tty? i tried with ALT + F2 but nothing happened. Also tried other key combinations, still nothing happened

**Comment by KZTN** [comment]
> I found the solution in reddit.
> I use bspwm btw.
> When on login screen go to tty (ALT + F2 in my case), log in and edit the _bspwmrc_ file (.config/bspwm/bspwmrc).
> Comment the bspcomp line and save. 
> Return to the login screen (ALT + F1 ) and log in as normally.

Works perfectly commenting the bscomp execution line. Thanks!
