### ISSUE TITLE
[Question] Enabling/Disabling sudo password feedback.

### ISSUE THREAD

**Issue by ViiEx** [archcraft-os/archcraft#239]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Detailed Description

Not a big deal tho I would like to remove the password feedback when I'm typing my sudo password on my terminal. I did went through the sudoers file with visudo but I found that it had everything in there commented and instead it is including a folder in the end of the file. I thought that was what I was looking for but in my surprise the folder is empty (I believe I checked with `ls -la` as well). 

Is there any way to remove the password feedback? 

Thanks everyone in advance!

# Expected Behavior

When running the command sudo (for example `sudo vim ~/random.txt`) and type the sudo password the asterisks wont reveal.

# Current Behavior

Asterisks take the place of every character I write for password.

**Comment by adi1090x** [comment]
Edit **/etc/sudoers.d/01_pw_feedback** file and remove `pwfeedback`
