### ISSUE TITLE
Last Arch upgrade make me break i3/bspwm startup

### ISSUE THREAD

**Issue by Vandell63** [archcraft-os/archcraft#240]
# Prerequisites
- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository ( oups maybe i miss here sry )

# Detailed Description
After a fresh new archlinux upgrade, i3 or bspwm do not start anymore, but openbox work as expected.
After login and after some times, i am redirected to the login page again

# Failure Information (for bugs)
In journalctl logs we have a Xorg crash issue.

## Steps to Reproduce
1. `sudo pacman -Syuu`
2. `reboot`
3. `login` with i3 or bspwm
4. You get it

## Resolution
After deep dive and remove step by step bspwm bin execution. I fall on to the picom.conf which seems to be the issue.
After comparing the i3 & bspwm similarities, i fall on one point.
Set the `experimental-backends` to `false` from the `picom.conf` file, **seems to fix the issue** for i3 & bspwm.

Maybe i set it by mistake. But at least it can help other if it's happened.
```
experimental-backends = false;
backend = "xrender";
```

## End word
Thx for this project. I was waiting this kind of work into the archlinux eco-system and you did great. Keep it up. Everyone know how much time it takes to get this kind of nice end ui and user experience in linux. I'll donate for sure.

**Comment by joshzcold** [comment]
+ 1 on this getting fixed if its fixable by archcraft.
I was all over the place troubleshooting NVIDIA and xorg when this was my problem starting any session.

**Comment by petsam** [comment]
> backend = "xrender";

This usually has to do with the backend used.
Try `glx` backend, to test for success.

**Comment by adi1090x** [comment]
I guess this is resolved.
