### ISSUE TITLE
polybar: error while loading shared libraries: libjsoncpp.so.24: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by frostycoding** [archcraft-os/archcraft#242]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
>**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Detailed Description
I use bspwm in archcraft linux, I have just updated the system after a long time, after i log out and log in, the top panel is missing, so i ran the command polybar in the terminal to check if everything is correct, and this error appears
"polybar: error while loading shared libraries: libjsoncpp.so.24: cannot open shared object file: No such file or directory"

What do i do?

![Screenshot from 2021-12-25 11-42-18](https://user-images.githubusercontent.com/88981709/147378725-cfe7e434-b1f6-4a3c-bc51-833472089a2a.png)

**Comment by frostycoding** [comment]
What do i do guys

**Comment by frostycoding** [comment]
im so confused

**Comment by frostycoding** [comment]
what do i do guys?

**Comment by frostycoding** [comment]
nevermind, i found the answer, you just had to recompile jsoncpp

**Comment by frostycoding** [comment]
- sudo pacman -R polybar
- git clone https://aur.archlinux.org/polybar.git
- cd polybar
- makepkg -fsi

This is how you need to recompile jsoncpp

**Comment by rendekarf** [comment]
@frostycoding thanks mate, solved it for me.

**Comment by frostycoding** [comment]
@rendekarf your welcome
