### ISSUE TITLE
Polybar module language issue

### ISSUE THREAD

**Issue by cyl3x** [archcraft-os/archcraft#247]
# Detailed Description

I use German as my primary language on my system. The polybar module/used-memory uses "free -m" to detect the current memory usage, but because my language is not English and "free" giving outputs in native languages, the "sed"-command to prass the output is not working.
My simple fix for that is adding "LANG=en_US.utf-8" in front of the command sequence.

## Steps to Reproduce
Change language to something else than english

**Comment by petsam** [comment]
> My simple fix

The _proper_ way (not a workaround) is to set the locale in the polybar config (each theme has its own config, so either edit all themes' files, or the one you use).
For example, [this](https://github.com/archcraft-os/archcraft-openbox/blob/a1a645f22a98556106a8e6a39d67e01d7227e97d/files/polybar/forest/config.ini#L176)

**Comment by cyl3x** [comment]
Maybe you are right, but then the date module would not display the date/time in my native Language. Another approach would be to use the "internal/memory" to get the used memory instead of an custom script

**Comment by petsam** [comment]
@cyl3x I just misunderstood. You are right.

**Comment by adi1090x** [comment]
Noted, Will be fixed in upcoming release.
