### ISSUE TITLE
How to remove the space between the top bar with the window?

### ISSUE THREAD

**Issue by ambarja** [archcraft-os/archcraft#248]
Hello everyone, I have a question, How can I remove the space between topbar and windows ? Currently I have 
the last version (**v21.10**).
Here added some images and the characteristics of my SO.
Thanks.
### Fig. 1: Yellow box space between the topbar and windows
![2022-01-20_11-44](https://user-images.githubusercontent.com/23284899/150384472-66e0b289-d7f3-454c-9aa0-9c8282ad8a26.png)

### Fig. 2: Settings OpenBox
 
![Screenshot_2022-01-20-11-54-50_1366x768](https://user-images.githubusercontent.com/23284899/150385115-930c311e-ba09-456d-9c3a-fee824f2842d.png)

### Fig. 2: Characteristic of my SO
![Screenshot_2022-01-20-11-51-28_1366x768](https://user-images.githubusercontent.com/23284899/150384514-f097fe57-781e-46cf-ae62-e7099764d270.png)

**Comment by Not-Storm** [comment]
In your settings, which can be accessed through the plank application. There should be a option of edge buffers, you might wanna try to set it to 0. It's 10 by default

**Comment by ambarja** [comment]
@Not-Storm thank a lot, but in my archcraft no running the plank application, I used the terminal using sudo and I have the next error, so Is there other alternative for configuration is edge buffers?

### Error in Plank :point_down: 
```
dconf-WARNING **: 11:09:39.364: failed to commit changes to dconf: Error al lanzar («spawn») el comando «dbus-launch --autolaunch=efbd3f40e809448ca3acf88b1d618f6e --binary-syntax --close-stderr»: El proceso hijo terminó con el código 1
```

**Comment by Not-Storm** [comment]
Well nothing I am aware of, although if you can get into the settings manager (the one with xfce look) you can change the buffers there

**Comment by ambarja** [comment]
Recently I have follow the steps, but I don't find this option of buffer u-u
 
![Screenshot_2022-01-24-12-50-27_1366x768](https://user-images.githubusercontent.com/23284899/150837336-5f873a2f-134f-44a8-a9de-706a8684b46b.png)
![Screenshot_2022-01-24-12-52-48_1366x768](https://user-images.githubusercontent.com/23284899/150837358-22279f76-d54b-497a-8757-192ac2a6ff5a.png)

**Comment by Not-Storm** [comment]
Hello, I am sorry it was a mistake on my side. The buffer option is in the openbox configuration settings. It can be accessed through the windows key menu (rofi)

**Comment by ambarja** [comment]
@Not-Storm sorry but I don't find the settings for reduce option of buffer :cry: 
![Screenshot_2022-01-25-11-17-30_1366x768](https://user-images.githubusercontent.com/23284899/151015688-792dd380-04dc-474a-aaff-f01888e88cbf.png)

**Comment by Not-Storm** [comment]
Add me on discord, StormShadow#2807. I am in the archcraft discord server so try tagging me there. I will get back as soon as possible

**Comment by adi1090x** [comment]
Edit **~/.config/openbox/polybar/default/config.ini** file and set `margin-bottom = 0`
