### ISSUE TITLE
Stuck on logo

### ISSUE THREAD

**Issue by nescafe-gold** [archcraft-os/archcraft#25]
When booting from a usb I am stuck on a screen with the archcraft logo and a progress bar moving back and forth.

**Comment by adi1090x** [comment]
Nvidia?

**Comment by nescafe-gold** [comment]
Intel HD Graphics 620

**Comment by akshayrajp** [comment]
Same issue here.

**Comment by Heliferepo** [comment]
Try booting in Legacy guys that solved my problem

**Comment by akshayrajp** [comment]
> Try booting in Legacy guys that solved my problem

Can confirm. Switching from UEFI to legacy worked for me too.

**Comment by adi1090x** [comment]
Great, hope it's solved.

**Comment by akshayrajp** [comment]
But please do find a fix for UEFI boot. @adi1090x 

Booting from legacy is a workaround, not a fix.
