### ISSUE TITLE
i can't reach live session in real hardware but it normally opened in virtual box

### ISSUE THREAD

**Issue by MahmoodMakhloof** [archcraft-os/archcraft#250]
i wanna install archcraft as a primary os but i can't , it stopped at this point.

![FB_IMG_1642954450618.jpg](https://user-images.githubusercontent.com/73743979/150687707-8248f309-92fb-42a5-abe5-d3177475daed.jpg)

**Comment by rajpar29** [comment]
Facing the same issue. I am using Asus Rig Strix. 8 GB Ram, Nvidia 1650, intel i5 10th gen.

**Comment by MahmoodMakhloof** [comment]
problem solved by using internal GPU instead of external nivdea one

**Comment by rajpar29** [comment]
> problem solved by using internal GPU instead of external nivdea one

How did you do it?

**Comment by Eilaluth** [comment]
> > problem solved by using internal GPU instead of external nivdea one
> 
> How did you do it?

I find the more simple way
In the login screen go to tty ( CTRL + ALT + F2 )
Disable picom in
`~/.config/openbox/autostart`
Now you can login but the interface might be buggy to fix this try
`sudo pacman -Rs  picom-ibhagwan-git`
Then
`yay -S picom-git`

Btw im using Nvidia GTX 1050 Ti, the bug only appear in Nvidia users (as i know).

**Comment by adi1090x** [comment]
The issue is either with Nvidia or with compositor.
The Possible Solution for this problem has already been posted on wiki : [Black Screen After Install/Liveboot](https://wiki.archcraft.io/docs/install-archcraft/post-install
