### ISSUE TITLE
Update Chaotic AUR keyring and mirrorlist

### ISSUE THREAD

**Issue by Hamzailer** [archcraft-os/archcraft#251]
# Detailed Description

Chaotic AUR has updated mirrorlist and keyring which is still not available in archcraft repos leading to not being able to install packages from there

# Feature request

Update the following packages in repos `chaotic-keyring` `chaotic-mirrorlist`

**Comment by die88-ac** [comment]
Same issues here, couldn't install Librewolf due to issues with the chaotic-keyring

**Comment by Hamzailer** [comment]
Current fix is:

`sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com`
`
sudo pacman-key --lsign-key FBA220DFC880C036`
`
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'`

**Comment by nfrench83** [comment]
I updated to the git versions of each Chaotic AUR keyring and haven't had
an issue. The only thing is that it yells, when I issue a pacman -Syyu,
that my copy of each is newer than the one in the archcraft repository.

**Comment by adi1090x** [comment]
It's already been updated.
