### ISSUE TITLE
Missing ec_sys kernel module

### ISSUE THREAD

**Issue by nddq** [archcraft-os/archcraft#256]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [X] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Detailed Description

Please describe the issue in detail

- I was trying to install https://github.com/YoyPa/isw, a laptop fan controller.
- modprobe: FATAL: Module ec_sys not found in directory /lib/modules/5.16.4-arch1-1

# Feature request

Apparently this EC_SYS kernel module is missing from this release. Would this count as a feature request?

**Comment by adi1090x** [comment]
User Specific.
