### ISSUE TITLE
add option to connect to wireless wifi with username in password (peap/eap)

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [archcraft-os/archcraft#258]
# Detailed Description

When I try to connect to my school's WiFi network, a username and password is usually required. However, in Archcraft's network menu, it only prompts me for the passphrase (aka. password), rendering it unable to connect to WiFi.  

# Solution
Add a more sophisticated network menu into each riced window manager (similar to that of full-fleged DEs e.g. GNOME and KDE), making it easier to connect to wireless WiFi with alternative methods. 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version: archcraft-2022.02.02-x86_64.iso
* Computer Model: Swift SF314-52 V1.08
* Graphics Card: Intel HD Graphics 620
* CPU: Intel i7-7500U (4) @ 3.500GHz

## Other
I've tried tinkering with `iwd` and `networkctl`, they didn't seem to work.

**Comment by adi1090x** [comment]
Use `nm-connection-editor`
