### ISSUE TITLE
I could build an nvidia version for Archcraft

### ISSUE THREAD

**Issue by Heliferepo** [archcraft-os/archcraft#26]
If you are interested I can build Archcraft with nvidia hardware as lot of people have problems installing the distro

It makes me wondering if I build it with nvidia would it make it work ?

**Comment by adi1090x** [comment]
It's not  a big deal to build the nvidia version of the OS. But i don't want to create a separate ISO for that, I'm looking for a solution to add the support of nvidia in the same, one ISO.

**Comment by forkthat** [comment]
Is it also possible to include AMD drivers by default in the ISO?  Looking at the installed packages, only `xf86-video-intel` is included.

**Comment by adi1090x** [comment]
Done.
