### ISSUE TITLE
Endless login loop

### ISSUE THREAD

**Issue by throtz** [archcraft-os/archcraft#260]
# Detailed Description

As i boot into the login screen on the newest version of archcraft, for the first time i type in the password ("liveuser") and it accepts it, starts loading the desktop, loads a part of the desktop background and then immediately cycles me back to the loading screen, asking for the password again, so i cannot even boot into the liveversion to install archcraft

# Expected Behavior

Cycles you through login into a few ms of wallpaper and then goes back to login asking for the password again

# Current Behavior

Endless login loop

## Steps to Reproduce

1. download the latest archcraft iso and burn it onto a media (USB used in this case)
2. select the media in the boot order
3. boot it up
4. input the password
5. u get a screen flash
6. asks for a password again

## Context

* ISO Version: archcraft-2022.02.02-x86_64
* System Specs: AMD Fx 9590, 8gb RAM
* Graphics Card: NVIDIA GTX 1050

**Comment by ElliotRThorne** [comment]
I get this error, 
I have a nvidia graphics card aswell, NVIDIA RTX 2060.

**Comment by OrrellElectrics** [comment]
Same here 1080ti

**Comment by TheodorrodeohT** [comment]
Same here for 1050ti

**Comment by teinpa** [comment]
this might fix it
https://wiki.archcraft.io/docs/install-archcraft/post-install

**Comment by throtz** [comment]
> 

im leaving it open until its fixed

**Comment by Vandell63** [comment]
@throtz  can you try this ? https://github.com/archcraft-os/archcraft/issues/240

**Comment by throtz** [comment]
@Vandell63 What i did to fix it is the following; as you're booting to live environment, u press ctrl+alt+f2 and basically uninstall picom. Then you proceed to login with username and password install the OS, then do the same thing on the install of the OS, i never really installed it back.

**Comment by adi1090x** [comment]
The Solution for this problem has already been posted on wiki : [Black Screen After Install/Liveboot](https://wiki.archcraft.io/docs/install-archcraft/post-install)
