### ISSUE TITLE
Archcraft in WSL2

### ISSUE THREAD

**Issue by JuanIPlanes** [archcraft-os/archcraft#262]
### Hi.
I have a old hardware, and I can't run archcraft, installed in the disk. BUT,
lately, i'm using WSL(2) with Arch Linux, and run perfectly.
I try to install archcraft in the WSL, and i didn't succeed, because i didn't get the **.tar** from your repos.
please, can you guys make a .tar from your ISO image, or simil? or add Archcraft to Microsoft Store/create installer.
If it's veeeery complex, I had thought of install all packages that have the original Iso, from [This Page](https://ruhend.github.io/archcraft-contrib/features.html).

I read the following articles, hope this is helpful.

### [easyWSL](https://github.com/redcode-labs/easyWSL)
_Create WSL distros based on Docker Images._
### [WSL install another distro](https://gist.github.com/artman41/858450e2c29b239d8692213b684ada25) (artman41)
_Instructions on how to install a custom distro in WSL2 (Windows SubSystem for Linux 2)_
### [WSL Distro Launcher](https://github.com/Microsoft/WSL-DistroLauncher)
_C++ reference implementation for a Windows Subsystem for Linux (WSL) distribution installer/launcher application._

**Comment by devraza** [comment]
I like this idea.

**Comment by adi1090x** [comment]
Can't do it, sorry!
