### ISSUE TITLE
failed to execute command for pipe-menu 

### ISSUE THREAD

**Issue by shinas101** [archcraft-os/archcraft#266]
**hello**

when i try to change change Powermenu by right clicking -> preference -> change powermenu, It shows this error.

> failed to execute command for pipe-menu "/usr/share/archcraft/openbox/pipemenus/ac-change-powermenu" : failed to execute child process "/usr/share/archcraft/openbox/pipemenus/ac-change-powermenu" (no such file in directory )

Same for change polybar theme (ac-change-polybar) , change launcher ( ac-change-launcher).

#### Files inside my "/usr/share/archcraft/openbox/pipemenus/"  are : 

- /usr/share/archcraft/openbox/pipemenus/ac-change-fonts
- /usr/share/archcraft/openbox/pipemenus/ac-change-scheme
- /usr/share/archcraft/openbox/pipemenus/ac-change-style
- /usr/share/archcraft/openbox/pipemenus/ac-compositor
- /usr/share/archcraft/openbox/pipemenus/ac-kb
- /usr/share/archcraft/openbox/pipemenus/ac-kb-pipemenu
- /usr/share/archcraft/openbox/pipemenus/ac-ob-menu
- /usr/share/archcraft/openbox/pipemenus/ac-places
- /usr/share/archcraft/openbox/pipemenus/ac-powermenu
- /usr/share/archcraft/openbox/pipemenus/ac-randr
- /usr/share/archcraft/openbox/pipemenus/ac-recent-files
- /usr/share/archcraft/openbox/pipemenus/ac-record
- /usr/share/archcraft/openbox/pipemenus/ac-shots
- /usr/share/archcraft/openbox/pipemenus/ac-sysinfo

i am 💯 sure i didn't modify or delete any of the file inside this directory.

This was in pacman log .
> [2022-04-06T22:14:25+0530] [ALPM] upgraded archcraft-openbox (1.0-6 -> 1.0-7)

i assume something is wrong with the update hope you fix it , Bspwm works like a charm .

#### OS info 
os : Archcraft x86_64 | 5.17.1-arch1-1
wm : openbox

BTW am in love with archcraft , i use it as a daily driver .
If you need more info please ask.

**Comment by pacholoamit** [comment]
yeah currently experiencing the same thing after I updated through yay

**Comment by GlitchMill** [comment]
Update the System, it will fix it. Even if it doesn't reinstall the new April Release, Owner of this Project has deleted some useless stuff resulting in this

**Comment by shinas101** [comment]
FIX :

Upgrade to April release : archcraft-2022.04.07-x86_64

if you still face this issue (like me) Downgrade archcraft-openbox to something like version 1.0-4 or 1.0-5 (this version doesn't have generate wallpaper-script , ac-canvas)

**Comment by jiangtao69039** [comment]
> FIX :
> 
> Upgrade to April release : archcraft-2022.04.07-x86_64
> 
> if you still face this issue (like me) Downgrade archcraft-openbox to something like version 1.0-4 or 1.0-5 (this version doesn't have generate wallpaper-script , ac-canvas)

how to upgrade?  i face the same issue.

**Comment by shinas101** [comment]
> > FIX :
> > Upgrade to April release : archcraft-2022.04.07-x86_64
> > if you still face this issue (like me) Downgrade archcraft-openbox to something like version 1.0-4 or 1.0-5 (this version doesn't have generate wallpaper-script , ac-canvas)
> 
> how to upgrade? i face the same issue.

upgrade won't fix it, downgrade archcraft-openbox 
                          OR
copy files you're missing from [here](https://github.com/shinas101/miscellaneous/tree/main/archcraft-openbox) and paste it to your **/usr/share/archcraft/openbox/pipemenus**
