### ISSUE TITLE
Can't remove polybar

### ISSUE THREAD

**Issue by haerber** [archcraft-os/archcraft#267]
Hello. I tried to remove polybar because I prefer tint2 put it came back after system update. It seems to be integrate to archcraft-openbox. Please how to remove it without breaking everything ?

**Comment by 5vil** [comment]
Im kinda new to archcraft and WM's in general, have you tried forcefully deleting the polybar folder, removing polybar dependencies in the scripts , and then uninstalling it?

**Comment by aksalsf** [comment]
How about comment or remove it from autostart? So Polybar won't run.
```
geany ~/.config/openbox/autostart
```
Comment or remove this part,
```
bash ~/.config/openbox/polybar/launch.sh
```

**Comment by adi1090x** [comment]
Do as @aksalsf mentioned.
