### ISSUE TITLE
Plymouth screen doesn't show on boot

### ISSUE THREAD

**Issue by 5vil** [archcraft-os/archcraft#268]
I know it's active because it appears when shutting down, but on boot there's just 3 dots on the top left
I used the colorful-loop plymouth theme made by @adi1090x

**Comment by AbhayF8** [comment]
I also had this issue and i fixed this by editing the /etc/mkinitcpio.conf with sudo permissions and adding i915/nouvea/radeon/amdgpu(whichever u use)(check with lspci -k) in modules and then doing sudo mkinitcpio -p linux.

**Comment by 5vil** [comment]
Thanks!
