### ISSUE TITLE
How can I upgrade from February version to latest?

### ISSUE THREAD

**Issue by OxSon** [archcraft-os/archcraft#269]
- [x] This issue concerns upgrading from Feb. to Apr. release ~~I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)~~
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Detailed Description

Hello, thanks for such a wonderful, beautiful, and convenient distro!

I have an installation from the February release ISO and I'd like to upgrade to the latest. From googling, it seems like it is recommended to reinstall completely from the new ISO. Is there any way to avoid this? I have a lot of data I don't want to lose. Or is it possible to reinstall from ISO without losing data from, e.g., ~/Documents or ~/Downloads?

I'd appreciate some help, or a link to a resource that can help me. Thanks again. If this isn't the right repo please just lemme know and I'll close and reopen on the right one. Or if GitHub isn't the right place to ask this at all, then please tell me where is better. Thank you!

**Comment by OxSon** [comment]
Thanks, but I certainly have done that. It doesn't leave me in a good state. For example, it complains that the `archcraft-nvim` package is now missing, but does not remove it, and leaves many many configuration files scattered throughout `/` (and `~` but those are easy enough for me to know how to deal with).

Do you know how I can rectify this? Or do you know which things in `/` are safe to `rm`, or any other commands I need to run to leave my system in a clean state?

**Comment by adi1090x** [comment]
Guess, it's solved!
