### ISSUE TITLE
Tokyonight or Catpuccin theme for bspwm?

### ISSUE THREAD

**Issue by expacc007** [archcraft-os/archcraft#270]
# Feature request

Tokyonight or catpuccin theme for bspwm?

https://github.com/folke/tokyonight.nvim?msclkid=63038ac0c16e11ecb8bfdcdf2fee4bbc
https://github.com/catppuccin/catppuccin?msclkid=5b5c18b7c16e11ecaecfecb5baf24f36

**Comment by GuiltyKing27** [comment]
Both. Add Evergreen for good measure.

**Comment by vtmx** [comment]
OneDark and Kanagawa ;)

https://github.com/rebelot/kanagawa.nvim

**Comment by adi1090x** [comment]
BSPWM now have infinite color-schemes.
Also you can put any of these color-schemes in `~/.config/bspwm/themes/current.bash` file in bash variables format and BSPWM will be themed accordingly.

**Comment by vtmx** [comment]
Thanks!

**Comment by vtmx** [comment]
I create a repository with these themes:
https://github.com/vtmx/archcraft-themes
