### ISSUE TITLE
Polybar stretches out of screen

### ISSUE THREAD

**Issue by expacc007** [archcraft-os/archcraft#271]
I am using 2560x1600 screen on archcraft live mode when I change the resolution to 1920x1200 (because everything is too small on 2k) polybar stretches out of screen in openbox. However polybar scales correctly in bspwm.

**Comment by dhengGhuring** [comment]
Yes i have same issue

**Comment by riquezjp** [comment]
@RameshKumarGogoi do you want to re-open this? This issue still persists, Changing style is a workaround, not a fix.
