### ISSUE TITLE
Dwm Not working

### ISSUE THREAD

**Issue by SarveshSubramanian** [archcraft-os/archcraft#272]
My DWM which i installed by [sudo pacman -Syyu archcraft-dwm] has some problems
i logged out and into dwm i was greeted with a wallpaper but thats it
my keyboard , mouse ,etc were not recongnised
i needed to reinstall archcraft because of a potential sddm problem
pls help

**Comment by GuiltyKing27** [comment]
Did you check the system locale like instructed in the terminal when downloading it from the terminal? See this:- https://github.com/archcraft-os/archcraft-dwm/blob/main/archcraft-dwm/archcraft-dwm.install

**Comment by SarveshSubramanian** [comment]
i dont know how to fix

**Comment by SarveshSubramanian** [comment]
nvm i made it work
idk how
