### ISSUE TITLE
Error update oh-my-zsh

### ISSUE THREAD

**Issue by amdersz5g7** [archcraft-os/archcraft#278]
# Current Behavior

What is the current behavior?

Failed update oh-my-zsh
![image](https://user-images.githubusercontent.com/29188297/172036820-83eb79cd-b873-4e94-a237-f8d8f42b5b5a.png)

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1, open alacritty and it show confirmation to update oh-my-zsh, and i hit enter. and then error like in picture attach

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

![image](https://user-images.githubusercontent.com/29188297/172037073-c9dc8110-25b8-4037-9704-346c901c6e25.png)

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by solkrans** [comment]
I had the same problem. I backed up .oh-my-zsh by renaming it, reinstalled oh-my-zsh according to their homepage. Moved stuff from the backed up folder and, I think I only ended up moving stuff from the custom folder. And then also redid the .zshrc file as I had it before (it gets backed up during oh-my-zsh installation).

**Comment by amdersz5g7** [comment]
for temporary i just disable auto update zsh, like this:

![image](https://user-images.githubusercontent.com/29188297/174813327-bf296f35-8690-40cb-8c6a-27e1d6d81983.png)

**Comment by adi1090x** [comment]
Current fix : Either you disable the auto-update or you reinstall it from it's github page.
