### ISSUE TITLE
Showing some support

### ISSUE THREAD

**Issue by lifeBalance** [archcraft-os/archcraft#28]
Hey Adi, not sure if you've watched the DistroTube video about Archcraft, but in my opinion:
- DT is right about the default **font** and strange choice of **shortcuts**.
- But he's completely wrong about the chosen tone to deliver the message. He didn't even take the time to prepare the video and read about shortcuts and stuff.
I think the distribution is amazing, and it could potentially become a big thing; it has almost everything a Linux super-user could wish for. That being said, please fix **default font**  (type and size), and rethink your choice of **default shortcuts**; the current ones are weird.

Congratulations and thanks for all the work you've put into the distro, (a lot, and it shows) and keep it up.

**Comment by Heliferepo** [comment]
I agree for the shortcuts tho but this is still an amazing work
Since we are here do you plann making a discord or something like that to discuss about the distro and meet the other users?

**Comment by lifeBalance** [comment]
Mattis, my man, they indeed are in Discord. Check the bottom of the page:
[archcraft-os.github.io](https://archcraft-os.github.io/)

**Comment by Heliferepo** [comment]
True thanks buddy

**Comment by adi1090x** [comment]
I've watched that video and yeah... he did not review it right but anyway... that helped me a lot to improve archcraft. I've fixed everything, added amd, nvidia support, new styles and a lot... coming on 1st September. Here's a shot of default look BTW...
![Screenshot_2020-08-30-12-47-19_1366x768](https://user-images.githubusercontent.com/26059688/91667803-cbdf9900-eb24-11ea-8364-280f63f1cabd.png)

**Comment by Heliferepo** [comment]
omg that's gorgeous

**Comment by adi1090x** [comment]
New Version is available now.
