### ISSUE TITLE
archcraft bootable USB does not boot on Z600 workstation

### ISSUE THREAD

**Issue by vksd** [archcraft-os/archcraft#280]
# Detailed Description

Please describe the issue in detail
I have downloaded latest archcraft ISO, and verified checksum.  It works fine on two laptops that I have.

However, it simply hangs at boot on my HP Z600 workstation.  It usually says "FAILED reflector pacman..." But sometimes it does not say that even, and a cursor just keeps blinking.
I have tried it with and without ethernet LAN connection.  Seems to make no difference.
To clarify, it does not boot at all.

I also tried with and without ventoy for the bootable USB. Again, that made no difference.
Pl. help, I really want to install archcraft.  Thanks. 

I tried all the possible boot modes (BIOS, copy to RAM, NVIDIA etc.). Multiple times. Each time same behavior.

**Comment by vksd** [comment]
I am able to log into tty using alt-f2.  However, I dont know what to do after that. I tried to bring up sddm by exec sddm, but it just stays at some intermediate step (sddm does not launch).

**Comment by adi1090x** [comment]
Try latest ISO
