### ISSUE TITLE
QEMU Guest error

### ISSUE THREAD

**Issue by KamilM1205** [archcraft-os/archcraft#281]
My configuration:
- archcraft 2022.06.08
- Intel I5-3570
- Nvidia gt 630 1 gb

Bootable usb created by dd.

# Description

When I booting to live usb, I have error:
![20220618_193621.jpg](https://user-images.githubusercontent.com/38256099/174445759-be132d2a-ca66-4fe5-b3a1-69c361b38546.jpg)

**Comment by Gnkalk** [comment]
My configuration:

- archcraft 2022.06.08
- intel Pentium dual core E5500
- Nvidia Geforce 8400 GS

I have the same problem, I get exactly the same error

**Comment by wopgnepal** [comment]
Nvidia Geforce
intel i5 4460 haswel
msi h81m p33
same problem

**Comment by PaqRul** [comment]
> My configuration:
> 
>     * archcraft 2022.06.08
> 
>     * Intel I5-3570
> 
>     * Nvidia gt 630 1 gb
> 
> 
> Bootable usb created by dd.
> # Description
> 
> When I booting to live usb, I have error: ![20220618_193621.jpg](https://user-images.githubusercontent.com/38256099/174445759-be132d2a-ca66-4fe5-b3a1-69c361b38546.jpg)

I have the same bug, my setup is:
Intel xeon e31220 @3.10Ghz
Nvidia G210 2GB
8 GB RAM
Motherboard Gibabyte Ga-H61m-Ds2 V2.2
Bootable created with Rufus, another with Ventoy with Iso Archcraft 2022.06.08

**Comment by alix1383** [comment]
press tab in boot menu and add "nomodeset" after "quite splash"
 ![Uploading a3{d128ff0} (de6b95f1-fcea-4c41-aac8-70c64d61d61d id=0x7f0a03c6 tag=BaseCommentFragment) …]()

**Comment by adi1090x** [comment]
Resolved?

**Comment by vvxin** [comment]
boot the latest ISO in hyper-v / windows 10.
Same problem.

**Comment by vvxin** [comment]
> Resolved?

"nomodeset" works for me! 
both in virtual machine and a bare-metal laptop

**Comment by DocMAX** [comment]
Doesn't work for me

**Comment by adi1090x** [comment]
Well, If this issue is still exist for some people, It's probably of incompatible GPU.

**Comment by alexlyee** [comment]
What GPUs are compatible exactly?

**Comment by lorenzohoekman** [comment]
I have the same issue for vm and bare-metal. Running:
OS: archcraft-wayland-2022.10.20-x86_64.iso
CPU: Intel i9-9820X (20) @ 4.1GHz
GPU: NVIDIA GeForce RTX 2080 SUPER
Memory: 32GiB DDR4

My graphics card was able to run Garuda sway/wayfire.  so i thought it would be compatible. Any help or advice  on this issue would be greatly appreciated
