### ISSUE TITLE
Baobab  theme problem

### ISSUE THREAD

**Issue by riquezjp** [archcraft-os/archcraft#286]
# Detailed Description
Baobab (Disc Usage Analyzer) has a broken & mismatching theme, especially noticeable in dark modes.
I presume this is due to libadwaita.

## Steps to Reproduce

For example; using openbox with default theme (ark-dark) baobab is themed white & the tool menu has a  large transparent border surrounding it.
If you mouseover the disc usage sections that have coloured % bars, such as home folder/.cache, the background bar & number value becomes invisible. >____% .cache

![Screenshot_2022-07-09-11-39-06_1920x1080](https://user-images.githubusercontent.com/10734045/178103489-fb5b6894-f33e-4cde-a26d-24d957d6963e.png)

![Screenshot_2022-07-09-11-41-02_1920x1080](https://user-images.githubusercontent.com/10734045/178103494-b339ca65-7812-4806-8fa1-e4ce45fc46ce.png)

**Comment by adi1090x** [comment]
Upstream issue from Gnome.

**Comment by andregalastri** [comment]
* Open the file `~/.config/picom.conf`
* Search for the term `shadow-exclude`
* Add the command `"class_g = 'baobab' && window_type = 'menu'",` at the top of the list, like this:
  ```
  shadow-exclude = [
      "class_g = 'baobab' && window_type = 'menu'",
      ...
  ];
  ```
  > **NOTE: don't forget the comma at the end of the command and keep all the other stuff of the list**
* Save the file and it will be fixed.
