### ISSUE TITLE
4k is borked

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [archcraft-os/archcraft#288]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
>**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [X] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

# Detailed Description

4k resolution is borked

# Expected Behavior
Any text whatsoever to be readable, for the lockscreen background to take up the entire screen

# Current Behavior

No text is readable on my laptop screen, lockscreen background only takes up 1/4 of the screen

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Boot ArchCraft on a 4k monitor
2. Observe

**Comment by adi1090x** [comment]
Have you tried this : https://wiki.archlinux.org/title/HiDPI#Xorg
