### ISSUE TITLE
Failed to install packages to new root

### ISSUE THREAD

**Issue by rhtzy** [archcraft-os/archcraft#289]
:: Synchronizing package databases...
 archcraft.db failed to download
error: failed retrieving file 'archcraft.db' from archcraft.io : Failed to connect to archcraft.io port 443 after 9690 ms: Connection timed out
error: failed to synchronize all databases (download library error)
==> ERROR: Failed to install packages to new root

**Comment by adi1090x** [comment]
Sometimes this happens  because of slow internet speed, or maybe github is down at the moment.

You should try again after some time.

**Comment by RaiyanAhmed-RK** [comment]
i am using arch linux, how to add archcraft repo in pacman on other archlinux distro ?
