### ISSUE TITLE
Can't find documentation on Style Scripts

### ISSUE THREAD

**Issue by Snazzyham** [archcraft-os/archcraft#29]
Firstly I'd like to say, this project looks great! I use manjaro, but am considering making the switch to this. 

Quick question though, in the README I saw something about "Style Scripts" to easily swap styles, but I couldn't find a reference to that on https://archcraft-os.github.io/ or in the repo. 

How would I go about using those? what do they modify and where are they stored?

**Comment by adi1090x** [comment]
Here : [Styles](https://github.com/archcraft-os/archcraft/tree/master/iso/airootfs/etc/skel/.config/openbox/styles)
The style scripts can be executed via openbox menu and it changes theme for polybar, rofi, gtk icon and theme, fonts, dunst, etc.
The startup guide will help you with everything, if you're gonna give it a shot, do it after 1st September, new version will be uploaded soon.
![Screenshot_2020-08-31-01-01-59_1366x768](https://user-images.githubusercontent.com/26059688/91667921-cafb3700-eb25-11ea-9acc-6dabcd99284c.png)

**Comment by Snazzyham** [comment]
awesome will definitely check it out. 

Do the style scripts work on bspwm as well?

**Comment by adi1090x** [comment]
Yes.

**Comment by forkthat** [comment]
I was about to ask how to change the themes of the desktop and I'm glad I came across this!

**Comment by DetectiveCatt** [comment]
The link is broken now.. anyone care to post again?
