### ISSUE TITLE
Latest updates removed my `.config/openbox` folder and replaced it with a stock one

### ISSUE THREAD

**Issue by PiotrekPKP** [archcraft-os/archcraft#290]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
>**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository

# Detailed Description

To be clear: I don't expect you to bring back my config ;) I just want to inform you about the problem for future Archcraft users.

I run `sudo pacman -Syu` yesterday and rebooted my machine (as usual). After booting to Openbox I realized that everything was brought back to stock config.
I chcecked `.config/openbox` folder and unfortunately it was entirely replaced with a new one. I can give you list of packages that were upgraded (though I don't know which one caused the problem).

# Expected Behavior

I expected the update **not** to remove my config.

# Current Behavior

Update of at least one of the listed packages removes the config.

## Steps to Reproduce

Run `sudo pacman -Syu` on configurated machine and update those packages from listed versions.

1. `sudo pacman -Syu <package from the list>`
2. Reboot
3. You will see your config removed

## Context

Updated packages:
- `archcraft-backgrounds (1.0-3 -> 1.0-4)`
- `archcraft-bspwm (1.0-8 -> 2.0-0)`
- `archcraft-help (1.0-3 -> 1.0-4)`
- `archcraft-hooks (1.0-4 -> 1.0-6)`
- `archcraft-openbox (1.0-9 -> 2.0-0)` (I assume that's the one causing problems)
- `archcraft-pixmaps (1.0-2 -> 1.0-3)`
- `archcraft-scripts (1.0-8 -> 1.0-9)`
- `archcraft-skeleton (1.0-5 -> 1.0-7)`

* ISO Version: v2021.09
* Graphics Card: NVIDIA GPU 1650MQ

**Comment by adi1090x** [comment]
No, it's not gone, it's backed-up.

Check `~/.config` folder.
