### ISSUE TITLE
Cpu Fan making a lot of noise

### ISSUE THREAD

**Issue by m-anshuman2166** [archcraft-os/archcraft#292]
I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
 I checked the [documentation](https://wiki.archcraft.io) and found no answer
 I checked to make sure that this issue has not already been filed
 I'm reporting the issue to the correct repository

# Detailed Description

At start, runs without any issues. But after 2-3minutes, cpu fan starts making loud noise and overheats pc.

# Expected Behavior

Cpu fan should work normally.

# Current Behavior

Overheating and loud cpu noise.

## Steps to Reproduce

[N.A]

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version: archcraft-2022.07.18-x86_64
* System Specs: 
![image](https://user-images.githubusercontent.com/72782632/182012408-09eeb965-c71b-4447-b6d7-fc2ae3e478b9.png)

* Graphics Card: 
![image](https://user-images.githubusercontent.com/72782632/182012465-c507126a-602c-4cb2-96ca-308dae1cb654.png)

**Comment by Technetium1** [comment]
```
watch -n0.5 -d sensors
```
See what happens more specifically to temp/fan speeds and report back?
Does either one of the following have any obvious errors?

```
journalctl -xe
```

```
sudo dmesg
```
