### ISSUE TITLE
Not booting from USB

### ISSUE THREAD

**Issue by ImpeccablePenguin** [archcraft-os/archcraft#293]
# Detailed Description

When booting from USB, the process hangs around something graphics related. I have verified the SHA256 of the iso and it correctly boots in my VM. 

## Context

* ISO Version: 07.18
* System Specs: 11th Gen intel i7-11800H, 16gb RAM
* Graphics Card: NVIDIA GeForce RTX 3060 Mobile and Intel UHD Graphics

## Failure Logs

see [image](https://drive.google.com/file/d/1Z5o3rF-dh4XgX2IqmbV1ExQmOjvzfq3E/view?usp=sharing) for output

**Comment by adi1090x** [comment]
Incompatible GPU, Probably

**Comment by CIaudi0** [comment]
when you boot from usb, in grub menu click 'e' in order to edit and try to write "nomodeset" after 'quiet splash', so boot with F10
