### ISSUE TITLE
Hide/Unhide Window does not work

### ISSUE THREAD

**Issue by YannickSpoerl** [archcraft-os/archcraft#294]
The combinaton **MOD** + **SHIFT** + **i** is supposed to hide/unhide the focused window. It does not. In fact, the command "_winmask_" can't even be found.

My .config/bspwm/sxhkdrc contains the line:

```bash
# Hide/Unhide Window
super + shift + i
	winmask	
```	a

**Comment by solfrak** [comment]
replace winmask by bspwinmak. Should work like as expected

**Comment by YannickSpoerl** [comment]
Thanks, that was it. How did you know?

**Comment by solfrak** [comment]
Luck i guess. I tried to execute the winmask command but it didn't work. But my terminal suggested bspwinmask instead
