### ISSUE TITLE
BOOTING TIME AROUND 5 MINUTES

### ISSUE THREAD

**Issue by JasterV** [archcraft-os/archcraft#299]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
>**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Detailed Description

Not a lot to say, I just installed the latest version of Archcraft into my system and each time I restart the computer it takes probably around 5 minutes to boot, thats too much!

# Expected Behavior

I expect it to boot in less than 10 seconds

# Current Behavior

Booting takes a lifetime

# Failure Information (for bugs)

I hope this is a bug that can be fixed

## Steps to Reproduce

Just restart the computer

## Context

My system info:

![Screenshot_2022-08-15-18-13-17_1920x1080](https://user-images.githubusercontent.com/49537445/184673140-e04f221d-977e-47fa-be5a-9ed9bb442295.png)

## Failure Logs

I don't have any

**Comment by andregalastri** [comment]
In the Terminal, run `systemd-analyze blame > ~/bootlog.txt`. It will generate a `bootlog.txt` file in your home folder. Open it, copy its content and post here to see which service is hanging the booting time...

**Comment by JasterV** [comment]
@andregalastri  bootlog.txt contents:

```
1min 30.137s systemd-modules-load.service
     58.856s reflector.service
     34.274s pacman-init.service
      5.162s NetworkManager-wait-online.service
       702ms ldconfig.service
       188ms sshdgenkeys.service
       180ms systemd-udev-trigger.service
       166ms systemd-resolved.service
       145ms upower.service
       141ms systemd-rfkill.service
       114ms dev-mapper-luks\x2d0ee4b7f1\x2d6b65\x2d4766\x2dbf88\x2dd80929093275.device
        68ms boot-efi.mount
        65ms plymouth-deactivate.service
        64ms plymouth-quit-wait.service
        64ms plymouth-quit.service
        59ms user@1000.service
        58ms lvm2-monitor.service
        44ms ModemManager.service
        36ms systemd-journald.service
        30ms systemd-tmpfiles-setup.service
        29ms systemd-timesyncd.service
        29ms systemd-logind.service
        28ms systemd-udevd.service
        25ms bluetooth.service
        20ms systemd-vconsole-setup.service
        19ms cups.service
        17ms NetworkManager.service
        16ms systemd-remount-fs.service
        14ms avahi-daemon.service
        13ms plymouth-start.service
        13ms systemd-fsck@dev-disk-by\x2duuid-350B\x2d0823.service
        13ms systemd-journal-catalog-update.service
        11ms plymouth-read-write.service
        11ms polkit.service
        10ms systemd-tmpfiles-setup-dev.service
         9ms systemd-sysusers.service
         9ms modprobe@fuse.service
         8ms dbus.service
         7ms alsa-restore.service
         7ms wpa_supplicant.service
         6ms dev-hugepages.mount
         6ms dev-mqueue.mount
         6ms sys-kernel-debug.mount
         5ms systemd-update-utmp.service
         5ms sys-kernel-tracing.mount
         5ms systemd-sysctl.service
         5ms kmod-static-nodes.service
         5ms systemd-cryptsetup@luks\x2d0ee4b7f1\x2d6b65\x2d4766\x2dbf88\x2dd80929093275.service
         4ms systemd-user-sessions.service
         4ms modprobe@configfs.service
         4ms modprobe@drm.service
         4ms systemd-random-seed.service
         4ms user-runtime-dir@1000.service
         3ms systemd-journal-flush.service
         3ms swap.mount
         3ms sys-kernel-config.mount
         3ms var-cache.mount
         2ms rtkit-daemon.service
         2ms home.mount
         2ms swap-swapfile.swap
         2ms var-log.mount
         2ms systemd-backlight@backlight:intel_backlight.service
         2ms systemd-update-done.service
         1ms tmp.mount
         1ms sys-fs-fuse-connections.mount
```

**Comment by JasterV** [comment]
Also a photo of the screen logs when it hangs

![IMG_20220819_161327.jpg](https://user-images.githubusercontent.com/49537445/185638176-91e8c1c3-87ba-4549-91e8-15b788ff059b.jpg)

**Comment by invalidcode232** [comment]
Getting the same issue, any update for this?

**Comment by zekesarosi** [comment]
Same issue for me

**Comment by JoshuaDRose** [comment]
same

**Comment by zekesarosi** [comment]
This is frustrating. Hope someone has a fix!

**Comment by JoshuaDRose** [comment]
Issues have been resolved.

**Comment by JasterV** [comment]
@JoshuaDRose What was causing the issue?

**Comment by JasterV** [comment]
@JoshuaDRose It stills happening to me, it is really frustrating

**Comment by invalidcode232** [comment]
Also still happening to me

**Comment by tdewaard** [comment]
Having exactly the same problem (very similar output to systemd-analyze blame as well)
I tried lowering the timeout of systemd-modules-load.service but this didn't work
As a workaround I installed the LTS kernel: booting times are now as expected
