### ISSUE TITLE
Polybar icons broke after updating

### ISSUE THREAD

**Issue by sakshatshinde** [archcraft-os/archcraft#3]
Polybar icons have stopped working. I also ran the fix_modules script and it didn't work

**Comment by adi1090x** [comment]
screenshot?

**Comment by n00b2h4ck3r** [comment]
![Screenshot_2020-07-29-01-12-34_2806x900](https://user-images.githubusercontent.com/10554636/88825126-9817f900-d19d-11ea-8c4b-ac555067d644.png)

Same issue... Polybar icons stop working after update.

**Comment by adi1090x** [comment]
Are you using the latest ISO?

**Comment by n00b2h4ck3r** [comment]
yes, latest iso... New installation.. i just did Sudo Pacman -Syuu and reboot... Then icons dissapears.. But if i run polybar with sudo the icons works....

**Comment by sakshatshinde** [comment]
> screenshot?

Sorry I just distro hopped, will let you know if the problem occurs again if I install Archcraft

**Comment by adi1090x** [comment]
@n00b2h4ck3r That's weird... try reinstalling polybar (`yay -S polybar`).
also, make sure you're using this **archcraft-2020.07.26-x86_64.iso** ISO, the previous one had some issues with pacman.

**Comment by n00b2h4ck3r** [comment]
> @n00b2h4ck3r That's weird... try reinstalling polybar (`yay -S polybar`).
> also, make sure you're using this **archcraft-2020.07.26-x86_64.iso** ISO, the previous one had some issues with pacman.

Yes, I did a clean installation so that the problem would be solved, but when updating, the same thing happens again. You have tried installing polybar again and nothing.

**Comment by adi1090x** [comment]
I'm not sure what & how this is happening with you guys... I'm using the same ISO and everything is just fine here.
![Screenshot_2020-07-30-07-56-00_1366x768](https://user-images.githubusercontent.com/26059688/88934860-bd406080-d29e-11ea-901a-8506ba57ba8f.png)

**Comment by adi1090x** [comment]
make sure you recompile polybar (or `yay -S polybar`) after the system upgrade.
the update of `jsoncpp` causes polybar to be recompiled.

**Comment by Apostrov** [comment]
Had the same problem and recompile not helped. I fixed the problem by changing `waffle` font to `siji` in `config.ini`
