### ISSUE TITLE
internet not working

### ISSUE THREAD

**Issue by ghost** [archcraft-os/archcraft#301]
![IMG_20220819_134505_679](https://user-images.githubusercontent.com/61046119/185596987-f35dc78a-1f24-4fd4-ab32-4999874a5d44.jpg)
i have a stable insternet on my other os but in archcraft is not working and only its 7kb/s

**Comment by freunte** [comment]
Is that ethernet? Have you tried reflector to update your mirrors?

**Comment by Solasoul** [comment]
Check for limits on your firewall settings

**Comment by JEAPI-DEV** [comment]
Wait, does archcraft come with an preinstalled firewall?

**Comment by CIaudi0** [comment]
install the correctly driver of your pc. I have Broadcom 4321 so I have installed b43-firmware b43-fwcutter and Broadcom-wl , I have written in terminal : modprobe -r b43 usb bcma , and modprobe wl and after reboot. so I resolve .
