### ISSUE TITLE
Tooltips for status bar icons

### ISSUE THREAD

**Issue by jcperil** [archcraft-os/archcraft#302]
# Feature request

An option to enable or disable tooltips when you hover over screen elements in the status bar. I can see the tooltip appear in the menu bar, for example, if I hover over Firefox browser icon, the name Firefox appears for the user to see.

I can't figure out what some of the icons in the status bar are for. It would be helpful if this tooltip was available for the status bar too, if not by default then at least as an option somewhere in Preferences section.

**Comment by adi1090x** [comment]
Not supported by polybar yet.
