### ISSUE TITLE
Optimus manager is not working

### ISSUE THREAD

**Issue by sid314** [archcraft-os/archcraft#303]
# Prerequisites
- [ x] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [ x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository

# Detailed Description
running optimus-manager gives following errors

ERROR: a GPU setup was initiated but Xorg post-start hook did not run.
Log at /var/log/optimus-manager/switch/switch-20220821T191501.log
If your login manager is GDM, make sure to follow those instructions:
https://github.com/Askannz/optimus-manager#important--gnome-and-gdm-users
If your display manager is neither GDM, SDDM nor LightDM, or if you don't use one, read the wiki:
https://github.com/Askannz/optimus-manager/wiki/FAQ,-common-issues,-troubleshooting
Cannot execute command because of previous errors.

# Expected Behaviour

It should run

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. run `optimus-manager`

**Comment by sid314** [comment]
It should run `/usr/bin/prime-offload` just after starting its display server for the login screen and `/usr/bin/prime-switch` as root after the current user has logged out.

**Comment by sid314** [comment]
I also ainsatalled bbswitch and acpi_call packeges which removed some of the errors in the logs

**Comment by adi1090x** [comment]
Have you tried this: https://wiki.archlinux.org/title/NVIDIA_Optimus

**Comment by sid314** [comment]
it may work sorry i no longer use archcraft
