### ISSUE TITLE
Add way to download archcraft mirrorlist

### ISSUE THREAD

**Issue by gbaudino** [archcraft-os/archcraft#304]
# Detailed Description
I want to be able to install the archcraft mirrorlist on my current archlinux and I can't find a way provided for this.

# Feature request
Add a way to download and install the mirrorlist on the desired archlinux.
For example blackarch provides a path https://blackarch.org/strap.sh that curl -O downloads to, and running this automatically installs the mirrorlist.

**Comment by adi1090x** [comment]
Not interested, i can only deal with Archcraft. If you're willing to transform arch into Archcraft, do it manually.

**Comment by jensgrunzer1** [comment]
I've uploaded mine in this repo  https://github.com/jensgrunzer1/archraft-mirrorlist

**Comment by ghost** [comment]
> I've uploaded mine in this repo https://github.com/jensgrunzer1/archraft-mirrorlist

i am actually grateful that you exists, thanks a lot!
