### ISSUE TITLE
Not able to log into any session

### ISSUE THREAD

**Issue by systemcoding** [archcraft-os/archcraft#308]
- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases/download/v22.07/archcraft-2022.07.18-x86_64.iso)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Detailed Description
So I installed lib32-mesa-vdpau and mesa packages from the core repos then it prompted me to reboot because I installed some core packages. So I rebooted the computer to make sure everything is good. Then i entered my password to log into openbox, then suddenly it brought back me to the login screen. I thought that i entered my password wrong, i entered my password again. It still brought me back to login screen. I tried bspwm just to make sure it is just openbox's problem. It failed to launch my bspwm session. I commented out the compositor lines in the autostart file. No change.

Another Thing:
I also updated the entire system to the absolute latest using ```sudo pacman -Syu```

* ISO Version: archcraft-2022.07.18-x86_64.iso
* System Specs: i3-3rd Gen Processor, 4GB Ram, 1TB Hard Disk
* Graphics Card: Intel HD 2500

## So is there a way to fix this problem?

**Comment by wrenfannin** [comment]
Burn an arch usb, chroot into your installation and remove those two packages or roll them back, see if that fixes your problem

**Comment by systemcoding** [comment]
I removed those packages and i still can't login

**Comment by wrenfannin** [comment]
are you able to log into a tty?

**Comment by systemcoding** [comment]
I was able to log into the tty. But i installed Linux Mint because I didn't find any solution and even asked in Matrix but no one responded. Anyways thanks for the help! Have a great day 😊
