### ISSUE TITLE
polybar launcher in bspwm

### ISSUE THREAD

**Issue by jaennova** [archcraft-os/archcraft#310]
what file is the one that launches the polybar in bspwm?
I normally launch it inside the bspwmrc file, where I add a line like this:
sh ~/.config/bspwm/polybar/launch.sh
but when starting the session the one that comes by default is always launched, try to change these files of the polybar by default, but in some it does not let me save the changes that I make inside them
is there a solution for this problem?

**Comment by brendencallahan** [comment]
It's started by the bspbar script in ~/.config/bspwm/bin. It is called at the end of bspwmrc. By default when you log-in with bspwm, polybar reads the config files from ~/.config/bspwm/polybar. Changes made in ~/.config/bspwm/polybar have been persistent for me. Be sure to check ~/.config/bspwm/bin/bspcolors or change colors directly in your themes as the polybar colors get written to the conf file at startup. Hope that helps!

**Comment by jaennova** [comment]
thanks
