### ISSUE TITLE
winmask issue (EASY FIX)

### ISSUE THREAD

**Issue by brendencallahan** [archcraft-os/archcraft#311]
# Prerequisites

- [X] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [X] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

# Detailed Description

The winmask script isn't being run because of a typo.

# Expected Behavior

When using super+shift+i in bspwm the focused window should be hidden.

# Current Behavior

Nothing happens currently.

# Fix

In ~/.config/bspwm/sxhkd the last line needs to be changed from "winmask" to "bspwinmask"

Seems like something only got renamed in one place, because in bspwm/bin it is bspwinmask.

**Comment by adi1090x** [comment]
Fixed already.
