### ISSUE TITLE
Unable to login using the GUI

### ISSUE THREAD

**Issue by lolmokha** [archcraft-os/archcraft#314]
# Detailed Description

I type a password in login manager but when I press Enter, nothing happens. The same behavior when I use my mouse and click on an arrow (next to password form). Enter key works because I can login into tty, but have no idea where to find out what's going on or how to fix it. I've tried using another keyboard but it doesn't seem to work. I've tried updating using ` sudo pacman -Syyu ` but it hasnt been fixed.

# Expected Behavior
If the password is correct, then it logs into the system, else it displays an error message.

# Current Behavior

It is doing nothing. 

# Failure Information (for bugs)

Might be unrelated but, when running in recovery mode, it gives me the error ` Failed to start: Remount Root and kernel file system ` once then continues with the boot process. Running ` journalctl -xb ` after logging in contains an error
` [Firmware Bug]: TSC_DEADLINE disabled due to Errata; please update microcode to version: 0xb2 (or later) '. This happens even after I updated the microcode and the BIOS

# System specs

* Kernel Version: 5.19.12-arch1-1
* System Specs: Intel i5 660. 16GB memory
* Graphics Card: Nvidia GeForce GT730
* DM: Openbox

## Failure Logs
The failure logs for the error Failed to start: Remount Root and kernel file system 
`  Failed to start Remount Root and Kernel File Systems` 
` systemd-remount-fs.service: Failed with result 'exit-code' `
` systemd-remount-fs.service: Main process exited, code=exited, status=1/FAILURE `
` EXT4-fs: Cannot change data mode on remount ' `

**Comment by Solasoul** [comment]
Hi, I am a user like you, let me see if I can help you do you have a time machine backup done like before this issue happened?

**Comment by lolmokha** [comment]
> Hi, I am a user like you, let me see if I can help you do you have a time machine backup done like before this issue happened?
> 
> If you do, please save whatever files that are important to an external drive and restore and see if it works. If it doesn't restart the PC, a few times and try again. In case it still doesn't work, then do pacman -Syu instead. Clear your tmp files.

I have not done a time machine backup. I've done a pacman -Syu and it still doesn't work

**Comment by adi1090x** [comment]
Keyboard layout?

**Comment by lolmokha** [comment]
> Keyboard layout?

the keyboard layout is QWERTY

**Comment by XxnittanixX** [comment]
yea fucking same here IM SO MAD

**Comment by XxnittanixX** [comment]
-_- grrrr

**Comment by XxnittanixX** [comment]
a bashscript to fix this issue WOULD BE FUCKING HELPFUL
