### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by TobyG74** [archcraft-os/archcraft#315]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [✓ ] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [ ✓] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [✓ ] I checked to make sure that this issue has not already been filed
- [ ✓] I'm reporting the issue to the correct repository

# Detailed Description

Black Screen

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

I can't enter installation mode, just stuck on the black screen after the arch logo, I've tried waiting for a long time but nothing happens

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version: archcraft-2022.09.16-x86_64.iso
* System Specs: -
* Graphics Card: AMD Radeon(TM) R3 Graphics
* Etc

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by GPeaky** [comment]
Hi, I'm having the same issue, after doing a "sudo pacman -Syuu" and restart i can't login into my account appears a black screen and after 5 seconds go back to the login screen. If someone could help us, Thanks!
