### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by krypton-byte** [archcraft-os/archcraft#316]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Detailed Description

Stuck

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

I can't enter installation mode, just stuck on log

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version: archcraft-2022.09.16-x86_64
* System Specs: Intel i3 12100F
* Graphics Card: RTX 2060
* Etc

## Failure Logs

Please include any relevant log snippets or files here.
![stuck](https://i.ibb.co/M7GFQSm/IMG20221006233821.jpg)

**Comment by mn-xd** [comment]
Did you chose to run archcraft with Nvidia drivers ?

**Comment by krypton-byte** [comment]
balena etcher

**Comment by krypton-byte** [comment]
I tried all but the same

**Comment by Solasoul** [comment]
Check if there is an update for your video driver.

**Comment by yifany-github** [comment]
Hi, I have the same issue. Did you fix it?

**Comment by Benjamin51380** [comment]
+1

**Comment by MISTERNEGATIVE21** [comment]
I guess its the problem with new drivers . Nvidia drivers will work if connected to external video output . You need to install vulkan-intel inside tty. Or probably upgrade your kernel

**Comment by yifany-github** [comment]
> k

How do I upgrade the kernel or install vulkan-intel at the boot screen?

**Comment by yifany-github** [comment]
> I guess its the problem with new drivers . Nvidia drivers will work if connected to external video output . You need to install vulkan-intel inside tty. Or probably upgrade your kernel

How do I upgrade the kernel or install vulkan-intel at the boot screen?

**Comment by adi1090x** [comment]
In newer ISOs, this issue has been solved.
