### ISSUE TITLE
Archcraft lagging too much

### ISSUE THREAD

**Issue by korrykatti** [archcraft-os/archcraft#318]
# Detailed Description

Archcraft is lagging to much . Other os ( even arch based ones ) didn't lag this much  so this is probably not a hardware issue. The screen freezes time to time and apps open very slow and bootup takes ten minutes. Please see into it

**Comment by Solasoul** [comment]
Make sure you have at least 4GB of Ram to get the best performance.

**Comment by korrykatti** [comment]
i have 4gb ram
