### ISSUE TITLE
Stop Continue to Boot the System

### ISSUE THREAD

**Issue by yifany-github** [archcraft-os/archcraft#320]
00000000000
1.3482681 CS: 0010 DS: 0000 ES: 0000 CRO: 0000000080050033
1.3482691 CR2: 0000000000000000 CR3: 00000001010ec002 CR4: 0000000000f70ec0
Г
1.3482701 PKRU: 55555554
1.4221191 1915 0000:00:02.0: [drm] GuC firmware 1915/ad1p_quc_69.0.3.bin ve rsion 69.0
1.4221241 1915 0000:00:02.0: [drm] HuC firmware 1915/tg1_huc_7.9.3.bin vers ion 7.9
1.4389171 1915 0000:00:02.0: [drm] HuC authenticated
1.4398381 1915 0000:00:02.0: [drm] GuC submission enabled
1.439840] 1915 0000:00:02.0: [drm] GuC SLPC enabled
1.4402241 1915 0000:00:02.0: [drm] GuC RC: enabled
1.4410851 1915 0000:00:02.0: [drm] Protected Xe Path (PXP) protected conten t support initialized
1.4433561 [drm] Initialized 1915 1.6.0 20201103 for 0000:00:02.0 on minor 0
1.113478] ACPI: video: [Firmware Bug]: ACPI(PEGP) defines _DOD but not _DOS
1.4135511 ACPI: video: Video Deuice [PEGP] (multi-head: yes rom: yes post
: no)
[
1.4437761 input: Video Bus as /devices/INKSYSTM:00/LNXSYBUS:00/PNPOA08:00/d evice:00/LNNUIDED:00/input/input2
[
1.4148961 ACPI: video: Video Device IGFX01 (multi-head: yes ron: no post:
no)
[
1.4451151 input: Video Bus as /devices/LNSYSTM:00/LNXSYBUS:00/PNPOA08:00/L
NXVIDED:01/input/input3
1.4505801 fbcon: 1915drmfb (fb0) is primary device
2.743375] Console: switching to colour frame buffer device 240x67
[
[
[
2.7638951 1915 0000:00:02.0: [drm] fb0: 1915drmfb frame buffer device
2.882264] [drm] andgpu kernel modesetting enabled.
2.8824291 amdgpu: CRAT table not found
2.8824431 amdgpu: Virtual CRAT table created for CPU
2.8824581 andgpu: Topology: Add CPU node
2.8978931 [drm] radeon kernel modesetting enabled.

I was trying to install Archcraft on my laptop, but when I booted the live system from my USB driver, I got those and it stopped at the last line. I tried normal and one with Nvidia, and both showed the same info. 
Can anyone help me? Thanks a lot.

<img width="1122" alt="Screen Shot 2022-10-17 at 15 17 46" src="https://user-images.githubusercontent.com/71915211/196263533-870cf032-0748-4642-b371-a1ff15acbd0d.png">

**Comment by iteng007** [comment]
# I guess you are using an Nvidia graphics card, try adding _ibt=off_ to the boot parameters

**Comment by pixelafk** [comment]
I have this same exact issue on the latest version with an NVIDIA graphics card (it doesn't matter which boot option I choose, normal, into memory, and NVIDIA all end up at this error and then freeze requiring a force shutdown)
