### ISSUE TITLE
OB menu {prefs>comp>edit config} is broken

### ISSUE THREAD

**Issue by riquezjp** [archcraft-os/archcraft#321]
# Detailed Description

The openbox menu option  [Preferences > Compositor > Edit configuration file] has no effect. The config file does not open.
This used to work, but has stopped working at some point in the last few months.

![Screenshot_2022-10-20-21-25-24_1920x1080](https://user-images.githubusercontent.com/10734045/197053474-ac8ba86b-84ef-411c-ac8a-ea2f68c5418c.png)

I see the following in the journal, but gedit does not open.

```
Oct 20 21:40:48 Sulaco dbus-daemon[855]: [session uid=1000 pid=855] Activating service name='org.gnome.gedit' requested by ':1.100' (uid=1000 pid=6668 comm="exo-open /home/rico/.config/picom.conf")
Oct 20 21:40:48 Sulaco dbus-daemon[855]: [session uid=1000 pid=855] Successfully activated service 'org.gnome.gedit'
```

other menu options such as "edit menu.xml" do work.

**Comment by adi1090x** [comment]
Fixed, Long ago.
