### ISSUE TITLE
Failed to start (installing)

### ISSUE THREAD

**Issue by BTWarchBTW** [archcraft-os/archcraft#323]
When I tried to install archcraft on my pc it started well but on that system d logs where service start  There I got stuck on failed to start refresh Pacman mirror list (I dont know to be exact because I closed my pc but it is almost same service) after there the installation stops

**Comment by mn-xd** [comment]
https://github.com/archcraft-os/archcraft/issues/146

**Comment by BTWarchBTW** [comment]
Thanks for you help but I tried already 
And it didn't work

**Comment by mn-xd** [comment]
Does internet work on your machine? Try ping command on tty

**Comment by BTWarchBTW** [comment]
Mn-xd I don't have fiber I have my mobile phone to use internet with hospot and how can I open tty in systemd logs, I tried but nothing showed up rather than blank screen

**Comment by BTWarchBTW** [comment]
![Uploading IMG_20221105_174844.jpg…]()
Tty☝️
![Uploading IMG_20221105_174826.jpg…]()
System d logs ☝️💀

**Comment by BTWarchBTW** [comment]
There is way called usb tethering in mobile where you can share internet from phone to pc with usb cable so I did that but didn't saw any changes

**Comment by BTWarchBTW** [comment]
This problem has ben solved 
If any one els is facing same problem here's how to fix it 
Download a older iso from your current one or s newer (in my case it was 2 month older iso)
Works charm
