### ISSUE TITLE
Display Scales In Wrong Direction

### ISSUE THREAD

**Issue by tekn0x** [archcraft-os/archcraft#324]
Hello. For some reason when I change the scale in the display settings from 1x into 2x. Everything gets smaller instead of getting bigger. Is that the desired behavior?

In my other distros when I change the scale to a larger number, things get bigger.  I am not sure how to make everything the right size for my retina display.

Thank you for any assistance.

**Comment by SwissOS** [comment]
I have exactly the same problem. Instead of using my native resolution of 2560x1600 with scale 2x, I had to resort to using 1280x800 and scale 1.
Very strange problem indeed, as you say, normally, scaling always worked correctly (ie: setting 2x makes things bigger, not smaller).

**Comment by adi1090x** [comment]
No specific config for this has been done in Archcraft.

**Comment by Abdullah-03** [comment]
Same problem, couldn't figure out the solution.
