### ISSUE TITLE
[BUG] Qwerty layout is forced for system decryption

### ISSUE THREAD

**Issue by Titikomba** [archcraft-os/archcraft#325]
# Detailed Description
I installed Archcraft using Calamares.
I'm a non-qwerty user, so I adjusted the keyboard layout during the installation. I decided to encrypt my system. Installation went well.
When booting, I am not able to provide the correct passpharse. 
It turns out that if I enter my passphrase assuming a qwerty layout, it works.

# Expected Behavior

I expected to be able to enter my passphrase with the layout I chose during the installation phase. 

# Current Behavior

Currently, it is not possible: I have to write my passphrase as if I had a qwerty layout.

## Steps to Reproduce

Install Archcraft using Calamares and select a non-qwerty layout. 
Encrypt the system by ticking the box when the option is proposed.
Reboot.

## Context

* ISO Version: 2022_09_16-x86_64
* I use BSPWM (I do not think this is relevant but...)
* Archcraft is the only OS on the machine, I erase the disk during installation.

**Comment by mn-xd** [comment]
Do you use openbox, bspwm or other window manager ? Because I had the same problem and I solve it by switching from bspwm to openbox.

**Comment by adi1090x** [comment]
It seems like an issue with calamares, It should have been fixed by now.
