### ISSUE TITLE
Change default browser

### ISSUE THREAD

**Issue by ismanolgarcia** [archcraft-os/archcraft#328]
Cheers ! Can someone help me, I want to know how to set another browser as default. 
Example: google chrome

**Comment by BTWarchBTW** [comment]
The chrome or any other browser will tell you that you don't have set it to default, "do you want to make browser x to be your default browser?" You can just yess to that 
Simplest way

**Comment by ismanolgarcia** [comment]
Yes I tried that but I want to know if there will be an alternative to do it through the terminal

**Comment by TOLIE-OFFICIAL** [comment]
> The chrome or any other browser will tell you that you don't have set it to default, "do you want to make browser x to be your default browser?" You can just yess to that Simplest way

it seems that it will not work when i change to google-chrome from firefox  :(

**Comment by ismanolgarcia** [comment]
> > Chrome o cualquier otro navegador le dirá que no lo ha configurado como predeterminado, "¿quiere que el navegador x sea su navegador predeterminado?" Puedes simplemente decir sí a esa forma más simple
> 
> parece que no funcionará cuando cambie a google-chrome desde firefox :(

If the same thing happens to me, I'm looking for an alternative that can be defined as default by some file from the terminal

**Comment by anthonyportugal** [comment]
Searching for information about it I found the following, you can set it in _~/.config/mimeapps.list_

```
[Default Applications]
text/html=google-chrome.desktop
x-scheme-handler/http=google-chrome.desktop
x-scheme-handler/https=google-chrome.desktop
x-scheme-handler/about=google-chrome.desktop
x-scheme-handler/unknown=google-chrome.desktop
```
In case you need to do it with a command from the terminal, you could create a script that modifies the file with the values for each browser

**Comment by ktunprasert** [comment]
There's an XFCE settings manager in the global super menu called "Settings Manager" you can set your default browser from there. You can test whether this has taken affect by trying to `xdg-open` a link
