### ISSUE TITLE
No CLI installer at all??!!

### ISSUE THREAD

**Issue by alexlyee** [archcraft-os/archcraft#329]
I'm on the latest special edition (2022-10), and NONE of the packaged versions seem to have the CLI installer. Why is this?

**Comment by b08x** [comment]
> Why is this?

If a feature you're looking for isn't immediately apparent or available, try looking in the  [Archcraft Reddit forum](https://www.reddit.com/r/archcraft/). Someone may have already answered this question. To get the best answer, include a few more details about what you are looking to accomplish. 

Opening an issue on GitHub is generally intended for people actively developing the project. Asking why something doesn't exist, especially when you use exclamation points, is rude and distracting.

**Comment by alexlyee** [comment]
@b08x I'm sorry if I came across as rude and distracting. I didn't use exclamation points though. I scoured through Reddit and the questions here on Github and this place seemed more active for simple questions. I also waited a few weeks for a response from the support email before trying here. As all the documentation I could find on Archcraft seems to suggest that the CLI installer is a regular included feature, I was a little frustrated at the time because paying to the author in exchange for a more complete .iso and limited support via. email did not actually get me either of the things I expected. If some of that came out in my message in a few words of wasted text, I hope you can understand.

I posted my question on Reddit, hopefully someone can help.

**Comment by JVCAv1** [comment]
@alexlyee 
Are you referring to the ABIF installer? if so you can simply launch it with the welcome app. 
Refer to the wiki for a complete guide: 
https://wiki.archcraft.io/docs/install-archcraft/install-with-abif

**Comment by alexlyee** [comment]
I was, recently I saw he added it in his last update.
