### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by gibranlp** [archcraft-os/archcraft#33]
Sometimes when i start archcraft, i just get a black screen, no errors, no nothing, sometimes using the initframs helps but some other times i just cant get in.

Usually a few reboot fixes the issue.

**Comment by adi1090x** [comment]
Well, that's maybe something with you machine, if it was an issue with Archcraft, the Black screen issue which is due to GPU drivers would be persistent.

**Comment by gibranlp** [comment]
ok...

**Comment by Tekadon58** [comment]
I'm having the same problem, I don't have a dedicated video card.
