### ISSUE TITLE
Login Loop and Failure

### ISSUE THREAD

**Issue by vwagenjetta** [archcraft-os/archcraft#330]
- [ X] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [ X] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [X ] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository

# Detailed Description

After installing snapd, Brave browser, Discord, Fish Shell, and updating with yay -Syu, I am no longer able to login to my computer on BSPWM or OpenBox. I type my password, the screen goes black, and the login screen pops up again. After searching through all solutions given on GitHub, Reddit, and various other forums, the problem persists, but now when I login with the correct password it says Login Failed. I can login to either WM as Root, but I get a black screen (nitrogen is an empty box when I open it) with a default right click menu (in OpenBox), no polybar, and none of the hotkeys are working.

* ISO Version: Latest, downloaded and installed on 12/6/2022 from Archcraft.io sourceforge link (Side note: github link downloaded 1.9GB of 2.0GB and failed), USB drive created with gnome-multi-writer, installed with calamares (erase disk, no swap)

* System Specs: Asus laptop, 7th Gen Intel Core i7 CPU, 16GB RAM

* Graphics Card: GTX 1050 Ti (mobile)

A few similar issues (given solutions unsuccessful):
https://github.com/archcraft-os/archcraft/issues/260
https://www.reddit.com/r/archcraft/comments/rmzplg/stuck_on_login_screen/
https://github.com/archcraft-os/archcraft/issues/21
https://www.reddit.com/r/archlinux/comments/up99ox/help_with_login_loop/

I will try wiping the system and reinstalling when I get back home to my USB drive

**Comment by mn-xd** [comment]
It is all because of fish shell. I had the same problem. If you set fish shell as default with this command: chsh -s $(which fish) you will need to get to TTY (press Ctrl+alt+F1 or F3) and type this command: /usr/bin/chsh -s /bin/bash.

**Comment by oliviertripet** [comment]
Thank you @mn-xd you just saved my life !

**Comment by adi1090x** [comment]
Lesson: Don't use fish as your login shell. It's just an interactive shell.
