### ISSUE TITLE
ArchCraft Openbox - Issues with xrender compositor after upgrade

### ISSUE THREAD

**Issue by tokenwizard** [archcraft-os/archcraft#331]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
>**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases/tag/v21.10)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Detailed Description

After running the most recent updates (sudo pacman -Syy && sudo pacman -Syu) the xrender compositor causes Xorg to max out CPU usage. I have been running this compositor for months, but after my recent system updates, this issue started. 

![Screenshot_2022-12-07-10-50-40_3440x1440](https://user-images.githubusercontent.com/24832561/206229362-303965df-23cb-4b48-8515-866c6a0fe69f.png)

# Expected Behavior
Normal compositor behavior with no lag or stutter. 

# Current Behavior

Input/Response seems laggy. Dragging windows around is choppy. CPU usage is extremely high. 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
1. run a full system update and reboot
2. make sure you are using the xrender compositor
3. check CPU usage with top or similar while dragging a window around the desktop. 

## Context

Happens no matter the conditions, even if I have no other applications running other than a terminal with top running. 

* ISO Version:  
archcraft-2022.09.16-x86_64.iso

* System Specs: 
  
![image](https://user-images.githubusercontent.com/24832561/206228460-8555e540-5398-4600-bb05-3d8e3ffb3501.png)

* Graphics Card:
(see above)

Openbox 3.6.1
libxrender: 0.9.11-1

To clarify, if I use the Openbox menus to switch tot he 'glx' compositor, Xorg CPU usage goes back to normal, along with all lag that was being experienced under xrender.

**Comment by adi1090x** [comment]
It's recommended to use `glx` backend. xrender is only when glx doesn't work on some machines.
