### ISSUE TITLE
Archcraft automatically goes to sleep mode

### ISSUE THREAD

**Issue by mn-xd** [archcraft-os/archcraft#332]
When I am rendering large simulations in blender. My computer automatically goes to sleep mode. I know that in Archcraft settings I can disable sleep but I want to keep it because sometimes it is useful. I don't want my computer to automatically go to sleep when it is under load.

**Comment by adi1090x** [comment]
Just enable tray icon in xfce power settings and then right click on battery icon in tray and toggle `presentation mode`. It'll prevent computer from going to sleep.
