### ISSUE TITLE
Nvidia gpu driver screen tear

### ISSUE THREAD

**Issue by littleblack111** [archcraft-os/archcraft#336]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
>**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Detailed Description

I got some screen tearing issues in Nvidia gpu, the methods online works(fore composite pipeline from Nvidia-settings) but it will make the screen very laggy, for eg, I was playing Minecraft, and even it says it is 700fps, it still make me feel like playing on a 10-30fps machine, and if I stop using the method, (disable force composite pipeline) it will be super smooth(but with screen tears)

# Expected Behavior

with smooth fps and no screen tear

# Current Behavior

screen tearing/lagging

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. get a GeForce GTX 1060 6GB(that's what gpu I'm using)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version:
2021.10(but I don't think it matters)
* System Specs:
250GB+2TB external hard drive
* Graphics Card:
GeForce GTX 1060 6GB
* Etc
i7-8700 CPU
16GB memory

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by mn-xd** [comment]
Did you try `force full composite pipeline`? 
This should help you: 

- https://askubuntu.com/questions/1185277/screen-tearing-in-linux-with-nvidia-graphics
- https://wiki.archlinux.org/title/NVIDIA/Troubleshooting

**Comment by littleblack111** [comment]
And I tried using the GZL backend (in the picom) and it will make the poly at very ugly(it make everything move left 10cm)and so I wont be able 2 see sth, and it is overlapping

**Comment by littleblack111** [comment]
fix by using xr_glx_hybrid backend(setted in picom.conf)

**Comment by littleblack111** [comment]
fix by using xr_glx_hybrid backend(setted in picom.conf)
