### ISSUE TITLE
Problem with bluetooth after installing the new version.

### ISSUE THREAD

**Issue by wondersalmon** [archcraft-os/archcraft#337]
I installed the new version of Archcraft (2023.01.01, openbox). And now I can not pair bluetooth headphones. When using a blueberry, a pairing code appears but cannot be confirmed. When using blueman, the dialog also does not appear and it is impossible to connect devices.

On the previous version of Archcraft, the blueberry connection worked fine

**Comment by mn-xd** [comment]
For now I can't tell what is causing this issue but you can try to pair your headphones like this: open "bluetoothctl" in terminal and type "scan on". if your device is still not showing up try "devices" and to pair with it type: "pair here_goes_bluetooth_address" use tab to autocomplete this command.

**Comment by wondersalmon** [comment]
Thanks, it works. Not as convenient as it used to be, but still
