### ISSUE TITLE
Blank area in Pamac preferences

### ISSUE THREAD

**Issue by wondersalmon** [archcraft-os/archcraft#339]
Hello! On the new version of the OS, fields without text appeared in the pamac settings window. The problem is solved by removing gtk3-nocsd, but this entails constant messages in the console. Is there a way to correctly fix the error?

**Comment by wondersalmon** [comment]
`unset LD_PRELOAD` solves the problem, but I have not yet realized how well it solves

**Comment by adi1090x** [comment]
Solved.
