### ISSUE TITLE
nvim/vim config

### ISSUE THREAD

**Issue by plasmoduck** [archcraft-os/archcraft#34]
Where can I download (from the internet/github) the nvim/vim config file used in archcraft please?

**Comment by adi1090x** [comment]
There you go : https://github.com/archcraft-os/archcraft/blob/master/iso/airootfs/etc/skel/.vimrc

**Comment by Tekadon58** [comment]
> There you go : https://github.com/archcraft-os/archcraft/blob/master/iso/airootfs/etc/skel/.vimrc

Page not found

**Comment by matthewweldon** [comment]
I went back to an older commit and found a hard link to his above .vimrc, but i don't know if this represents the latest .vimrc, I couldn't find it in the latest.

[https://github.com/archcraft-os/archcraft/blob/39658401d2d706b40ed3994e065ad6674aa372b2/iso/airootfs/etc/skel/.vimrc](https://github.com/archcraft-os/archcraft/blob/39658401d2d706b40ed3994e065ad6674aa372b2/iso/airootfs/etc/skel/.vimrc)

**Comment by Tekadon58** [comment]
>  @Tekadon58 I went back to an older commit and found a hard link to his above .vimrc, but i don't know if this represents the latest .vimrc, I couldn't find it in the latest.
> 
> [https://github.com/archcraft-os/archcraft/blob/39658401d2d706b40ed3994e065ad6674aa372b2/iso/airootfs/etc/skel/.vimrc](https://github.com/archcraft-os/archcraft/blob/39658401d2d706b40ed3994e065ad6674aa372b2/iso/airootfs/etc/skel/.vimrc)

Tranks
