### ISSUE TITLE
[QUESTION] Default VM "OpenBox"

### ISSUE THREAD

**Issue by PonyLucky** [archcraft-os/archcraft#340]
# Detailed Description

Hi, I booted into ArchCraft and found some basic bugs. Like the OS was 10 years old and not maintained. It wasn't actually bugs from the OS but from the VM. I went on the website of OpenBox and found that the last update was 13 years ago !

# Feature request

I know that we can change the VM to a one with support of multi-screen. I think that the default VM should be actually maintained.

# Expected Behavior

For example, correct multi-screen display.

# Current Behavior

Two 1920p screens. One vertical and the other horizontal will make the top bar display only on the vertical screen as it is the higher one, even if secondary screen.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Having two screens of different resolution.
2. OR placing one vertical.

## Context

Also tried the thing on my portable PC where I don't have an NVIDIA graphic card.

First and primary screen: 3440×1440p (21/9).
Second screen: 1920×1080p (16/9). Oriented vertically **on the right**.

* ISO Version: Last ISO from 01/09/2023
* System Specs: x64 motherboard from MSI.
* Graphics Card: NVIDIA 3080 RTX (proprietary drivers)
* RAM: 64Go 3320MHz
* Disks: OS installed on 512Go SSD NVMe, and others disks but not important here

**Comment by adi1090x** [comment]
The OS is not 10 years old and unmaintained. The Openbox WM is. But it doesn't matter because it still works like a charm even in 2024. And it'll be the default WM of Archcraft as long as it works.
