### ISSUE TITLE
I have an error during the installation

### ISSUE THREAD

**Issue by mesteryui** [archcraft-os/archcraft#343]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
>**YOU MAY DELETE THE PREREQUISITES SECTION.**
Look the log:
https://termbin.com/cawm

**Comment by ViniciusRed** [comment]
```ERROR: Installation failed: "El instalador no pudo particionar el disco «WDC WD10JPVX-22JC3T0»." ```
Did you manually partition or was it normal?

**Comment by mesteryui** [comment]
It was normal

**Comment by ViniciusRed** [comment]
Have you tried manually?

**Comment by adi1090x** [comment]
Not enough information or logs.
