### ISSUE TITLE
custom dotfiles dont work

### ISSUE THREAD

**Issue by itzRealDuck** [archcraft-os/archcraft#344]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
>**YOU MAY DELETE THE PREREQUISITES SECTION.** 

- [ yes] I am using the [latest version](https://github.com/archcraft-os/releases/releases)
- [ i didnt check] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [ yes] I checked to make sure that this issue has not already been filed
- [ i mean this is the iso where all development goes so yes] I'm reporting the issue to the correct repository

# Detailed Description

so when i switched from endeavour to archcraft i saw peoples dotfiles like xmonad and bspwm i installed bspwm today and i did everything and when i switched to the loginn screen and entered bspwm it just ot a black screen i waited for a few minutes but nothing loaded and the same happend to xmonad dots but it didnt show anythinng like the bar just the wallpaper also all of those things worked in endeavour so i am sure 100% that its a archcraft  problem

Please describe the issue in detail

# Expected Behavior
i expected it to load everything just find since i followed the tutorial and it had a installation script and a few videos were made about how to install it so yes
Please describe the behavior you are expecting

# Current Behavior
just a black screen with the only thing there is my cursor
What is the current behavior?

# Failure Information (for bugs)  

black screen with the only thing that works is my cursor

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce 
 1 - install any dotfiles or these  https://github.com/eldermf/bspwm
2- log out of the main session and log in bspwm 
you get a big black screen
Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context 
iso version : the latest one
 1 : i got  a old laptop its a hp elitebook 8460p and cpu is intel core i5  
gpu : Intel 2nd Generation Core Processo 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version:
* System Specs:
* Graphics Card:
* Etc

## Failure Logs
what?
Please include any relevant log snippets or files here.

**Comment by itzRealDuck** [comment]
i removed my previous dots and now it only shows the login screen

**Comment by adi1090x** [comment]
Not an issue of Archcraft.
