### ISSUE TITLE
error on oh my zsh update

### ISSUE THREAD

**Issue by seeval** [archcraft-os/archcraft#345]
oh my zsh update ($ omz update) fails with following error:

error: unable to normalize alternate object path: /home/aditya/Archcraft/packages/archcraft-skeleton/archcraft-omz/oh-my-zsh/objects
fatal: reference is not a tree: master

using 2023 archcraft

**Comment by adi1090x** [comment]
Updated the package, but if you want to update manually, Delete the ~/.oh-my-zsh/ folder and reinstall OMZ. 
PS: Don't forget to put custom themes.
