### ISSUE TITLE
neofetch icons turn to arabic letters after installing fonts 

### ISSUE THREAD

**Issue by mativiters** [archcraft-os/archcraft#346]
When I install the AUR package persian-fonts, icons in neofetch (the ten or so vertical icons before every statistics line) turn to Arabic letters. When I uninstall they turn to normal.
I use the latest iso (2023.01.20 i think) and I have not done anything else other than install fonts.

**Comment by adi1090x** [comment]
Those icons are glyphs, So they gonna be messed up if you install new fonts. If you need that font, i suggest you use `default/normal neofetch config`
