### ISSUE TITLE
bug the sound applet do not show te volume level but it actually change it

### ISSUE THREAD

**Issue by alavaelian** [archcraft-os/archcraft#347]
i am using the last version of arch craft
when i use the mause well to change the volume the volume actually change but it not shows on the applet it stuck on the default value

**Comment by lgmarcosxavier** [comment]
Greetings, I also encountered this case, in addition to selecting the sound section in polybar, muted the sound.

I managed to solve it by simply changing the font size.

Preferences > Change Font > Status Bar (polybar)

So I guess it must be a screen resolution issue.

**Comment by adi1090x** [comment]
Fixed.
