### ISSUE TITLE
Replace systemd with something else, please

### ISSUE THREAD

**Issue by Wjxfi** [archcraft-os/archcraft#348]
I really want this, it will greatly increase the security of the system

More than [150 linux systems](https://distrowatch.com/search-mobile.php?ostype=All&category=All&origin=All&basedon=All&notbasedon=None&desktop=All&architecture=All&package=All&rolling=All&isosize=All&netinstall=All&language=All&defaultinit=Not+systemd&status=Active#simple) have done this. And I feel much safer on them than I do here

Everyone knows that systemd is bad

devuan, trisquel, mx linux and [many others](https://distrowatch.com/search-mobile.php?ostype=All&category=All&origin=All&basedon=All&notbasedon=None&desktop=All&architecture=All&package=All&rolling=All&isosize=All&netinstall=All&language=All&defaultinit=Not+systemd&status=Active#simple) have done this

I really want to feel safe, and without that I can't afford it

edit:
Artix must have done this (it is similar to arch linux (without systemd))

The best alternative: OpenRC

'

'

systemd consumes a lot of resources. Absolutely any other alternative will make your os more lightweight

Problems: artificially obfuscated code to make it hard to find vulnerabilities, so there are thousands of vulnerabilities, created by redhat, which is a contractor of anb, systemd is forcibly included in linux distributions, linux creator expressed doubts about systemd, the whole community does not like it, systemd code uses google dns and more,

**Comment by adi1090x** [comment]
Archcraft is and will be closest to Arch, which still uses systemd.
