### ISSUE TITLE
use libre boot instead of the regular boot

### ISSUE THREAD

**Issue by Wjxfi** [archcraft-os/archcraft#349]
all information below, taken from https://libreboot.org/
(there were a lot of links in the text, but they all got deleted because of the transfer)

'

The libreboot project provides libre boot firmware that initializes the hardware (e.g. memory controller, CPU, peripherals) on specific Intel/AMD x86 and ARM targets, which then starts a bootloader for your operating system. GNU+Linux and BSD are well-supported. It replaces proprietary BIOS/UEFI firmware. Help is available via #libreboot on Libera IRC.

NEW RELEASE: The latest release is Libreboot 20221214, released on 14 December 2022. See: Libreboot 20221214 release announcement.

Why should you use libreboot?
Libreboot gives you freedoms that you otherwise can’t get with most other boot firmware. It’s extremely powerful and configurable for many use cases.

You have rights. The right to privacy, freedom of thought, freedom of speech and the right to read. In this context, Libreboot gives you these rights. Your freedom matters. Right to repair matters. Many people use proprietary (non-libre) boot firmware, even if they use a libre OS. Proprietary firmware often contains backdoors, and can be buggy. The libreboot project was founded in in December 2013, with the express purpose of making coreboot firmware accessible for non-technical users.

The libreboot project uses coreboot for hardware initialisation. Coreboot is notoriously difficult to install for most non-technical users; it handles only basic initialization and jumps to a separate payload program (e.g. GRUB, Tianocore), which must also be configured. The libreboot software solves this problem; it is a coreboot distribution with an automated build system that builds complete ROM images, for more robust installation. Documentation is provided.

How does libreboot differ from regular coreboot?
In the same way that Debian is a GNU+Linux distribution, libreboot is a coreboot distribution. If you want to build a ROM image from scratch, you otherwise have to perform expert-level configuration of coreboot, GRUB and whatever other software you need, to prepare the ROM image. With libreboot, you can literally download from Git or a source archive, and run make, and it will build entire ROM images. An automated build system, named lbmk (Libreboot MaKe), builds these ROM images automatically, without any user input or intervention required. Configuration has already been performed in advance.

If you were to build regular coreboot, without using libreboot’s automated build system, it would require a lot more intervention and decent technical knowledge to produce a working configuration.

Regular binary releases of libreboot provide these ROM images pre-compiled, and you can simply install them, with no special knowledge or skill except the ability to follow simplified instructions, written for non-technical users.

'

I am very fond of privacy and sincerely ask you to add this

Many systems have already done this, such as Trisquel

I really want to feel safe, and without that I can't afford it

**Comment by adi1090x** [comment]
Again, very much subjective and the choice of end-user.
