### ISSUE TITLE
use the linux-libre kernel instead of the normal kernel

### ISSUE THREAD

**Issue by Wjxfi** [archcraft-os/archcraft#350]
you may not know it, but inside the normal linux kernel there are nonfree components

linux libre removes all nonfree components and guarantees freedom. Please add it

this has already been added by many distributions, such as Trisquel

https://www.fsfla.org/ikiwiki/selibre/linux-libre/

Don't look at the beauty of the site, look at the functionality, it's good

I really want to feel safe, and without that I can't afford it

**Comment by adi1090x** [comment]
Very much subjective. It's the end-user's choice ultimately.
