### ISSUE TITLE
compositor bug

### ISSUE THREAD

**Issue by Wjxfi** [archcraft-os/archcraft#353]
openbox > right click > preferences > compositor > Incorrect entry to the channel menu "/usr/share/archcraft/openbox/pipemenus/ac-compositor"

I may have misspelled the words in front of the "" because I used the translator

'

you get it, I can't get into the composer menu

Before that, I uninstalled picom-ibhagwan-git on the advice from https://wiki.archcraft.io/docs/install-archcraft/post-install

I don't know if it's because I deleted it or not, but if it is, it can be replaced (maybe)

**Comment by adi1090x** [comment]
Fixed already.
