### ISSUE TITLE
When I change the theme, the performance decreases slightly

### ISSUE THREAD

**Issue by Wjxfi** [archcraft-os/archcraft#354]
Was 567mb, became 1101

And this is not a one-time thing. It does not go below 1000

performance can be corrected (please)

(it should go back to about 500 mb and not stay at 1000 mb)

**Comment by adi1090x** [comment]
No it doesn't. Just tested and it's not like that.

Perhaps you're judging the memory usage by polybar, which doesn't show correct info sometimes.
