### ISSUE TITLE
Premium 4k or 8k demonstrations

### ISSUE THREAD

**Issue by Wjxfi** [archcraft-os/archcraft#355]
Your beautiful videos of premium builds can be improved by improving video quality

My monitor supports up to 4k resolution, but your video does not. This is bad, because you want to make everything beautiful.

I would be happy if you could improve the quality of the video.

Sorry to be off-topic, couldn't find another place.

**Comment by adi1090x** [comment]
I don't have a 4k or 8k monitors, Sorry.
