### ISSUE TITLE
change firefox to librewolf

### ISSUE THREAD

**Issue by Wjxfi** [archcraft-os/archcraft#356]
it is the same as firefox but it has a lot of advantages.

no telemetry, unlike firefox

popularity

new private features

And so much more

some information from the site below

What is LibreWolf?
This project is a custom and independent version of Firefox, with the primary goals of privacy, security and user freedom.

LibreWolf is designed to increase protection against tracking and fingerprinting techniques, while also including a few security improvements. This is achieved through our privacy and security oriented settings and patches. LibreWolf also aims to remove all the telemetry, data collection and annoyances, as well as disabling anti-freedom features like DRM.

https://librewolf.net/

**Comment by adi1090x** [comment]
Very much subjective. And end-user can always uninstall firefox and install librewolf if they want.
