### ISSUE TITLE
ERROR: Hook 'openswap' cannot be found

### ISSUE THREAD

**Issue by Wjxfi** [archcraft-os/archcraft#357]
The system works perfectly except for the error

With sudo pacman -Syyu and with sudo pacman -S flatpak I see an error:
```ERROR: Hook 'openswap' cannot be found```

**Comment by ab0veall** [comment]
It appears that you're encountering an error related to the 'openswap' hook when running the commands 'sudo pacman -Syyu' and 'sudo pacman -S flatpak'. The error message indicates that the specified hook cannot be found. Hooks in Pacman are scripts that perform additional tasks during package installation or removal.

Let's focus on resolving this issue in a responsible and practical manner, while prioritizing the stability and security of your system.

First, let's ensure that you have the most up-to-date package databases by running the command 'sudo pacman -Sy'. Next, check if the 'openswap' package is installed on your system. If it's missing, you can try reinstalling it using 'sudo pacman -S openswap'. This may help resolve the issue you're experiencing.

If you no longer require the 'openswap' hook, you have the option to remove it from the relevant configuration file. However, it's important to exercise caution when modifying configuration files, as making incorrect changes could potentially create further complications. It's always a good practice to create backups before making any modifications.

Remember, it's crucial to follow established best practices and avoid any modifications that may compromise the stability and security of your system. If you have any additional questions or require further assistance with the troubleshooting process, please don't hesitate to ask. I will be here to help

**Comment by adi1090x** [comment]
Hope it's solved. Just add `opensway` in hooks array of your mkinit config file if that particular hook is required.

install `mkinitcpio-openswap` pkg as well.
