### ISSUE TITLE
Changing the sound does not work (in Polybar)

### ISSUE THREAD

**Issue by Wjxfi** [archcraft-os/archcraft#358]
it starts working after:
```switching to a different desktop theme```

all other buttons work in polybar

This is really inconvenient. Please fix it

'

I just realized that it works, but the icon does not change (remains Mute).

**Comment by brendencallahan** [comment]
I'm having this happen as well. Volume works as expected but the polybar symbol does not update until bspwm is reloaded.

**Comment by Mauroardila** [comment]
Same problem in last .iso. Any solution?

**Comment by brendencallahan** [comment]
> Same problem in last .iso. Any solution?

The only 'solution' I've found is to reload bspwm or ignore it. (alt+ctrl+r).

**Comment by Muddyf0x** [comment]
Hi i had the same problem with polybar tho on openbox.
Just go to your ~/.config/openbox-themes/themes/default/polybar/modules.ini and comment this line out:
`
sink = alsa_output.pci-0000_12_00.3.analog-stereo
`
Probably best for most users who only use the default sink

**Comment by brendencallahan** [comment]
Just tried this and it didn't resolve it for me. The volume icon still does not update until I reload bspwm either with ctrl+alt+r or by applying a new theme. I've tried setting it to another audio device found by `pactl list sinks` but that didn't work either.

**Comment by adi1090x** [comment]
I've already fixed that issue a long time ago, don't you guys update your installation.
