### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by jkalter24** [archcraft-os/archcraft#36]
IT ASKS ME FOR A SUDO PASSWORD EVERY DAMN TIME

**Comment by thonkdifferent** [comment]
Sudo pasword for the live media is: `liveuser`.

Also, don't forget to add your user to the sudoers file

**Comment by adi1090x** [comment]
because the password is enabled in the live ISO, and mentioned everywhere that it's `liveuser` .

**Comment by ziunadev** [comment]
i got bumped into screen lock in liveusb, is the password still same the same?
