### ISSUE TITLE
Blinking Cursor on Black Screen with No TTY Access

### ISSUE THREAD

**Issue by psygo** [archcraft-os/archcraft#361]
I know this isn't really a problem with Archcraft but any help would be greatly appreciated, since I haven't been able to find much helpful info elsewhere.

After a little bit more than 6 months of great use of Archcraft, I decided to make another update with `sudo pacman -Syu`. However, this time, when I rebooted the system, all I got was a black screen with a blinking cursor, and I can't even access any TTY! :/

I had backed up everything with Timeshift but how am I going to access it if literally nothing works? I don't know if this is a problem with GRUB though.

> This might be related to #306

**Comment by jhonvidal** [comment]
I have almost the same problem after installing the archcraft ISO with openbox by default, I get a completely black screen and I can't do anything or access the TTY.

I was able to enter the operating system as a recovery, perform the following instructions:

https://wiki.archcraft.io/docs/install-archcraft/post-install

still the problem persists.

any solution?

**Comment by XxnittanixX** [comment]
oh yha  oh yha  same here buddy IM FUCKING UPSET

**Comment by adi1090x** [comment]
Perhaps a faulty `mesa` update (That happens quiet a lot nowadays)

Just enter into tty, use any tty from 1 to 7 and downgrade the mesa pkg to previous one.

I know it's been open for so long, and perhaps already has been solved. Prefer Archcraft communities for such issues for quick solutions.
