### ISSUE TITLE
Login username text is misplaced on 1366x768 resolution

### ISSUE THREAD

**Issue by OpenSauce04** [archcraft-os/archcraft#362]
# Detailed Description

Please describe the issue in detail
The text for the username on the login screen appears to be misplaced and cut off on the login screen while using a 1366x768 monitor
![20230307_205325.jpg](https://user-images.githubusercontent.com/48618519/223551729-5a9a5604-af37-4b4e-a6da-7bc0ccaa1c8a.jpg)

# Expected Behavior

Username text should be correctly centered and not have the text cut off at the top

# Current Behavior

The username text is off-center and cut off at the top. This does not affect the password prompt whatsoever

## Steps to Reproduce

1. Use latest Archcraft using 1366x768 resolution
2. Look at login screen

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version: archcraft-2023.01.20-x86_64.iso
* System Specs: 
![image](https://user-images.githubusercontent.com/48618519/223551525-6ca11a5a-89a9-4a28-9918-a0a312c139a5.png)

**Comment by alluka3101** [comment]
well, same issue.

**Comment by alluka3101** [comment]
found a temporary solution. Just edit the theme.conf in the sddm ( change the fontsize to 10 or 15)

**Comment by adi1090x** [comment]
Edit `/etc/sddm.conf.d/kde_settings.conf` file and adjust font size or edit `/usr/share/sddm/themes/archcraft/theme.conf` file and adjust ScreenWidth and ScreenHeight and Font size there.
