### ISSUE TITLE
Displaying wallpaper only

### ISSUE THREAD

**Issue by kdbaustert** [archcraft-os/archcraft#37]
After login screen it just sits there showing the grey background nothing happens

**Comment by Antidote1911** [comment]
With no more information... (live iso ? after installation ? starting Bspwm or Openbox ? ..... )

**Comment by adi1090x** [comment]
Probably an issue with display/graphics drivers. Nvidia?

**Comment by SamirOmarov** [comment]
Change WM to bspwm.

**Comment by Antidote1911** [comment]
> Change WM to bspwm.

and comment the line exec compton -b & in ~/.config/openbox/autostart
Logout, and you can reconnect with Openbox

**Comment by adi1090x** [comment]
Is it resolved?
