### ISSUE TITLE
xfce gdbus.error:org.freedesktop.policykit1.error.failed: an authentication agent already exists for the given subject

### ISSUE THREAD

**Issue by ifqygazhar** [archcraft-os/archcraft#374]
The error show after user login

**xfce gdbus.error:org.freedesktop.policykit1.error.failed: an authentication agent already exists for the given subject**

I have solution on internet [here](https://www.blackmoreops.com/2013/11/19/fix-gdbus-error-org-freedesktop-policykit1-error-failed-authentication-agent-already-exists-given-subject-error-kali-lmde-debian-linux/) but i not found a session and start on archcraft, i use archcraft xfce edition

**Comment by adi1090x** [comment]
This is not Archcraft XFCE repo.

**Comment by Frestein** [comment]
The error show after user login
![Screenshot_2024-01-21-03-20-39_1920x1080](https://github.com/archcraft-os/archcraft/assets/85928597/915a8080-14d2-48e0-b53e-e4e38c4ee083)
Archcraft Openbox

**Comment by Frestein** [comment]
[SOLVED] xfce-polkit is now executed from here 
![image](https://github.com/archcraft-os/archcraft/assets/85928597/c124f456-abba-4017-bd47-861e0808a486)

I just commented out these lines in openbox/autostart. 
![image](https://github.com/archcraft-os/archcraft/assets/85928597/530a2f65-e196-4c3d-9bb1-91a3948e30fc)

**Comment by irrefl** [comment]
╭─    ~/.config/openbox ▓▒░────────────────────░▒▓ ✔    at 01:55:28   ─╮
╰─ sudo systemctl disable polkit.service   

╭─    ~ ▓▒░────────────────────────────────────────░▒▓ ✔  at 01:53:23   ─╮
╰─ cd ~/.config/openbox                                                        ─╯

╭─    ~/.config/openbox ▓▒░────────────────────────░▒▓ ✔  at 01:53:37   ─╮
╰─ nvim autostart                                                              ─╯

=> comment these lines: 
```
#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

## Kill if already running
killall -9 xfsettingsd picom polybar mpd dunst ksuperkey xfce4-power-manager

## Restore Wallpaper
nitrogen --restore

## xfce4-settings daemon
xfsettingsd &

**## polkit agent
#if [[ ! `pidof xfce-polkit` ]]; then
#	/usr/lib/xfce-polkit/xfce-polkit &
#fi**

```
