### ISSUE TITLE
Kdenlive and Inkscape (and maybe GIMP) triggering Plymouth Black Screen???

### ISSUE THREAD

**Issue by psygo** [archcraft-os/archcraft#375]
Ever since some updates ago (< 1month ago), for some reason, every time I'm using either Kdenlive or Inkscape (or maybe GIMP), when I press the mod key (windows key on my keyboard), I get this black screen:

![archcraft black screen](https://github.com/archcraft-os/archcraft/assets/11823725/24b0db93-4856-467e-bd2f-75945dc007e2)

And I think it's a 50-50 thing to get a 100% black screen, in which the PC is still on. When the black screen has the text on screen, if I click enter, my PC shuts down.

I have no idea why this is happening or what *exactly* triggers all this, but it's extremely annoying, as it has already happened dozens of times.

**Comment by adi1090x** [comment]
using all three on my laptop, No such issue there EVER.

Something else must has causing this.

![Screenshot_2024-01-07-11-04-59_1920x1080](https://github.com/archcraft-os/archcraft/assets/26059688/1cbcf048-a621-43bf-a19e-202b6a727917)
