### ISSUE TITLE
Nodejs error ,npm error

### ISSUE THREAD

**Issue by tonmoy998** [archcraft-os/archcraft#376]
I am learning linux os.I was testing neovim .While installing meson ,I found error

![2023-08-14T21:37:07,181865833+06:00](https://github.com/archcraft-os/archcraft/assets/74363531/5b5dd376-7109-4161-850e-678e2c5eab14)

**Comment by neiesc** [comment]
@tonmoy998 try update all package https://wiki.archcraft.io/docs/install-archcraft/post-install#update-system

**Comment by adi1090x** [comment]
Update your entire system with `sudo pacman -Syyu`

This is not really an Archcraft specific issue.
