### ISSUE TITLE
Password at sudo is denied even with the correct credentials

### ISSUE THREAD

**Issue by TauqeerAhmad5201** [archcraft-os/archcraft#377]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
>**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x ] I am using the [latest version](https://github.com/archcraft-os/releases/releases)
- [ x ] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository

# Detailed Description

The time I am entering my password at the sudo request, it shows that password is wrong. I've duly cross checked my password, and it's correct. Since the time I reboot and tries to login, the same password works perfectly. I've also checked that I am entering the password of the matched user. Also, I am a single user in the system. 

# Expected Behavior

The sudo request should be working perfectly after I enter my password which is correct. 

# Current Behavior

It is denying the correct password but a restart fixes it. 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Try to execute the command using sudo. 
2. Enter the password. 
3. The password will be denied. 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version: archcraft-2023.07.05-x86_64.iso
* System Specs: intel i5-11th Gen 
* Graphics Card: NVIDIA RTX 3050
* Etc

**Comment by adi1090x** [comment]
If you enter you password wrong for three times continuously (accidentally, due to  caps lock is on or anything) you get into lock-mode for 10 minutes. Remember that.
