### ISSUE TITLE
DNS doesnt work  

### ISSUE THREAD

**Issue by Banana021s** [archcraft-os/archcraft#381]
i have an issue about network in archcraft these days

i change my dns in `/etc/resolve.conf`
like this:
` nameserver 178.22.122.100`
`nameserver 185.51.200.2 `

idk it's cuz of dns that i use or the issue of archcraft

**Comment by adi1090x** [comment]
Seems like no issue here.

![Screenshot_2024-01-07-10-59-00_1920x1080](https://github.com/archcraft-os/archcraft/assets/26059688/7cad7398-e5f7-42b6-bd53-df81ae7c3942)
