### ISSUE TITLE
Screenshots represent the past state of the display

### ISSUE THREAD

**Issue by ISduoppoti** [archcraft-os/archcraft#384]
- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases)  +
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer +
- [x] I checked to make sure that this issue has not already been filed +
- [x] I'm reporting the issue to the correct repository (mb)

# Failure Information (for bugs)

I am new into archcraft(and Linux too). When I want to take a screenshot (openbox) I press button (prt sc) and Lets imagine I have 4:34 pm right now, but screenshot about 2:20 pm(i can see it on the top where the time)
Therefore, i downloaded ksnip, open an Firefox browser, then tried to take screenshot with it, but I see only my wallpaper, there no Firefox, menubars.
Oh, right now I am getting screenshots with a bit transparent LockScreen, i will add images
It seems that it takes screenshot from past, and it remembers my screen?

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version:   archcraft-2023.10.12-x86_64-001.iso
* I am using dual boot(Windows 11 + archcraft)
* Graphics Card: GeForce RTX 3060 Mobile / Max-Q
* Intel i7-12700
*Samsung ssd 512(for archcraft 54 gb)

## Failure Logs

My actual screen:

![IMG_20231112_164853](https://github.com/archcraft-os/archcraft/assets/105210780/653da6c9-601a-4ceb-8353-1c524ade8dff)

My screenshot:
![Screenshot_2023-11-12-16-49-21_1920x1080](https://github.com/archcraft-os/archcraft/assets/105210780/76b670df-a443-40ca-9728-fd4033a0895a)

BTW on this screenshot we can see time 04:10 pm and what I was doing at that time

And one more screenshot that i captured at 05:36 pm
But time on screenshot is not 5:36

![Screenshot_2023-11-12-17-33-52_1920x1080](https://github.com/archcraft-os/archcraft/assets/105210780/d1f10ab8-f811-4bc8-a7f6-7cfd25ad78df)

Also I see that its the same when i captured at 4:25, mb this screen saves somewhere and that system using it?

Dont know what else to write, if smt is needed, I'll answer

**Comment by adi1090x** [comment]
That's is  the weirdest issue NO ONE has ever reported.

**Comment by adi1090x** [comment]
Check your locale and hardware clock, sync them if not in sync. if dualbooting, fix the clock issue.
