### ISSUE TITLE
Polybar issue

### ISSUE THREAD

**Issue by evaapinaa** [archcraft-os/archcraft#385]
![Screenshot_2023-12-04-02-12-09_1920x1080](https://github.com/archcraft-os/archcraft/assets/116506327/8922bd87-d92b-4a51-819e-05d793848877)

I bought bspwm premium and just installed it today, I have problems with some lines that appear in the polybar of the everforest theme (and I used random to match the background).
I do not know if in the photo they are well appreciated, but they are the lines that appear in the backgrounds of the emoticons. The square shadow of the background of the polybar doesn't bother me either, but it would be good to solve it.

I would like that somebody could tell me how to fix these lines of the polybar. I am new in all this and I don't know what can be causing the problem.

![Screenshot_2023-12-04-02-12-09_1920x1080](https://github.com/archcraft-os/archcraft/assets/116506327/2ec821dc-faf4-4f4c-9686-7c339f4ab3c6)

**Comment by adi1090x** [comment]
This has been fixed and `bspwm premium` has been updated on JAN 1st, get the updated pkg (for free) from ko-fi and install the new configs.
