### ISSUE TITLE
/boot/efi gets mounted before /boot in the ABIF installer

### ISSUE THREAD

**Issue by vaygr** [archcraft-os/archcraft#386]
# Detailed Description

`/boot/efi` gets mounted before `/boot` if you choose to have `/boot` as a separate partition.

# Expected Behavior

`/boot/efi` mounting should be postponed until all other partitions are mounted.

# Current Behavior

`/boot/efi` gets mounted before `/boot`, which then masks `/boot/efi` location.

# Failure Information (for bugs)

--//--

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

https://wiki.archcraft.io/docs/install-archcraft/install-with-abif#mount-partitions

## Context

* ISO Version: 2023.10.12

## Failure Logs

N/A

**Comment by adi1090x** [comment]
Yes, It's a limitation of ABIF. It's recommended that you use only `/boot` as mount-point and not `/boot/efi`

**Comment by vaygr** [comment]
@adi1090x why not do the same thing as Manjaro Architect does (mounting efi partition the last)?
