### ISSUE TITLE
Styles disappear

### ISSUE THREAD

**Issue by DashD87** [archcraft-os/archcraft#387]
![Screenshot_2023-12-22-10-16-19_1360x768](https://github.com/archcraft-os/archcraft/assets/23029194/75af1ce7-c67a-493a-81c3-6f5f5ec071e3)
Hello!

I us Archcraft with openbox. When I try change the style in menu the stíles not showing.

**Comment by adi1090x** [comment]
Make sure the directory `~/.config/openbox/themes/` exist. If not, re-install `archcraft-openbox` and use new configs.
