### ISSUE TITLE
Alacritty TOML Config Files

### ISSUE THREAD

**Issue by Wiian16** [archcraft-os/archcraft#388]
# Detailed Description

Recently when opening the alacritty terminal, a warning message has appeared about migrating current YAML config files to TOML. Alacritty has provided a tool to convert your config files, but it does not go into the folders for each wm. After running `alacritty migrate`, I still have a warning about my config file. Alacritty has said that they will be dropping support for YAML files soon, as they don't want to maintain support for both.  

# Feature request

I do not yet have a good understanding of either YAML or TOML, so I don't know how to translate between the two. On top of that, Archcraft adds some complexity by changing theme colors with your background. I would like to either have a tool to convert these files for me, or perhaps there could be new config files provided here.

**Comment by MrShelbySann** [comment]
To fix this, here is what I did until the developer does something:

- Copy the  `~/.config/wayfire/alacritty` folder to .config (so it would be located at `~/.config/alacritty)`
- Run `alacritty migrate`, which will migrate the .yml files to .toml
- Move the .toml files under `~/.config/alacritty` back to `~/.config/wayfire/alacritty`
- Now, opening alacritty should warn you about `history` and `manifest`
- In `~/.config/wayfire/alacritty/alacritty.toml`, remove or comment out the lines that start with `history` and `manifest`, then save the file

You should be good to go, however, the window doesn't seem to respect the line where the window size is declared (at least on Wayfire it doesn't, it just bugs out the window decoration).

Hope it helps!

**Comment by adi1090x** [comment]
Already updated everything, you can get the wayfire update from ko-fi for free. 

New alacritty version has some issue with geometry on floating windows in (some) wayland compositors (like sway and wayfire) To solve this, just edit the config file (`~/.config/wayfire/alacritty/alacritty.toml`) and comment out these lines:
```toml
[window.dimensions]
columns = 82
lines = 24
```

A PR fixing this issue has been merged to alacritty, wait for the new alacritty update.
