### ISSUE TITLE
Apply to current stock Arch linux.

### ISSUE THREAD

**Issue by grandfso** [archcraft-os/archcraft#39]
Would it be difficult / possible to apply Archcraft theming and tooling customizations to stock install of Arch 64bit? If possible, will you consider a short how-to instrucitons on how to follow through with that?

**Comment by devtechcorp** [comment]
Pal in the README https://github.com/archcraft-os/archcraft#get-the-iso read from 2.

**Comment by adi1090x** [comment]
Well, not really that hard, just clone the repository and copy paste everything from `iso/airootfs/etc/skel` dir to your `home` dir. install the required packages listen in the `packages.x86_64` file. you must at least know how to configure stuff.
