### ISSUE TITLE
USB Boot causes blank screen

### ISSUE THREAD

**Issue by AidanTheBandit** [archcraft-os/archcraft#390]
- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Detailed Description
Selecting USB in boot menu doesn't work. This was tested with 2 drives

# Expected Behavior

Load archcraft installer

# Current Behavior

Clicking the USB drive in the boot menu causes the screen just refresh

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Spam F11 on your keyboard to open the boot menu
2. Select the USB drive with the Archcraft iso flashed onto it

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version: archcraft-2023.10.12-x86_64
* System Specs: AMD Ryzen 5 5600x, Nvidia GeForce RTX 3060, ASRock X570 Taichi, 2 G.Skill 8GB DDR4 Ram
* Graphics Card: Nvidia RTX 3060
Video: https://media.barkle.chat/bk_/f9edf9d6-07c4-48f1-be02-6f1437901465.mp4

## Failure Logs
None

**Comment by adi1090x** [comment]
Boot the ISO by turning off `secure boot` in your BIOS. Re-open if needed.
