### ISSUE TITLE
Issue with Alacritty terminal

### ISSUE THREAD

**Issue by 1llyaa** [archcraft-os/archcraft#392]
Hello, I got problem with terminal. After doing yay -Syu --devel my terminal wont work as it worked. After updating everything when I press win + t terminal wont open full screen and I get this warn message: 
![image](https://github.com/archcraft-os/archcraft/assets/114167638/bb40c458-2fde-4866-98f0-99df8c6ebcda)

When I open log there are 2 lines:
[0.000269480s] [WARN ] [alacritty_config_derive] Unused config key: history
[0.000311858s] [WARN ] [alacritty_config_derive] Unused config key: multiplier

Is there any way of fixing it? 
I tried to find everywhere but I found nothing.

I apologize if my question is stupid but Im pretty new in arch linux community.

**Comment by Rooyca** [comment]
Did you try removing or commenting those keys from your `alacrity.toml`?

**Comment by 1llyaa** [comment]
Yes, it worked. Sorry for replying late.
