### ISSUE TITLE
Can i speek to you in portuguese?

### ISSUE THREAD

**Issue by irlm1801** [archcraft-os/archcraft#393]
Boa tarde,
Estou a utilizar o Archcraft XFCE 120124 e tenho bugs a reportar que são:
1. quando abro um ficheiro, ele não abre com o pacote flatpak,
2. quando removo/copio uma pasta, o Thunar fecha sozinho,
3. porque o SSD está sempre a ler/escrever no meu portátil, noto que a leitura do disco constante com esta distribuição baseada em Arch.
De resto acho que é uma distribuição fantástica, parabéns e continue a suportá-la por muito tempo, fico agradecido por uma resposta a estes bugs.
Ivo Magalhães

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
>**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am using the [latest version](https://github.com/archcraft-os/releases/releases)
- [x] I checked the [documentation](https://wiki.archcraft.io) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Detailed Description

Please describe the issue in detail

# Feature request

If this is just a feature request, please remove the rest of this template.

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
5. step 2
6. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* ISO Version:
* System Specs:
* Graphics Card:
* Etc

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by irlm1801** [comment]
Why you not respond me about this bug?

**Comment by adi1090x** [comment]
Because i don't understand the language.

**Comment by irlm1801** [comment]
translate
