### ISSUE TITLE
Problem running arch craft on notebook with amd gpu

### ISSUE THREAD

**Issue by 1llyaa** [archcraft-os/archcraft#398]
I get screen tearing even in install screen. I tried to do everything but nothing works. Any suggestions?![image](https://github.com/archcraft-os/archcraft/assets/114167638/cb2ea44d-b7bc-4765-90ef-f962f2052038)

**Comment by 1llyaa** [comment]
I forgot to mention that I have AMD graphics card. Is it problem for archcraft?

**Comment by adi1090x** [comment]
Archcraft should work fine on AMD machines. My own laptop have AMD and it runs perfectly fine.
```
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
```

Try disabling the compositor (picom) or use the **glx** backend.

More [Here](https://wiki.archlinux.org/title/AMDGPU)
