### ISSUE TITLE
Network drivers not working (broadcom-wl)

### ISSUE THREAD

**Issue by jpoCruz** [archcraft-os/archcraft#4]
Huge amount of trouble when trying to install the correct drivers for my network card. Without them, there is no wireless connection. You can see everything I have tried on this reddit thread: https://www.reddit.com/r/archlinux/comments/hw1k9k/installing_different_network_drivers_broadcomwl/

Thank you.

**Comment by raunaktr** [comment]
Maybe broadcom-wl / broadcom-wl-dkms is not included in base install of this ISO. I would suggest you to install `broadcom-wl` via pacstrap or while you're in the chroot at the time of the installation. Make sure to use `wpa_supplicant` to connect to the internet and install broadcom-wl package while in chroot.

**Comment by adi1090x** [comment]
`broadcom-wl` is installed on this ISO, not sure why it's not working on your system. you've said that you faced this issue on other distros as well.

**Comment by Heliferepo** [comment]
I have a broadcom card I don't know what could be the issue but have you tried to use nmcli ?
This was the only thing that was working for me wifi-menu and all did not work
`nmcli connect wifi connect "$YOUBOX" password "$BOXPASSWORD"`

**Comment by adi1090x** [comment]
is this issue resolved?

**Comment by jpoCruz** [comment]
I am not sure. After a couple of days trying to solve the issue, I ended up distro hopping. I'll mark this as closed, since it is most likely a problem on my machine. Thank you.
