### ISSUE TITLE
Issue trying to encrypt home partition

### ISSUE THREAD

**Issue by ricardascubukinas** [archcraft-os/archcraft#40]
I've created 3 partitions boot, root with swap-file as well as home. I've encrypted the root and home partition with LUKS automatic encryption, the installation went fine, didn't change any configurations, then when I try to decrypt my data the loading bar just keeps rolling.
Creating boot and root partition with swap file and encrypting it works fine.

**Comment by adi1090x** [comment]
I think this will help : https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_a_non-root_file_system
