### ISSUE TITLE
Installer doesn't mkconfig for grub

### ISSUE THREAD

**Issue by ricardascubukinas** [archcraft-os/archcraft#41]
When you edit configs of installed system and edit grub/syslinux/systemd-boot, the changes are saved to the file although grub is not updated since the grub.cfg isn't regenerated using the new configuration.

grub-mkconfig has to be ran if the user edits grub/syslinux/systemd-boot or inform the user during installation that if he decides to edit the grub configuration that he has to run this command manually when he boots to initialize the grub changes he made via generating a new grub.cfg using:

`grub-mkconfig -o /boot/grub/grub.cfg`

**Comment by adi1090x** [comment]
Installer does that already. If you edit the file after installation, you've to for sure, update the config manually.
