### ISSUE TITLE
Live USB desktop freeze.

### ISSUE THREAD

**Issue by mrneilypops** [archcraft-os/archcraft#42]
HI,
I have booted my live USB and logged into the desktop but after maybe 1 minute the desktop freezes and I have to hard reboot. Any ideas on this before I try an install?

**Comment by Khosraw** [comment]
> HI,
> I have booted my live USB and logged into the desktop but after maybe 1 minute the desktop freezes and I have to hard reboot. Any ideas on this before I try an install?

I had this issue too but it happened after I installed it and wanted to reboot the system.

**Comment by adi1090x** [comment]
Fixed.
