### ISSUE TITLE
Window or Alt+F1 not working

### ISSUE THREAD

**Issue by pen-temp** [archcraft-os/archcraft#43]
Hello, 
i tested the latest Version archcraft-2020.09.01-x86_64.iso in 2 Vms and on one Notebook(HP Elitebook 8760w) and the laucher will not come after booting in live mode i can switch to another terminal everything seems working fine but i can press Window or Alt+F1 and nothing happends.

Thanks for help.

**Comment by cynman** [comment]
^ Confirmed.

**Comment by matthewwalk** [comment]
Also having this issue, did either of you find a workaround?

**Comment by joshg253** [comment]
Seeing the same in VirtualBox 6.1.14: after login, just an empty wallpaper screen. Cannot open menu to do anything.
Ctrl-Alt-F* _does_ switch between terminals, so it's not locked up, but almost seems that way.
Tried each of the Graphics Controller settings in Vbox, no change.

**Comment by joshg253** [comment]
Booted to the ISO bare metal on my laptop and instead get this glorious screen:
![20201001_215243](https://user-images.githubusercontent.com/297115/94889497-3db34700-0431-11eb-972b-efb43e6e6308.jpg)
(though much less blue in person)

**Comment by joshg253** [comment]
Still occurring with the latest (Oct 2) media.

**Comment by rkedjk** [comment]
Got this problem and solved it. Restarting display manager on other tty helped. Just run this -

`sudo systemctl restart service display-manager`

And everything works fine, except "Getting started" app. It needs to run manually from rofi.

**Comment by SDAChess** [comment]
Same problem on my end, a quick fix I had was to install nvidia drivers, exit the screen and open a tty. And regenerating a Xorg config with nvidia-xconfig and it works like a charm. Need to fix this in future releases though

**Comment by project11x** [comment]
> Got this problem and solved it. Restarting display manager on other tty helped. Just run this -
> 
> `sudo systemctl restart service display-manager`
> 
> And everything works fine, except "Getting started" app. It needs to run manually from rofi.
> 
> Upd: Same problem after installation, needs to restart display manager every time
> 
> UPD2: Also don't happen when starting bspwm instead of openbox

how do I open terminal if i see nothing?

**Comment by MrMini1025** [comment]
> 
> 
> Same problem on my end, a quick fix I had was to install nvidia drivers, exit the screen and open a tty. And regenerating a Xorg config with nvidia-xconfig and it works like a charm. Need to fix this in future releases though

Can you describe step by step?

**Comment by joshg253** [comment]
Looks like this and the other issues are all actually dupes of #37, which has some interesting workaround comments in there, but was closed without any indication if they worked.

> > Change WM to bspwm.
> 
> and comment the line exec compton -b & in ~/.config/openbox/autostart
> Logout, and you can reconnect with Openbox

**Comment by adi1090x** [comment]
Fixed.
