### ISSUE TITLE
Bad Pacman Repos & Yay Build Fails

### ISSUE THREAD

**Issue by Khosraw** [archcraft-os/archcraft#44]
I am running the current latest build of Archcraft Linux and I installed it previously as well. I have having a huge issue with the Repos. Many times pacman can't find simple things like SnapD or programs that are listed in the official repos. 

Even when I try installing them through Yay, many dependencies are not found and it fails to build. I can't find a reason for this and running `sudo pacman -Sy` a bunch did not solve anything. I want to be able to have this fixed and use Archcraft normally. Otherwise I would conclude Archcraft as a distro with design but no function.
![Screenshot_2020-09-14-06_1346x686](https://user-images.githubusercontent.com/53713571/93157907-c2336500-f6d0-11ea-9569-3c869f842ec4.png)

**Comment by Heliferepo** [comment]
Have you tried before `pacman -Syyu` ?

**Comment by Khosraw** [comment]
> Have you tried before `pacman -Syyu` ?

idk if that will help in any way. I uninstalled Arch Craft now since its package issues were annoying.
