### ISSUE TITLE
Installation Medium freezed

### ISSUE THREAD

**Issue by TeoConan** [archcraft-os/archcraft#45]
Hello, I tried archcraft on a live USB stick but my computer got freezed at every boots.

_Here what I only see_
![image](https://user-images.githubusercontent.com/22664730/93865164-3d46dd80-fcc6-11ea-81bc-9a9646684328.png)

I can access to the TTY and system seems to be normal but I cannot do anything...

If someone have an idea or something...
Thank you !

**Comment by ShreyashVerma01** [comment]
It works for me but whenever i try to install archcraft and say yes to the clone installer the whole systems crashes and hangs. I have to force shut my laptop then try again only to get the same result.

**Comment by joshg253** [comment]
Dupe of #43

**Comment by adi1090x** [comment]
Fixed
