### ISSUE TITLE
Live USB - Infinite Boot - UEFI/Surface Book 2

### ISSUE THREAD

**Issue by MikeMaclennan** [archcraft-os/archcraft#46]
When trying to boot to a Live USB, the boot animation (with the Archcraft logo), lasts forever. I only notice this issue on my laptop which is a Surface Book 2 using UEFI and do not notice this when using my Desktop which uses BIOS. Is there some way to troubleshoot why it would not be working.

I tried having a look around for help but didn't see anything, so sorry if it's a silly question.

**Comment by vortex74** [comment]
I'm stuck with this logo right now too.

**Comment by ELG-Icefish** [comment]
Same for me on my pc
(Uefi)

**Comment by thiagomeireless** [comment]
Did you guys manage to solve this?

**Comment by MikeMaclennan** [comment]
No luck so far, although I will admit to not trying so actively.

**Comment by SDAChess** [comment]
It happened to me while make the USB with Rufus on Windows, try to use Rufus and use write as GTP partition and DD image in parameters, fixed the issue for me

**Comment by MikeMaclennan** [comment]
> It happened to me while make the USB with Rufus on Windows, try to use Rufus and use write as GTP partition and DD image in parameters, fixed the issue for me

Worked for me, I naively assumed I could use Rufus as usual. Thanks.
