### ISSUE TITLE
Unable to run Mkinitcpio

### ISSUE THREAD

**Issue by TheLickIn13Keys** [archcraft-os/archcraft#49]
![IMG_20201005_223649](https://user-images.githubusercontent.com/54650080/95163037-df9da100-075b-11eb-9966-7bd9d12b55df.jpg)
Every time I try installing Archraft I get this error when I want to run mkinitcpio.
I tried the tradition archlinux ways of fixing this, but none of them worked.
I followed the install guide for UEFI (my system is UEFI) verbatim but still no luck.

**Comment by adi1090x** [comment]
Try again with new ISO, i hope it's fixed.
