### ISSUE TITLE
Installation fails to boot after upgrading via Pacman

### ISSUE THREAD

**Issue by rsarvar1a** [archcraft-os/archcraft#50]
Totally fresh install, with the exception of having added Win10 to grub; booted completely fine before updating via pacman. 
```
sudo pacman -Syy
sudo pacman - Syu
```
No errors of any kind reported from the above. Upon restarting, booting into archcraft results in a black screen, and everything is totally unresponsive.

**Comment by michaeldrouin** [comment]
i'm having this same exact issue. i noticed you closed the issue yourself. how did you resolve it?
