### ISSUE TITLE
Option to style QT apps?

### ISSUE THREAD

**Issue by nigelwarning** [archcraft-os/archcraft#55]
So,

I tried Openbox in a VM. I love the Manhattan theme, is it possible to let QT apps also use the Manhattan Theme?
I normally use kvantum-qt5, but there is no option for that.

Greetings!

**Comment by adi1090x** [comment]
These are just openbox themes, there's no way yet to style the qt apps.

**Comment by Tsubajashi** [comment]
Hi! Sorry to necro this, but does it work nowadays or is the situation the same?
