### ISSUE TITLE
Does not work in VirtualBox without a drive

### ISSUE THREAD

**Issue by infinitygamer404** [archcraft-os/archcraft#58]
When booting into archcraft live USB without a drive attached in the VM, it doesn't show a desktop at all
It just shows a wallpaper and nothing else
Right clicking and trying key combos also doesn't work
![image](https://user-images.githubusercontent.com/59830101/101984610-c27dd500-3cac-11eb-8c51-354fc1bd3db3.png)

**Comment by joshg253** [comment]
Duplicate of #43
