### ISSUE TITLE
Can't make ISO...

### ISSUE THREAD

**Issue by novousernx** [archcraft-os/archcraft#59]
I try to remake ISO with updated packages but... I have this error...

[mkarchiso] WARNING: build.sh scripts are deprecated! Please use mkarchiso directly.

[mkarchiso] INFO: Reading profile...
[mkarchiso] INFO: Validating 'bios.syslinux.mbr': 'memtest86+' is not in the package list. Memmory testing will not be available from syslinux.
[mkarchiso] INFO: Validating 'bios.syslinux.eltorito': 'memtest86+' is not in the package list. Memmory testing will not be available from syslinux.
[mkarchiso] INFO: Done!
[mkarchiso] INFO: Setting overrides...
[mkarchiso] INFO: Done!
[mkarchiso] INFO: mkarchiso configuration settings
[mkarchiso] INFO:              Architecture:   x86_64
[mkarchiso] INFO:         Working directory:   work
[mkarchiso] INFO:    Installation directory:   arch
[mkarchiso] INFO:                Build date:   2020-12-06T20:01:29+00:00
[mkarchiso] INFO:          Output directory:   out
[mkarchiso] INFO:                   GPG key:   None
[mkarchiso] INFO:                   Profile:   /home/master/archcraft/archcraft/iso
[mkarchiso] INFO: Pacman configuration file:   /home/master/archcraft/archcraft/iso/pacman.conf
[mkarchiso] INFO:           Image file name:   archcraft-2020.12.07-x86_64.iso
[mkarchiso] INFO:          ISO volume label:   archcraft_202012
[mkarchiso] INFO:             ISO publisher:   Aditya Shakya <http://www.github.com/adi1090x>
[mkarchiso] INFO:           ISO application:   Yet another minimal linux distribution, based on Arch Linux.
[mkarchiso] INFO:                Boot modes:   bios.syslinux.mbr bios.syslinux.eltorito uefi-x64.systemd-boot.esp uefi-x64.systemd-boot.eltorito
[mkarchiso] INFO:                  Packages:   amd-ucode arch-install-scripts b43-fwcutter base base-devel bind-tools broadcom-wl btrfs-progs clonezilla crda darkhttpd ddrescue dhclient dhcpcd diffutils dialog dmraid dnsmasq dnsutils dosfstools edk2-shell efibootmgr ethtool exfatprogs f2fs-tools fsarchiver gnu-netcat gpm gptfdisk haveged hdparm intel-ucode ipw2100-fw ipw2200-fw irssi iwd jfsutils kitty-terminfo lftp linux linux-atm linux-firmware lsscsi lvm2 lynx man-db man-pages mc mdadm mkinitcpio mkinitcpio-archiso mkinitcpio-nfs-utils mtools nano nbd ndisc6 nfs-utils nilfs-utils nmap ntfs-3g nvme-cli ntp openconnect openssh openvpn partclone parted partimage ppp pptpclient reflector reiserfsprogs rp-pppoe rsync rxvt-unicode-terminfo sdparm sg3_utils smartmontools sudo syslinux systemd-resolvconf tcpdump terminus-font termite-terminfo testdisk usb_modeswitch usbutils vim vpnc wireless-regdb wireless_tools wpa_supplicant wvdial xfsprogs xl2tpd zsh xorg-server xorg-xbacklight xorg-fonts-misc xorg-xfd xorg-xkill xorg-xrandr xorg-xrdb xorg-xinput xf86-input-libinput xf86-video-fbdev xf86-video-vesa xf86-video-intel xf86-video-amdgpu xf86-video-ati xf86-video-nouveau nvidia networkmanager nm-connection-editor networkmanager-openvpn obconf openbox adapta-gtk-theme bspwm sxhkd arc-gtk-theme arc-icon-theme alsa-plugins alsa-tools alsa-utils atril autoconf automake binutils bison bmon calc dunst fakeroot feh ffmpeg ffmpegthumbnailer gcc geany geany-plugins gparted gst-libav gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly gtk-engine-murrine gvfs gvfs-mtp htop imagemagick inetutils jq leafpad lxappearance lxdm-gtk3 make midori mpc mpd mplayer ncdu ncmpcpp nitrogen noto-fonts os-prober p7zip patch pcmanfm pkg-config plank polkit pulseaudio pulseaudio-alsa pulseaudio-equalizer-ladspa pavucontrol pv ranger scrot termite terminus-font-otb thunar thunar-archive-plugin thunar-media-tags-plugin thunar-volman ttf-dejavu tumbler udisks2 unrar unzip viewnior vim wget xarchiver xclip xdg-user-dirs xfce4-power-manager xfce4-settings xmlstarlet yad zip virtualbox-guest-dkms virtualbox-guest-utils linux-headers ac-about-dev ac-fonts ac-get-started ac-grid-icon-theme ac-gtk-themepack ac-hybrid-icon-theme ac-lxdm-theme ac-pixmaps ac-wallpapers betterlockscreen colorpicker compton-tryone-git grub-silent ksuperkey networkmanager-dmenu-git obmenu-generator perl-linux-desktopfiles plymouth polybar rofi-git yay cava downgrade pyroom toilet tty-clock unimatrix-git
[mkarchiso] INFO: Copying /etc/skel/* to user homes...
[mkarchiso] ERROR: Failed to set permissions on 'work/x86_64/airootfs/home/liveuser'. Outside of valid path.

**Comment by adi1090x** [comment]
Are you trying to build the ISO using Archcraft live ISO?

**Comment by novousernx** [comment]
Yes.

**Comment by novousernx** [comment]
And with another Arch Linux installation.
