### ISSUE TITLE
Polybar missing icons apart from the default style.

### ISSUE THREAD

**Issue by mrlkn** [archcraft-os/archcraft#60]
Hi,

I made a fresh install to my desktop. After making updates polybars icons are gone for all the styles but default. Tried to reinstall fonts (waffle and terminus) but it didnt work.

output of the polybar launch.sh
```
warn: Dropping unmatched character  (U+e205)
warn: Dropping unmatched character  (U+e097)
warn: Dropping unmatched character  (U+e09a)
warn: Dropping unmatched character  (U+e09d)
warn: Dropping unmatched character  (U+e017)
warn: Dropping unmatched character  (U+e220)
warn: Dropping unmatched character  (U+e2d0)
warn: Dropping unmatched character  (U+e203)
warn: Dropping unmatched character  (U+e312)
```

fyi: I had a problem with desktop environment after fresh install because of Nvidia graphics card installing `xorg-server` fixed my issue.

**Comment by adi1090x** [comment]
Please try the new ISO.
