### ISSUE TITLE
Infinite archcraft logo after install (Dell Inspiron 5502 UEFI)

### ISSUE THREAD

**Issue by Avni2000** [archcraft-os/archcraft#63]
This is a known issue and the one that had it last solved it by using a couple rufus modifications. The same didn't work for me, unfortunately, and it boots infinitely when choosing archcraft at grub.

**Comment by Daemitrious** [comment]
@Avni2000   I developed this by messing with the config file after pressing `e` when at the Archcraft grub bootup screen.  Maybe look around in there.  I wouldn't reccomend, but you could try modifying the default shell by appending `init=/bin/sh` to the `linux` line.

**Comment by Avni2000** [comment]
I'll be sure to try it when i get the time!

**Comment by adi1090x** [comment]
Try New ISO, Reopen if the issue still exist.
