### ISSUE TITLE
auto resizing does not work of virtualbox

### ISSUE THREAD

**Issue by subhajit-halder** [archcraft-os/archcraft#64]
This is an arch issue in general, autoresizing of the window would not work with default virtualbox settings

To fix it : 

setting -> display -> graphics controller -> VBoxVGA 

resolve the issue 

source : https://bbs.archlinux.org/viewtopic.php?pid=1827885#p1827885

**Comment by adi1090x** [comment]
Archcraft ISO has everything needed to run it properly in Virtualbox.
You have to use another controller for auto resizing, as it's a Arch thing.

You can also set the EFI resolution.
