### ISSUE TITLE
Add CJK fonts and input methods

### ISSUE THREAD

**Issue by ClSlaid** [archcraft-os/archcraft#66]
As one who live in east asia area, it's neccesary to have fonts and input methods that support CJK (A.K.A. Chinese Japanese Korean) characters.
Configuring fonts and input method is quite boring and time-consuming. If preclude CJK font and input method frameworks it'll be more friendly for east asian users.

**Comment by adi1090x** [comment]
Can be installed explicitly.

**Comment by ClSlaid** [comment]
> Can be installed explicitly.
Though could be installed explicitly, if the distro set locale to East Asia countries and areas on installation, local language characters will be displayed as squares. I still suggest including CJK-fonts in your distro.
Chinese Version:
□□□□□□□, □□,□□□□□□□□□(□□/□□),□□□□□□"□"□□□□. □□,□□□□□□.

**Comment by Hynes1154** [comment]
Waiting for this to be added yet.

**Comment by geekyBoogiepop** [comment]
I'm still experiencing this issue. I couldn't read Japanese websites because the fonts didn't render properly, I had to install noto-fonts-cjk package and restart my browser. Please fix it in your next release! 🙏
