### ISSUE TITLE
The OS hangs randomly and the only way out is forced hardware reset

### ISSUE THREAD

**Issue by Vedaant-Rajoo** [archcraft-os/archcraft#68]
I came across this issue recently. After upgrading to the latest version, my operating system hangs randomly and the only way to get it working is to hard reset it. It is kind of annoying when this happens in the middle of a meeting. 

Is it just for me, or are other people experiencing this too.

I'll update this issue further when I get more information, the next time it hangs.

**Comment by YannickSpoerl** [comment]
+1
I often use a heavy IDE, so I thought it had to to with my RAM at first. Turns out it also happens when barely doing anything,
 just randomly freezes, videos or music keeps playing. Need force shutdown entire system.

**Comment by M0hammedImran** [comment]
It's been happening to me as well, I thought it was something to do with bspwm. but its happening on openbox as well

**Comment by Vedaant-Rajoo** [comment]
The biggest issue for the developers is that there is no way to debug the logs since the OS completely shuts down and the only way is to force restart. But based on the above comments I can safely assume that it is in fact random and is caused by the system libraries and not the usr libraries.

**Comment by RafayGhafoor** [comment]
disabling bspcomp (picom) fixed it for me.

**Comment by adi1090x** [comment]
It's Fixed. Try New ISO, Reopen if the issue still exist.
