### ISSUE TITLE
Can't build the iso

### ISSUE THREAD

**Issue by Heliferepo** [archcraft-os/archcraft#7]
I managed to run perfectly setup.sh but then comes the time of build.sh
It fails and tell me : `failed to install packages to new root`

Is there a way to fix this did I broke anything ?

**Comment by adi1090x** [comment]
did you run `build.sh` as root?

**Comment by Heliferepo** [comment]
yes I used `sudo su` before running `build.sh`

**Comment by adi1090x** [comment]
okay, pls update your system first (Are you using arch or Archcraft). follow each step, clear pacman cache, then try again. Make sure all the AUR packages are build successfully & available inside `localrepo/x86_64`

**Comment by Heliferepo** [comment]
Hello again so i FINALLY managed to build the iso so I was using archcraft and I had some issues first of all setup.sh need to have bison ruby-ronn doxygen uncrustify cppcheck to function for me then

I needed also to import my self `/usr/share/edk2-shell/x64/Shell_Full.efi` into my system
