### ISSUE TITLE
Getting work/x86_64/airootfs/boot/initramfs-*.img': No such file or directory from building

### ISSUE THREAD

**Issue by thepenguinthatwants** [archcraft-os/archcraft#70]
Hi,
I've tried building this went throught setup.sh and  ran build.sh using root but it stops with this.

install: cannot stat '/home/ninja/archcraft/iso/work/x86_64/airootfs/boot/initramfs-*.img': No such file or directory

Any clue why such behaviour? I am using newly updated system but not sure if it should affect this like this.

**Comment by negativeExponent** [comment]
its incompatible with the latest archiso 51. downgrading to version 47.1 works though.

hope this can be updated to latest mkarchiso.

**Comment by adi1090x** [comment]
Fixed.

**Comment by thepenguinthatwants** [comment]
Nicee
