### ISSUE TITLE
[ Feature ] Torrent link for downloading ISO

### ISSUE THREAD

**Issue by pspiagicw** [archcraft-os/archcraft#72]
I love exploring new distributions , I recently tried ArchCraft , but the most upsetting part was that there is no torrent link for downloading the ISO.
A torrent link provided would make downloading it more convenient for users.
It would also make it more accessible to people with slow internet .

By the way , Great Work! I really enjoyed the experience.Thanks.If I could be of some help  don't hesitate to ask, I love contributing to open source.
I hope you consider the suggestion.

**Comment by adi1090x** [comment]
Let's see what can i do about it, Thanks.
