### ISSUE TITLE
Assigning "Super+Return" in Application Shortcuts in Keyboard [Settings]

### ISSUE THREAD

**Issue by Daemitrious** [archcraft-os/archcraft#74]
I noticed that `"Super+Return"` was defaulted to the `termite` terminal application, so I then installed `konsole`, another terminal application, but when I went to change the original shortcut to open `konsole` instead of `termite` it wasn't there.  I clicked the `Add` button to add the `"Super+Return"` shortcut but when doing so it would open `termite`.

I then tried uninstalling `termite` but would get the following error after using the shortcut:
`Failed to execute child process "termite" (No such file or directory).`

**Comment by YannickSpoerl** [comment]
I have also noticed that most of the xfce-settings applications (such as Keyboard) do not change the underlying system. For keyboard shortcuts there are cleaner (at least for my taste) solutions:

Are you using the _openbox_ or the _bspwm_ version of Archcraft? Use `cat .dmrc` if unsure.

For the _openbox_ version you want to edit .config/openbox/rc.xml. There should be a line looking like this:
```xml
<keybind key="W-Return">
   <action name="Execute">
      <command>termite</command>
   </action>
</keybind>
```
Which you would want to modify to launch konsole instead.

For the _bspwm_ version you want to edit .config/bspwm/bin/bspterm, which by default launches termite:
```sh
if [ "$1" == "-f" ]; then
   termite --class termite-float -c ~/.config/bspwm/termite/config
else
     termite -c ~/.config/bspwm/termite/config
fi
```
