### ISSUE TITLE
Customize Look and Feel - Mouse Cursor

### ISSUE THREAD

**Issue by Daemitrious** [archcraft-os/archcraft#75]
I have the default `Hybrid` mouse cursor option applied but it will only take into affect until after I logout then log back in.  Even after rebooting and logging in I must still relogin for it to change the cursor.

**Comment by AvinashReddy3108** [comment]
[+1] Can confirm this

**Comment by adi1090x** [comment]
Yeah, That's how Openbox works, On the other hand, cursor themes works fine in BSPWM.
