### ISSUE TITLE
Reinstalling Archcraft

### ISSUE THREAD

**Issue by Daemitrious** [archcraft-os/archcraft#76]
I was having a few issues with my original installation of Archcraft, so I decided to reinstall it just like usual.  When I went to boot it back on after shutting it down after finishing the entire installation, it would turn on for half a second that shut right back off.  I spent over an hour trying to figure out what happened but came out clueless.  After I woke up the next morning, I tried booting it back up again, but this time it turned on and I was able to mess with it for about 10 minutes before it stopped working.  The one and only thing I did in this time was perform a system update with the following command:  `sudo pacman -Syuu`.  After this finished, the entire computer froze up, forcing me to force shutdown my laptop (`Compac Presario CQ56`).  And finally after all of this, I attempted to turn it back on, but it would go back to its original issue of turning on for half a second then shutting back off.

**Comment by adi1090x** [comment]
It's probably an issue with graphics driver or with your laptop.

**Comment by adi1090x** [comment]
Try New ISO, Reopen if the issue still exist.

**Comment by Daemitrious** [comment]
bro i did that and my laptop killed itself lmao

**Comment by adi1090x** [comment]
I'm sure Archcraft is not the murderer.
