### ISSUE TITLE
Nerd fonts

### ISSUE THREAD

**Issue by artamonovoleg** [archcraft-os/archcraft#77]
Font in terminal and polybar breaks after install any own nerd font.

**Comment by paarthjuneja** [comment]
Hello, I had the same issue, but doing `sudo pacman -S ac-fonts ac-pixmaps` fixed it.

**Comment by artamonovoleg** [comment]
> Hello, I had the same issue, but doing `sudo pacman -S ac-fonts ac-pixmaps` fixed it.

Hello. Already installed. Reinstalling didn't change anything

**Comment by adi1090x** [comment]
Maybe your font conflicts with already installed nerd fonts. In that case you have to delete the one in system for your font to work properly. You have to change glyphs according to your font.
Basically a mess.
