### ISSUE TITLE
Mouse / touchpad configuration

### ISSUE THREAD

**Issue by RoToRx88** [archcraft-os/archcraft#8]
When using `xfce4-mouse-settings` the settings are not saved and doesn't have any effect of the mouse configuration. I tried editing the conf file manually in `~/.config/xfce4/xfconf/xfce-prechannel-xml/pointers.xml` but it doesn't have any effect either.
It is the same for all the other settings from xfce4, I had to install `arandr` to manage my screen settings.

**Comment by adi1090x** [comment]
that's weird. is it your touch-pad or a mouse?

**Comment by RoToRx88** [comment]
It's my touchpad. I had to install synclient to configure manually the scroll in the right direction.

**Comment by meta-boy** [comment]
In my case, I am not able to enable `tap to click` for the touchpad.

**Comment by adi1090x** [comment]
please install drivers for you touchpad
REF: [Archwiki](https://wiki.archlinux.org/index.php/libinput)
REF: [Archwiki](https://wiki.archlinux.org/index.php/Touchpad_Synaptics)

**Comment by RoToRx88** [comment]
@adi1090x I've gone through this, but it seems wider than just a touchpad issue. If I try to configure my screens with the built-in tool from xfce4 it doesn't work either. I had to install and use `arandr` to have some kind of GUI tool to configure my dual screen.

**Comment by adi1090x** [comment]
Use the latest release, install correctly drivers for your touchpad.
