### ISSUE TITLE
Keybinds for switch beetween workspaces/desktops

### ISSUE THREAD

**Issue by bebetoalves** [archcraft-os/archcraft#80]
Hello!

It's my first time using a window manager distro based, I would like to know how I can make switching between desktops more like Fedora/Ubuntu, for example: CTRL + Shift + Arrows keys to move windows to desktops/workspaces and CTRL + ALT + Arrow keys to switch beetween the desktops/workspaces.

Thank you guys!

**Comment by adi1090x** [comment]
Look at the keybindings here : https://archcraft-os.github.io/features.html
you can change them as you like.
