### ISSUE TITLE
No local network browsing with Thunar

### ISSUE THREAD

**Issue by rlabrach** [archcraft-os/archcraft#81]
Hello and thanks again for ArchCraft, it's a nice Linux distribution.
I want to be able to browse my local network (PC, Mac, NAS...) but when I go into Thunar, the software doesn't see anything in the network. What do I need to enable so that it explores the local network and finds the remote volumes?
thanks

**Comment by rlabrach** [comment]
Hello, me again, any idea to browse local network with Thunar ?
THX

**Comment by adi1090x** [comment]
I've added the functionality to thunar, Try New ISO, Reopen if the issue still exist.

**Comment by rlabrach** [comment]
hey !!! Great new, this new ISO is... GREAT !
THANK YOU SO MUCH

Le jeu. 27 mai 2021 à 06:56, Aditya Shakya ***@***.***> a
écrit :
