### ISSUE TITLE
bspwm and openbox config files

### ISSUE THREAD

**Issue by Mohammadreza99A** [archcraft-os/archcraft#83]
Is there a way to have access to repos that host config files of openbox and bspwm of ArchCraft?

**Comment by CH4ND4N-x** [comment]
> Is there a way to have access to repos that host config files of openbox and bspwm of ArchCraft?

Yes it's there in this repo .
Go to archcraft/iso/airootfs/etc/skel/.config/
Inside it you'll find all the config files
