### ISSUE TITLE
polybar in the forest theme changes to something like in the screenshot 

### ISSUE THREAD

**Issue by Januar71** [archcraft-os/archcraft#84]
polybar in the forest theme changes to something like in the screenshot ,I restarted my laptop, but when it comes back in, it changes like that, please help me
![scrot_2021-05-08-02_1366x768](https://user-images.githubusercontent.com/82145949/117496873-d69ad980-afa1-11eb-9466-1742b5e325d8.png)

**Comment by toricorn** [comment]
There's a `fix_modules.sh` inside the polybar folder in the `.config`, doesn't running that one fix it?

**Comment by Januar71** [comment]
I've run it, but it doesn't work at all

**Comment by Januar71** [comment]
> There's a `fix_modules.sh` inside the polybar folder in the `.config`, doesn't running that one fix it?

I've run it, but it doesn't work at all

**Comment by toricorn** [comment]
> > There's a `fix_modules.sh` inside the polybar folder in the `.config`, doesn't running that one fix it?
> 
> I've run it, but it doesn't work at all

Hmm.. the same thing happend to me some days ago, but I have no idea what fixed it.. I just ended up with using another style for a while and then I got some kind of problem with that other one and changed back to forest, and it was fixed lol

**Comment by Januar71** [comment]
> > > There's a `fix_modules.sh` inside the polybar folder in the `.config`, doesn't running that one fix it?
> > 
> > 
> > I've run it, but it doesn't work at all
> 
> Hmm.. the same thing happend to me some days ago, but I have no idea what fixed it.. I just ended up with using another style for a while and then I got some kind of problem with that other one and changed back to forest, and it was fixed lol

i don't know but anyway, thanks for the help, i appreciate that

**Comment by toricorn** [comment]
> > > > There's a `fix_modules.sh` inside the polybar folder in the `.config`, doesn't running that one fix it?
> > > 
> > > 
> > > I've run it, but it doesn't work at all
> > 
> > 
> > Hmm.. the same thing happend to me some days ago, but I have no idea what fixed it.. I just ended up with using another style for a while and then I got some kind of problem with that other one and changed back to forest, and it was fixed lol
> 
> i don't know but anyway, thanks for the help, i appreciate that

Now the same thing happend to me again lol..

**Comment by negativeExponent** [comment]
configure LANG/locale properly. last time i checked, it has to be en

**Comment by toricorn** [comment]
> configure LANG/locale properly. last time i checked, it has to be en

Doesn't fix it unfortunately.. why would the lang/locale change itself when already set to en?

**Comment by adi1090x** [comment]
Use UTF8
