### ISSUE TITLE
The media keys seem not to be mapped on any german keyboard layout.

### ISSUE THREAD

**Issue by Magolor44** [archcraft-os/archcraft#85]
I have tried every method to raise/lower the volume with every compination I could imagine an it just did not work. I just wanted to know if they are mapped and if yes on which buttons they are mapped since XF86 is not really a helpful description.

**Comment by negativeExponent** [comment]
if your keyboard do not have any media keys on them, then you will have to modify the config files to add your own hotkeys to them...

bspwm:
https://github.com/archcraft-os/archcraft/blob/master/iso/airootfs/etc/skel/.config/sxhkd/sxhkdrc#L48-L50

openbox:
https://github.com/archcraft-os/archcraft/blob/master/iso/airootfs/etc/skel/.config/openbox/rc.xml#L322-L330

**Comment by Magolor44** [comment]
Problem is: They are mapped to my function keys by my manufacturer and pretty much every OS and Linux distro seem to automatically recognise them except ArchCraft.
