### ISSUE TITLE
virtualbox-guest-dkms is removed from the repository

### ISSUE THREAD

**Issue by xukai92** [archcraft-os/archcraft#88]
With a fresh installation, and do `sudo pacman -Syy && sudo pacman -Syu`,
you will get error message about incompatibility between `virtualbox-guest-dkms` and `virtualbox-guest-utils-nox`.

I checked that `virtualbox-guest-dkms` is actually removed from the repository.
Does it sill make sense for the ISO to ship `virtualbox-guest-dkms` in this case?

Ref: https://archlinux.org/packages/community/x86_64/virtualbox-guest-dkms/

**Comment by adi1090x** [comment]
Already removed in upcoming update.

**Comment by xukai92** [comment]
Thanks! Any hints on when's the next release?
