### ISSUE TITLE
How to change the blue of LXDM color to red ?

### ISSUE THREAD

**Issue by Heliferepo** [archcraft-os/archcraft#9]
How should I do to change the blue color  into red for everything as LXDM and for the wm theme from source to build it for my custom iso

**Comment by adi1090x** [comment]
you need to install the adapta gtk theme, the red one. Then edit the lxdm config file `/etc/lxdm/lxdm.conf` and set the theme name.
also you need to  change the background image that match with your gtk theme color.

**Comment by Heliferepo** [comment]
Thanks
