### ISSUE TITLE
Can't See spotify music playing in the music player in the top bar and can't change music using keys.

### ISSUE THREAD

**Issue by yashrtalele97** [archcraft-os/archcraft#91]

**Comment by CodingArctic** [comment]
having this same thing. not exactly sure how to switch the media controls to use spotify

**Comment by ljfoster97** [comment]
I've also noticed this.
I get pop up notifications for track changes, but polybar doesn't show what songs are playing.
I'm thinking you'd have to manually configure Polybar with playerctl and some module like this
https://github.com/PrayagS/polybar-spotify

**Comment by CodingArctic** [comment]
I started using [polybar-now-playing](https://github.com/d093w1z/polybar-now-playing) for this and it works great!

**Comment by adi1090x** [comment]
default polybar config support mpd, you have to add spotify support manually.
