### ISSUE TITLE
pacman issues

### ISSUE THREAD

**Issue by MurdeRMelodY** [archcraft-os/archcraft#92]
I get the following error when trying to update the system:

:: File /var/cache/pacman/pkg/grub-silent-2.04-4-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] n
:: File /var/cache/pacman/pkg/plymouth-0.9.5-7-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] n
:: File /var/cache/pacman/pkg/polybar-3.5.5-2-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] n
:: File /var/cache/pacman/pkg/yay-10.2.2-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package (checksum))
Errors occurred, no packages were upgraded.

**Comment by adi1090x** [comment]
clear you pacman cache then try updating the system.
`sudo pacman -Scc && sudo pacman -Syyu`

**Comment by adi1090x** [comment]
Do not update grub-silent package, add it to Ignore pkgs.
It has some issues.

**Comment by MurdeRMelodY** [comment]
Ok, I'll do that. One more thing, it seems the "virtualbox-guest-dkms" package has been removed from the AUR

**Comment by xukai92** [comment]
> Ok, I'll do that. One more thing, it seems the "virtualbox-guest-dkms" package has been removed from the AUR and has been replaced with "virtualbox-guest-utils" package.

https://github.com/archcraft-os/archcraft/issues/88

**Comment by SylvanoTombo** [comment]
> clear you pacman cache then try updating the system.
> `sudo pacman -Scc && sudo pacman -Syyu`

Hi, @adi1090x , i've done the command you mentioned above but i'm still having the issue

**Comment by adi1090x** [comment]
Add Plymouth, polybar, yay, grub-silent to 'IgnorePkg' in /etc/pacman.conf

**Comment by adi1090x** [comment]
That will work, also... You should install the new ISO when it release in few days.

**Comment by SylvanoTombo** [comment]
@adi1090x thanks! and what about the upgrade of the 3 packages?

**Comment by adi1090x** [comment]
That's why i said you need to install the new ISO.

**Comment by SylvanoTombo** [comment]
Ok thanks!

**Comment by SylvanoTombo** [comment]
@adi1090x , can i build the repo to get the new iso ? or the repo will be again updated? i ask that because i need it for work.
