### ISSUE TITLE
Can't update + Archcraft repo not working

### ISSUE THREAD

**Issue by paarthjuneja** [archcraft-os/archcraft#93]
Hello, I cannot update it says `/var/cache/pacman/pkg/yay-10.2.2-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).`
Also, when I type commands in the Archcraft repo, like `sudo pacman -S ac-pixmaps`, it would fail saying `error: target not found: ac-pixmaps`
I have tried a lot of stuff, clearing pacman cache, clearing yay cache, updating keys, populating keys, etc. Nothing worked.

**Comment by SylvanoTombo** [comment]
Hi, see #92

**Comment by paarthjuneja** [comment]
> Hi, see #92

Hello, It doesn't work, already tried.

**Comment by SylvanoTombo** [comment]
Yeah! the fix is in the new ISO who will come out in a few days.

**Comment by SylvanoTombo** [comment]
@paarthjuneja , For my case! i uninstalled all packages with corrupt checksum and download the new version of package from the archcraft github.

**Comment by paarthjuneja** [comment]
Temporarily fixed by removing yay (which was causing the problem) and installing paru for now.
Waiting for new ISO.
Closing...
