### ISSUE TITLE
Pacman update complain about 3 corrupted packages. 

### ISSUE THREAD

**Issue by mixalis1987** [archcraft-os/archcraft#96]
pacman will not update because of corrupted packages. I installed archlinux-keyring and ran pacman-key --populate but nothing is working.

**Comment by mixalis1987** [comment]
Problem is the archcraft repo in pacman.conf.
Disabling it completed the update. But the "plymoth" "Polybar" and "yay" apps are still  a problem to update when I enable archcraft repo.

**Comment by adi1090x** [comment]
Fixed.
