### ISSUE TITLE
Some suggestions.

### ISSUE THREAD

**Issue by TheHamkerCat** [archcraft-os/archcraft#97]
**.1 Disable the crappy logo which comes during boot, ffs, or atleast give user an option to disable it during installation**

This will be usefull to check if there are any errors during boot, because if there is, the logo just freezes, tells the user nothing about what the problem actually is, i know you can press esc to hide the logo during boot [Took me 3 days to figure this shit out], but it's handy  for users to know what they're actually dealing with. remove these fancy shits, don't make it windows ffs.

**2. Run fsck automatically if device fails to boot 3-4 times.**

 If the boot fails because of some HDD/SDD problem like bad sectors etc, most distros out there, runs fsck, if the device fails to boot 3-4 times, **BUT THIS DISTRO DOESN'T RUNS FSCK, INSTEAD, IT SHOWS A GOOD FANCY  LOGO TO THE USER**, and expects them to fix it by magic, [happened to me 10 minutes ago that's why opening this issue]
 
 Kindly fix this in the next update, please :)

**Comment by xukai92** [comment]
I meet the same issue as well.
Maybe adding a line of text saying "Press ESC to hide the logo." is enough.

PS: I think the logo looks pretty neat and clean. Calling it "crappy" is unfair and probably not helpful for this issue.

**Comment by TheHamkerCat** [comment]
> I meet the same issue as well.
> Maybe adding a line of text saying "Press ESC to hide the logo." is enough.
> 
> PS: I think the logo looks pretty neat and clean. Calling it "crappy" is unfair and probably not helpful for this issue.

Actually, the logo itself is not crappy, the progress bar below it **is**, when device fails to boot, the bar keeps filling up, giving user the fake hope that his device will boot [takes almost 2-3 minutes to completely fill]

btw,  adding "Press ESC to hide the logo." is probably a better idea then removing the logo

**Comment by adi1090x** [comment]
I'll consider it.
