### ISSUE TITLE
ISO Checksum

### ISSUE THREAD

**Issue by Niv1900** [archcraft-os/archcraft#99]
Hello there, 

How to verify that my ISO file downloaded from sourceforge.net is correct ?

I can't find the md5, sha256 checksum values

**Comment by adi1090x** [comment]
https://sourceforge.net/projects/archcraft/files/Archcraft_05_2021/

**Comment by fama** [comment]
Would it be possible to publish also GPG signatures for authenticity?  There is no way to verify the signature.  What if sourceforge gets hacked?  It would also allow for distribution via tor and other channels.
Similar to https://manjaro.org/downloads/official/xfce/

**Comment by adi1090x** [comment]
@fama ... Right, I'll create a sig file and put it on the website.
